### ISSUE TITLE
Spec fails if our Enumerable type does not implement #dup

### ISSUE THREAD

**Issue by trejkaz** [rspec/rspec-expectations#1004]
I recently encountered a spec like this:

```
        expect { set.remove_items(all_items) }.to change { set.items }.to be_empty
```

This caused an unexpected NPE inside JRuby itself, which I filed over at jruby/jruby#4721.

We were running under JRuby, and in this case, `set.items` returned a custom collection class of ours which does not implement `Cloneable` and thus cannot currently support `#dup`.

The call in question is [here](https://github.com/rspec/rspec-expectations/blob/a72cb503934d6a1d40755030559044cd7226487c/lib/rspec/matchers/built_in/change.rb#L368):

```
        def evaluate_value_proc
          value_proc = @value_proc || lambda { @receiver.__send__(@message) }

          case val = value_proc.call
          when IO # enumerable, but we don't want to dup it.
            val
          when Enumerable, String
            val.dup
          else
            val
          end
        end
```

Even if JRuby fixes the issue and throws a `TypeError` or similar, consistent with other classes which cannot be duped (e.g. `FixedInt`), it seems like RSpec might want to catch this exception and simply not duplicate the collection or something.

**Comment by myronmarston** [comment]
The problem is that the `change` matcher does not work correctly on collection types unless it can `dup` them.  Here's how it works:

* Stash a reference to the item returned by the `change` block
* Run the `expect` block
* Get the new value returned by the `change` block
* Compare the before/after values to see if they are different

If we do not `dup` the collection, then we are simply comparing two references to the exact same mutable object, and our before/after values will be the exact same.  For the `change` matcher to work properly, we need a way to store a reference to the original value _as it was before the expect block ran_, and using `dup` is the only way we've found to do that.

Can you think of a way to get the `change` matcher to work properly on collections like yours?

**Comment by trejkaz** [comment]
Simply not duping would make it work correctly on our collections, because we ensure that our APIs do not return mutable objects.

I can't think of a way to figure out whether a collection is mutable without trying to mutate it, though. :/

**Comment by myronmarston** [comment]
If `set.items` does return a different instance before vs after, then that would indeed work.  That's sadly not the norm in ruby, though :(.

Anyhow, I think we can add `respond_to?(:dup)` check before calling `dup`.  The question is -- if it doesn't respond to `dup`, should we warn?  Or just silently do nothing, and potentially fail to match in a confusing way?

**Comment by trejkaz** [comment]
Well, the messy thing here is that any `Object` responds to `#dup`, so you'll always get a true result for that check, I think. Some just throw a `TypeError` when you call it. :(

The odds are I'll be writing some specs to expect JRuby to throw `TypeError` instead of getting the current unexpected exception, and then seeing if there is a way to avoid that for each of our classes which might be returned. Most of the time, the actual class we're returning is not immutable in itself, but is a store-nothing wrapper for another class which is immutable.

**Comment by myronmarston** [comment]
Answering my own question after thinking about it for a minute: I think we should _not_ directly warn if it doesn't respond to `dup`, but we should include a note in the failure message about this case, if all of these criteria are met:

* It's an object that we'd normally try to `dup` (e.g. `Enumerable` or `String`)
* The object does not respond to `dup`
* The before/after objects are the exact same instance

In that case, we can include a note in `failure_message`/`failure_message_when_negated` like:

> Note: the `change` matcher had to compare the exact same before/after object value, which might be causing the failure.  Usually RSpec will `dup` the object in this case so it can compare the after value against the original before value, but it could not in this case.  To fix this, make your object support `dup` or change the code in the `change` block to return a different instance each time it is evaluated.

**Comment by myronmarston** [comment]
> Well, the messy thing here is that any Object responds to #dup, so you'll always get a true result for that check, I think. Some just throw a TypeError when you call it. :(

Good to know.  We can add a `rescue` for `TypeError` for sure.

**Comment by myronmarston** [comment]
Are you willing to take a stab at fixing this?

**Comment by trejkaz** [comment]
Yeah, I'll see what I can do after we've pinned down the expected behaviour on the JRuby side.

**Comment by trejkaz** [comment]
jruby/jruby#4721 got fixed a while back, but I ended up getting moved off Ruby stuff, so I have had zero time to deal with any of this, and setting up to test this is probably going to take more time than I have available to look at it. So sadly I'm going to have to drop this on the floor after all. :(

On the bright side, whatever JRuby did on their side might have fixed it anyway, so maybe we can just close it in the hope that it has.

**Comment by pirj** [comment]
@trejkaz can you please confirm that the issue can still be reproduced?

I believe the problem with `dup` [was addressed](https://github.com/rspec/rspec-expectations/pull/1034/files#diff-16590f2e55b8f971bf68733232e5eca9L368) and [released in 3.8.0](https://github.com/rspec/rspec-expectations/blob/master/Changelog.md#380--2018-08-04).

**Comment by trejkaz** [comment]
Looks good to me.

Actually, I tried to run against 3.8.0 but we have some other things we have to address to test it in the place we originally discovered it, but I read the change itself, and it seems like this issue is now at the very least obsolete.

**Comment by pirj** [comment]
Awesome, thank you!
