### ISSUE TITLE
How to check raise_no_error 

### ISSUE THREAD

**Issue by stoivo** [rspec/rspec-expectations#1015]
Hi, I Love Rspec.

I would like to do this
```ruby
expect{
  # Something
}.to change(Car, :count).by(1)
.and change(Wheel, :count).by(4)
.and raise_no_error
```
`raise_no_error` does not exist's. `raise_error` does. 
So we could do 
```ruby
expect{
  expect{
  # Something
  }.to change(Journal, :count).by(1)
  .and change(Voucher, :count).by(2)
}.not_to raise_error
```

I just wondered if this is how I should do this?
Or is possible to introduce raise_no_error? I checked out the source I found https://github.com/rspec/rspec-expectations/blob/430cf59249ebe0291bcfec88d76b1c914a52ad11/lib/rspec/matchers.rb#L759-L761.

**Comment by myronmarston** [comment]
You can define a negated form of any matcher in one line using `define_negated_matcher`:

``` ruby
# in spec_helper.rb
RSpec::Matchers.define_negated_matcher :raise_no_error, :raise_error
```

``` ruby
# in your spec file:
expect{
  # Something
}.to change(Car, :count).by(1)
.and change(Wheel, :count).by(4)
.and raise_no_error
```

BTW, you might find my book useful.  It goes into a great detail about RSpec, including this issue:

http://rspec.info/blog/2017/09/effective-testing-with-rspec-3-released/

**Comment by stoivo** [comment]
Oh, that's how define_negated_matcher is working. Super cool!
