### ISSUE TITLE
The all Matcher provides false positives when empty

### ISSUE THREAD

**Issue by uchagani** [rspec/rspec-expectations#1019]
When using the ```all``` matcher, if the item being matched against is empty the expectation returns true instead of false.  For example:

```ruby
expect([]).to all include "abc"
```

The above expectation would return ```true``` when it should return ```false``` since the empty array doesn't include ```abc```

**Comment by myronmarston** [comment]
While it's counter intuitive, it's logically correct, for the same reason that Ruby returns `true` in this case:

``` irb
irb(main):002:0> [].all? { |i| i.odd? }
=> true
```

`i.odd?` is in fact true of every element in the collection; it's just that it doesn't have elements.  If it returned `false`, it would imply that there is at least one element in the collection for which `i.odd?` does not hold true,  which is not correct.

I agree this is a gotcha, though; it's one reason I covered it in [Effective Testing with RSpec 3: Build Ruby Apps with Confidence](https://pragprog.com/book/rspec3/effective-testing-with-rspec-3).  My suggestion from the book is to do this:

``` ruby
RSpec::Matchers.define_negated_matcher :have_elements, :be_empty

expect([]).to have_elements.and all include "abc"
```

**Comment by beyondcompute** [comment]
Got hit by this today 😔. Would be in practice helpful if the [documentation](https://relishapp.com/rspec/rspec-expectations/v/3-8/docs/built-in-matchers/all-matcher) mentioned this behavior.

Interesting note about [vacuous truths](https://en.wikipedia.org/wiki/Vacuous_truth) from Wikipedia:
> Outside of mathematics, statements which can be characterized informally as vacuously true can be misleading. Such statements make reasonable assertions about qualified objects which do not actually exist. For example, a child might tell their parent "I ate every vegetable on my plate", when there were no vegetables on the child's plate to begin with. 

🤷‍♂️

**Comment by benoittgt** [comment]
@beyondcompute PR welcome for the documentation :)
