### ISSUE TITLE
Jruby argument mismatch error

### ISSUE THREAD

**Issue by t0il3ts0ap** [rspec/rspec-expectations#1022]
I have the following class

```
java_import com.gopay.client.BCAWithdrawalClientConnection
java_import com.gopay.client.BCAWithdrawalClient

class BcaWithdrawalClient
  def initialize
      conn = BCAWithdrawalClientConnection.getInstance(ENV.to_java_map)
      @client = BCAWithdrawalClient.new(conn)
  end
end
```

When I try to mock `BCAWithdrawalClientConnection.getInstance` with
    `expect(BCAWithdrawalClientConnection).to receive(:getInstance).with(any_args)`

 it always fails with 
```
  1) BcaWithdrawalClient.make_request makes grpc request to bca withdrawal service
     Failure/Error: conn = BCAWithdrawalClientConnection.getInstance(ENV.to_java_map)

     ArgumentError:
       Wrong number of arguments. Expected 0, got 1.
     # ./app/clients/bca_withdrawal_client.rb:10:in `initialize'
     # ./spec/clients/bca_withdrawal_client_spec.rb:24:in `block in (root)'
```
I have tried all possible tweaks, but this error is not getting resolved.
I am able to mock methods without any argument in java classes though

**Comment by myronmarston** [comment]
To help us troubleshoot this, can you run this snippet in irb in the context of your project and paste what it returns?

``` irb
> BCAWithdrawalClientConnection.method(:getInstance).parameters
```

**Comment by t0il3ts0ap** [comment]
```
irb(main):005:0> BCAWithdrawalClientConnection.method(:getInstance).parameters
=> []

```
The code is working fine with the parameter I am passing.

**Comment by myronmarston** [comment]
This is a JRuby bug.  If `getInstance` accepts arguments (even optional ones or a splat), `method(:getInstance).parameters` should return information about those arguments.  Instead, it is telling RSpec that the method accepts no arguments by returning an empty array.  Please report this to JRuby.  Actually, there are some prior issues regarding `#parameters` that have been reported to JRuby and fixed.  So, you might try upgrading to the latest JRuby release to see if that fixes your issue.

If it doesn't, you can work around this by disabling partial double verification:

``` ruby
RSpec.configure do |rspec|
  rspec.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = false
  end
end
```

Just know that that config prevents RSpec from verifying that your partial doubles are limited in their interface to what the existing object already provides.  Turning it off is unfortunate, but perhaps necessary when working in an environment that misreports what parameters methods accept.
