### ISSUE TITLE
RSpec Test Failing.

### ISSUE THREAD

**Issue by manroy04** [rspec/rspec-expectations#1024]
Hello All,
I am facing issue while running spec.rb file to test against dockerfile.

ERROR:
Failure/Error: @image = Docker::Image.build_from_dir('.')
     Docker::Error::TimeoutError:
       read timeout reached
       
     # /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/connection.rb:52:in `rescue in request'
     # /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/connection.rb:38:in `request'
     # /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
     # /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/image.rb:274:in `build_from_tar'
     # /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/image.rb:293:in `build_from_dir'
     # ./dockerfiles/petclinicapp/petclinicapp_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # IO::EAGAINWaitReadable:
     #   Resource temporarily unavailable - read would block
     #   <internal:prelude>:76:in `__read_nonblock'

Need Help in that to fix this issue.

Need to

**Comment by myronmarston** [comment]
This doesn't look like an RSpec issue.  Please reach out to the Docker maintainers for docker help.

**Comment by manroy04** [comment]
Hi 
when i am doing this testing manually it is working fine. but by using jenkins i am getting this above mention error.

**Comment by myronmarston** [comment]
We don't maintain jenkins, either.

If you think you've found a bug in RSpec, please provide a [SSCCE](http://sscce.org/) that demonstrates the bug you think you've found.

If you're just asking for help with Docker/Jenkins, this isn't the right place.  We aren't responsible for or affiliated with those tools in anyway.

In general, we can provide some minimal help and advice for self-contained RSpec issues, but we would need a ton more information than you've provided (e.g. what behavior you are seeing vs what behavior you expect, a reproducible example we can play with to troubleshoot, etc).  But even then, we often can't help, and provide RSpec support as a free service to the community on our free time.

Sorry if that's not what you're looking for but it's all we can provide.
