### ISSUE TITLE
Negative predicate marchers  for `.from(..).to()` cases

### ISSUE THREAD

**Issue by equivalent** [rspec/rspec-expectations#1028]
Hi, let say I have a class:

```ruby
class User
  # ...
 def confirmed?
   # ...
 end
   
 def not_confirmed?
   !confirmed?
 end
end
```

it is possible to write this with RSpec

```ruby
 expect { trigger }
  .to change { user }
  .from(be_not_confirmend)
  .to(be_confirmed)
```

but imagine the `User#not_confirmed?` does not exist. Would it be possible to write something like this in RSpec ?:

```
expect { trigger }
   .to change { user.reload }
  .from(negative(be_confirmed))
  .to(be_confirmed)

# negative don't exist in RSpec (or does it? ) 

# or 
expect { trigger }
   .to change { user.reload }
  .from(negative_be_confirmed)
  .to(be_confirmed)

# negative_be could be RSpec built in negative predicate matcher
```

Do you think it's worth implementing something like this `negative` (negation of matcher )  to RSpec ? Or do you rather recommend to stick with:

```
expect { trigger }
  .to change { user.confirmed? }
  .from(false)
  .to(true)
```

just for record:

I don't think that negative predicate matchers are good idea in cases like:

```
expect(user).to  negative(be_confirmed)
expect(user).to  negative_be_confirmed

```

 yes much better sence is to use:

```
expect(user).not_to be_confirmed
```

but I think as a coincidence of this implementation that may be possible.

**Comment by JonRowe** [comment]
You can try using `RSpec::Matchers.define_negated_matcher` to define a negated version of `be_confirmed` I think that'll work despite the `be_` matcher being "magic"

**Comment by myronmarston** [comment]
A prior attempt was made to add generic negation method (like you're asking for) in #505 but ultimately we decided against it because we couldn't come up with a way to provide a readable description/failure message for the negated matcher.  Our solution was to provide `define_negated_matcher` which lets the user define the negated form/phrasing of the matcher.
