### ISSUE TITLE
Capybara::ElementNotFound: Unable to find visible xpath "/html"

### ISSUE THREAD

**Issue by OnlySteveH** [rspec/rspec-expectations#1029]
I am getting an error on running a failing test. The test should fail at this point but the backtrace gives me a load of errors that indicates some sort of conflict. 

The test:

```
  scenario "a user fails to create a new article" do
    visit "/"
    click_link "New Article"
    fill_in "Title", with: ""
    fill_in "Body",  with: ""
    click_button "Create Article"
    expect(page).to have_content("Article has not been created")
    expect(page).to have_content("Title can't be blank")
    expect(page).to have_content("Body can't be blank")
  end
```
This should fail as there's no validation for blank fields yet. The backtrace gives me:

```
  1) creating articles a user fails to create a new article
     Failure/Error: expect(page).to have_content("Article has not been created")
     
     Capybara::ElementNotFound:
       Unable to find visible xpath "/html"
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/base.rb:81:in `synchronize'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/finders.rb:37:in `find'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/document.rb:24:in `text'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/queries/text_query.rb:94:in `text'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/queries/text_query.rb:25:in `resolve_for'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/matchers.rb:707:in `block in _verify_text'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/base.rb:85:in `synchronize'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/matchers.rb:706:in `_verify_text'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/matchers.rb:615:in `assert_text'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/session.rb:792:in `block (2 levels) in <class:Session>'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/rspec/matchers.rb:116:in `block in matches?'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/rspec/matchers.rb:27:in `wrap_matches?'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/rspec/matchers.rb:116:in `matches?'
     # ./spec/features/creating_article_spec.rb:22:in `block (2 levels) in <top (required)>'
```

So there's something in the rspec matchers that's throwing an error making the test fail messily. 

I'm working in the Cloud 9 IDE where `gem environment` gives me:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.3.4 (2017-03-30 patchlevel 301) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.3.4
  - USER INSTALLATION DIRECTORY: /home/ubuntu/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-2.3.4/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.3.4/bin
  - SPEC CACHE DIRECTORY: /home/ubuntu/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.3.4
     - /usr/local/rvm/gems/ruby-2.3.4@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/ubuntu/.nvm/versions/node/v6.11.2/bin
     - /usr/local/rvm/gems/ruby-2.3.4/bin
     - /usr/local/rvm/gems/ruby-2.3.4@global/bin
     - /usr/local/rvm/rubies/ruby-2.3.4/bin
     - /mnt/shared/bin
     - /home/ubuntu/workspace/node_modules/.bin
     - /home/ubuntu/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /mnt/shared/sbin
     - /opt/gitl
     - /opt/go/bin
     - /mnt/shared/c9/app.nw/bin
     - /usr/local/rvm/bin

Please let me know if you need for information, or if this post is better placed elsewhere.

**Comment by OnlySteveH** [comment]
More on this. If I add validation to the `Article` model, the above error/failure results. So, with this:

```
class Article < ApplicationRecord
  validates :title, presence: true
end
```

... the above scenario is true. 

Removing that validation:

```
class Article < ApplicationRecord
  #validates :title, presence: true
end
```

And the test works as expected and fails gracefully:
```
Failures:

  1) creating articles a user fails to create a new article
     Failure/Error: expect(page).to have_content("Article has not been created")
       expected to find text "Article has not been created" in "Blog App Authors Article has been created New Article"
     # ./spec/features/creating_article_spec.rb:22:in `block (2 levels) in <top (required)>'

Finished in 0.2963 seconds (files took 3.12 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/features/creating_article_spec.rb:16 # creating articles a user fails to create a new article
```
There is a title in the `articles` table:

```
  create_table "articles", force: :cascade do |t|
    t.string "title"
    t.text "body"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

**Comment by xaviershay** [comment]
I'm not sure what expected default behaviour is here (sorry don't have a test harness available right now), but https://relishapp.com/rspec/rspec-core/docs/configuration/excluding-lines-from-the-backtrace is probably what you want to fix.

A quick search of places I would expect to see Capybara configure itself to be excluded from backtraces doesn't appear to have anything for setting it up:
* https://github.com/rspec/rspec-rails/blob/2fb410b2670fdaf22f6bd2d0b8d67f9d1b78334d/lib/rspec/rails/vendor/capybara.rb
* https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec/features.rb

Going to optimistically close this per policy, but anyone please do reopen if we have reason to suspect this is a widespread issue.
