### ISSUE TITLE
'change' matcher using incorrect initial value (with Vectors nested in arrays)

### ISSUE THREAD

**Issue by jrmhaig** [rspec/rspec-expectations#1030]
When using vectors nested inside a hash inside an array the change matcher appears to take the resulting value as the initial value.

For example;

```ruby
require 'matrix'

RSpec.describe 'vectors' do
  let(:vectors) { [{ a: Vector[1, 2] }] }

  it 'adds to the vector' do
    expect { vectors[0][:a] += Vector[1, 1] }
      .to change{vectors}
      .from( [{a: Vector[1, 2] }] )
      .to( [{a: Vector[2, 3]}] )
  end
end
```

When I run this test I get:

```
Failures:

  1) vectors adds to the vector
     Failure/Error:
       expect { vectors[0][:a] += Vector[1, 1] }
         .to change{vectors}
         .from( [{a: Vector[1, 2] }] )
         .to( [{a: Vector[2, 3]}] )

       expected `vectors` to have initially been [{:a=>Vector[1, 2]}], but was [{:a=>Vector[2, 3]}]
     # ./spec/test_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.02426 seconds (files took 0.12668 seconds to load)
1 example, 1 failure
```

If I remove the `from` section I then get a failure saying that `vectors` did not change.

I am using rspec 3.7.0 and Ruby 2.4.1

**Comment by myronmarston** [comment]
This can be reproduced w/o involving `Vector`:

``` ruby
RSpec.describe 'change' do
  let(:data) { [{ a: [1, 2] }] }

  it 'updates the nested array' do
    expect { data[0][:a] << 3 }
      .to change { data }
      .from( [{a: [1, 2] }] )
      .to( [{a: [1, 2, 3]}] )
  end
end
```

This produces:

```
change
  updates the nested array (FAILED - 1)

Failures:

  1) change updates the nested array
     Failure/Error: expect { data[0][:a] << 3 }
       expected result to have initially been [{:a=>[1, 2]}], but was [{:a=>[1, 2, 3]}]
     # ./spec/foo_spec.rb:5:in `block (2 levels) in <top (required)>'
```

Here's what's going on:

* The matcher executes the `change` block and stores the value as the `before_value`.  The `before_value` is a reference to the `vectors` array.
* The matcher executes the `expect` block to trigger the change
* The matcher again executes the `change` block, and stores the value as the `after_value`.  The `after_value` is another reference to the exact same `vectors` array.
* The matcher compares the `before_value` and `after_value` to see if there was a change.  I this case, they are references to the _exact same object_ and at the point it compares them, they are equal so it does not look like a change has occurred.

This has long been a known issue with the `change` matcher; see #41.  To work around this, we `dup` the compared value if it's a commonly mutated object:

https://github.com/rspec/rspec-expectations/blob/v3.7.0/lib/rspec/matchers/built_in/change.rb#L361-L372

...but this does only a _shallow_ dup, and in this case, it's a deeply nested object that is being mutated.  I think to fix this we'd have to "deep dup" the object, but there are a few issues with doing that:

* Ruby does not provide any sort of "deep dup" method.  In the past, I've used `Marshal.load(Marshal.dump(object))`, but that isn't guaranteed to work on all objects. (In some cases, it will throw exceptions).
* Trying to figure out if we can safely use marshalling to deep dup an object is non-trivial.
* This could have a huge impact on the performance of the `change` matcher when dealing with large object graphs, so I'm not sure it's something we should automatically do, even if we could.

We could potentially improve the failure message, though.

**Comment by myronmarston** [comment]
Actually, I think I've thought of a way to get your example to work: instead of holding a reference to the `before_value`, call `hash` on it, and compare to the `hash` of the `after_value`.  All the built-in mutable collection types take the full nested contents of their data into account when computing the `hash`, and a change at any level of a nested data structure should produce a different `hash` value.  We'd also have to evaluate anything based on the `before_value` (such as bits of potential failure messages) before running the `expect` block to get accurate results as well.

I think that could work very well, and it would largely remove our need for `dup`ing.

Thoughts from @rspec/rspec ?

**Comment by JonRowe** [comment]
This seems like a good idea to me!

**Comment by jrmhaig** [comment]
Thank you for the responses. This isn't causing me a great problem as I discovered this doing an [Advent Of Code puzzle](http://adventofcode.com/2017/day/20) so it is a little contrived and not something I need for an important development pipeline. :-)

I did simplify my example quote a lot but I should have thought to remove the vectors too.

**Comment by pirj** [comment]
Hey

There's a spec that used to work, but is failing now:
```
  it { expect { 'noop' }.not_to change { country.reload.cities } }
```

The thing is that even though `country.reload.cities` is still an empty set, the `ActiveRecord::Associations::CollectionProxy` that represents it changes its `hash` value on each `reload`.

This looks like a shortcoming of the `CollectionProxy` itself, as it's lazy, and by definition can't consider the results of the query evaluation in its `hash`.

Ended up with a hacky `{ country.reload.cities.to_a }` all over the spec suite.

Any advice on how to get rid of this hack?

**Comment by pirj** [comment]
cc @samphippen

**Comment by JonRowe** [comment]
> Any advice on how to get rid of this hack?

Unfortunately I think the only advice we could offer at the moment would be to ask / help the Rails team to implement a consistent hash. You could monkey patch it yourself by adding:

```
def hash
  to_a.hash
end
```

To the definition of the CollectionProxy in your spec suite?

**Comment by samphippen** [comment]
@pirj I'd say that this isn't an RSpec bug, and that you should file an issue with the Rails team if you think `ActiveRecord::Associations::CollectionProxy#hash` should behave differently.
