### ISSUE TITLE
Composable#should_enumerate? fails when items in a collection implement an `#equal?`

### ISSUE THREAD

**Issue by johvet** [rspec/rspec-expectations#1039]
The following example passes for me:
```
# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'Something', type: :model do
  context 'with a class having an #equal? method' do
    before do
      class Something
        def equal?; false; end
      end
    end

    # Remove the temporary class
    after { Object.send(:remove_const, :Something) }

    let(:a1)  { Array.new(2) { Something.new } }
    let(:a2)  { Array.new(2) { Something.new } }

    it { expect { expect(a1).to match_array(a2) }.to raise_error(ArgumentError, /wrong number of arguments/) }
  end
end
```

We try to match a collection of ActiveRecord instances having an enum where `:equal` is a legit enum option. Of course ActiveRecord defines a method `equal?` for that then. And that conflicts with `Composable#should_enumerate?` which (since 3.4.0) does something like:

```
Array === item && item.none? { |subitem| subitem.equal?(item) }
```

So should we now avoid using objects implementing an `equal?` method?

**Comment by myronmarston** [comment]
Thanks for reporting this!

We can certainly avoid using `equal?` within RSpec, by using `obj1.__id__ == obj2.__id__`.  Are you willing to open a PR to make that change?  It's probably worth looking for other usages of `equal?` while you are at it.

All that said: if your objects redefine `equal?` to mean something entirely different from `Object#equal?`, you're bound to have problems like these.  Libraries like RSpec have to be able to use core Ruby methods like `equal?`.  We can work around it here, but you might find that your object has problems integrating with other libraries.  ActiveRecord should perhaps not define `equal?` in this case (as it makes it so the object cannot integrate with some libraries, and may even break the object from working properly with rails itself!), or you might consider choosing a different enum value (e.g. `:eq` or `:__equal`) to avoid this issue.

**Comment by johvet** [comment]
Hi Myron,

Thank you for the quick reply. 

> Thanks for reporting this!
> We can certainly avoid using equal? within RSpec, by using obj1.__id__ == obj2.__id__. Are you willing to open a PR to make that change? It's probably worth looking for other usages of equal? while you are at it.
> 
I can definitely make a PR if the above is the approach you guys consider to be right. 
> All that said: if your objects redefine equal? to mean something entirely different from Object#equal?, you're bound to have problems like these. Libraries like RSpec have to be able to use core Ruby methods like equal?. We can work around it here, but you might find that your object has problems integrating with other libraries. ActiveRecord should perhaps not define equal? in this case (as it makes it so the object cannot integrate with some libraries, and may even break the object from working properly with rails itself!), or you might consider choosing a different enum value (e.g. :eq or :__equal) to avoid this issue.
> 
I totally agree, our mistake was to use :equal as a state in the enum in the first place, since it is really asking for troubles as you have correctly outlined above. I’ve changed our code to use :equal_to

Many thanks again for checking this real quick, and please let me know if I should create a PR using __id__ comparison, although the APIdoc explicitly states:

>> Unlike ==, the equal? <https://apidock.com/ruby/Object/equal%3F> method <https://apidock.com/ruby/Object/method> should never be overridden by subclasses: it is used to determine object identity (that is, a.equal? <https://apidock.com/ruby/Object/equal%3F>(b) if a is the same object as b).

So taking that into consideration, rspec-expectations might be just fine leaving it the way it is, and maybe a better thing to do would be to amend enum to be more cautious about the method it generates.

best

Johannes Vetter

**Comment by xaviershay** [comment]
I have a nagging feeling that doing `__id__` comparison we'll someday get a similar issue on the opposite side of the fence ("Something overrode `equal?` (possibly incorrectly) and RSpec isn't respecting that!") As a result, I err on the side of not changing.

**Comment by myronmarston** [comment]
We don't generally put in effort to avoid issues with objects that behave incorrectly w.r.t. the standard ruby object protocols, but we've always been happy to merge contributor PRs that provide non-hacky work arounds.  I feel the same here: I don't have the time to tackle this (particularly since it's a niche issue) but I'd happily merge a PR with a fix if you want to provide on @johvet.  After all, this should make RSpec work correctly with more objects.

> I have a nagging feeling that doing `__id__` comparison we'll someday get a similar issue on the opposite side of the fence ("Something overrode `equal?` (possibly incorrectly) and RSpec isn't respecting that!") As a result, I err on the side of not changing.

I don't expect someone to complain about our usage of `__id__` over `equal?` if we switch it; after all, our use of `equal?` is an internal implementation detail.  In addition, `equal?` is not intended to be a polymorphic API (as indicated by the ruby docs saying it should never be overridden by subclasses).  Honestly, I wish Ruby provided a class method for core object methods that aren't intended to be polymorphic to avoid issues with accidental overrides, but that ship has obviously sailed.

Anyhow, I'm going to close this issue since we're not intending to take action on it, but as I said above, we'd gladly merge a PR with the `__id__ == __id__` fix, @johvet.
