### ISSUE TITLE
missing set expectation?

### ISSUE THREAD

**Issue by axos88** [rspec/rspec-expectations#1046]
I'm really missing a `set` expectation, that is similar to `change`, but doesn't call the block beforehand, like so:

```
  specify { expect { operation(context, args) }.to set { context.result.value }.to 5 }
```

Having such an expectation would allow me not to have to repeat the following in all tests:

```
  specify do
    operation(context, args)
    expect(context.result.value).to eq(5)
  end
```

And allow for one-liners.

In some simple cases, it would be possible to use 

```
  specify { expect { operation(context, args) }.to change { context.result }.to 5
```

but not if the block would raise (a `NoMethodError` for `NilClass` for example).

**Comment by axos88** [comment]
Actually I would expect 

```
  specify { expect { operation }.to set { value }.to matcher
```

and 
```
  specify do
    operation(contxt, args)
    expect(value).to matcher
  end
```

to be equivalent

**Comment by JonRowe** [comment]
As you point out, this is equivalent to doing:

```Ruby
operation(contxt, args)
expect(value).to matcher
```

The point of the block based matchers is to be able to execute things more than once in order to evaluate the change, so I'm not sure why you want this?

**Comment by axos88** [comment]
In a context block containing a bunch of these:

```
  context "..." do
    subject { ... }
    
    specify { expect { subject }.to set { context.result.foo.bar1 }.to 5
    specify { expect { subject }.to set { context.result.foo.bar2 }.to 5
    specify { expect { subject }.to set { context.result.foo.bar3 }.to 5
    specify { expect { subject }.to set { context.result.foo.bar4 }.to 5
    specify { expect { subject }.to set { context.result.foo.bar5 }.to 5
    specify { expect { subject }.to set { context.result.foo.bar6 }.to 5
    specify { expect { subject }.to set { context.result.foo.bar7 }.to 5
```

Is much more readable to

```
  context "..." do
    subject { ... }
    
    specify do
      subject
      expect(context.result.foo.bar1).to eq(5)
   end

    specify do
      subject
      expect(context.result.foo.bar2).to eq(5)
   end

    specify do
      subject
      expect(context.result.foo.bar3).to eq(5)
   end

    specify do
      subject
      expect(context.result.foo.bar4).to eq(5)
   end

    specify do
      subject
      expect(context.result.foo.bar5).to eq(5)
   end

    specify do
      subject
      expect(context.result.foo.bar6).to eq(5)
   end

    specify do
      subject
      expect(context.result.foo.bar7).to eq(5)
   end

end
```

Also, in my test I wish to express the fact that my expectation is that performing the `subject` is what sets the value of `{ ... }` to `5`

**Comment by JonRowe** [comment]
```
before { subject }
specify { expect(context.result.foo.bar1).to eq(5) }
specify { expect(context.result.foo.bar2).to eq(5) }
specify { expect(context.result.foo.bar3).to eq(5) }
specify { expect(context.result.foo.bar4).to eq(5) }
specify { expect(context.result.foo.bar5).to eq(5) }
specify { expect(context.result.foo.bar6).to eq(5) }
specify { expect(context.result.foo.bar7).to eq(5) }
```

Is even more terse, and if you're after terseness take a look at `rspec-its`

```Ruby
subject do
  operation(context, args)
  context
end

its(:result) { is_expected.to eq 1 }
```

**Comment by axos88** [comment]
I find the first suggestion a bit appalling, as afaik the before blocks are for seting up the test, not actually performing it

The second one still feels like a workaround, but I guess I will work with that.

**Comment by JonRowe** [comment]
> I find the first suggestion a bit appalling, as afaik the before blocks are for seting up the test, not actually performing it

The test is the expectation. `operation(context, args)` is setup as you're not expecting on its output.

**Comment by myronmarston** [comment]
@axos88 honestly, I'd recommend just using one example here, with `:aggregate_failures` so you get each failure listed:

``` ruby
it 'sets the expected attributes', :aggregate_failures do
  subject
  expect(context.result.foo.bar1).to eq(5)
  expect(context.result.foo.bar2).to eq(5)
  expect(context.result.foo.bar3).to eq(5)
  expect(context.result.foo.bar4).to eq(5)
  expect(context.result.foo.bar5).to eq(5)
  expect(context.result.foo.bar6).to eq(5)
  expect(context.result.foo.bar7).to eq(5)
end
```

* It's the most readable/succinct of all (much less noise!)
* It's going to be the fastest, as this approach triggers the `subject` operation once instead of N times
* You get each expectation failure listed individually like you want
* You can provide a descriptive string describing the behavior you're specifying
* Requires the least cognitive overhead to understand
* Doesn't require the use of a new matcher

If you really want a `set` matcher, I'd encourage you to create your own; rspec-expectations ships with [an API that makes it easy to write your own matchers](https://relishapp.com/rspec/rspec-expectations/v/3-7/docs/custom-matchers/define-a-custom-matcher) for when you want to do something not already supported.
