### ISSUE TITLE
Unfriendly descriptions when mixing argument matchers from rspec-mocks with builtin matchers

### ISSUE THREAD

**Issue by zverok** [rspec/rspec-expectations#1049]
Example:

```ruby
expect(some_response).to include(meta: include(next_page: end_with('?offset=100'))
```
This works, and produces decent description on fail: `expected to (include {:meta => (include {:next => (end with "offset=100")})})`, but reads a bit weird: "include(meta → include(...))"? What?..

This on the other hand, reads more natural:
```ruby
expect(some_response).to include(meta: hash_including(next_page: end_with('?offset=100'))
```
...but generates not very friendly description: 
```
expected to (include {:meta => #<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x000055610e9c3cd0 @expected={:next => #<RSpec::Matchers::BuiltIn::EndWith:0x000055610e9c3fa0 @actual_does_not_have_ordered_elements=false, @expected="offset=200", @actual="/offset=100">}>})
```
:scream: 

There are a lot of argument matchers that are remixable this way, down to `{foo: {bar: {baz: anything}}}` as a way to check that "path" exists at all.

Wandering around the problem, I see several possible solutions:

1. Teach `Composable#surface_description_in` about argument matchers. Contra: as far as I can see, arg.matchers have no common base class, so I am not sure how to distinguish them; also, it increases coupling in a bad way;
2. API update: setup `#to_s` for matchers and argument matchers the way they will always be formatted "the right way" even in the simple string interpolation (I believe that should've been already considered, and there are really strong arguments against this solution).
3. Architectural: promote argument matchers to proper builtin matchers, usable on themselves;

Maybe the last one was also already discussed and rejected? But for me, it seems that unification can bring some value besides just "better descriptions".

PS: One more funny example:
```ruby
hash_including(include(end_with('meta'))).description
# => hash_including("include (end with \"meta\")"=>"anything")
include(include(end_with('meta'))).description
# => include (include (end with "meta"))
```
"Same, same, but different" :)

**Comment by myronmarston** [comment]
This is just a symptom of a deeper underlying problem: the fact that rspec-mocks argument matchers essentially duplicate the matchers included in rspec-expectations.  That's something we've long discussed reconciling in rspec/rspec-mocks#513.  We'd still like to see that happen, which will resolve this issue you've reported.  I'm going to close this issue.

Note that while the linked issue is a few years old (which might give the impression it's never going to get resolved), there are a few things coming down the pipeline that will make it _much_ easier for us to resolve it:

* We're planning to merge the repos into one (see rspec/rspec-core#2509), which will simplify the process
* I expect us to get started on RSpec 4 in the not-too-distant-future, which is the easiest time to fix this kind of issues as we don't have to worry about strictly preserving the behavior of the matchers as we reconcile them (as it's the first time in years we're allowing ourselves to make breaking changes!)

Thanks for bringing this to our attention!

**Comment by zverok** [comment]
@myronmarston Awesome, thanks! Just caught myself in a middle of writing the blog post with investigating some ideas about RSpec matchers (and adoring the composability), and it got to my attention that this separation was always a bit strange to me. I am really glad to see the way RSpec is evolving.

**Comment by zverok** [comment]
Here's the post, by the way: https://zverok.github.io/blog/2018-03-02-rspec-json.html
