### ISSUE TITLE
NoMethodError: undefined method `expect' for xxxxx:Class

### ISSUE THREAD

**Issue by rojabharathisunderneedi** [rspec/rspec-expectations#1058]
### Your environment
* Ruby version:ruby 2.4.0p0 
* rspec-expectations version: rspec-expectations (3.7.0)

### Steps to reproduce
**file:** Gemfile
gem 'capybara'
gem 'cucumber'
gem 'json', github: 'flori/json', branch: 'v1.8'
gem 'rake'
gem 'rspec'
gem 'selenium-webdriver'
gem 'settingslogic'
gem 'parallel_tests'
gem 'yard-cucumber'
gem 'rails_helper'
gem 'require_all'
gem 'rubocop'

**file:** sample_home.rb

**Comment by JonRowe** [comment]
Not enough information here to see what your issue is, but in general Github is not the place to ask for help, from the error message I suspect you're trying to use `expect` outside of an `it` block.

**Comment by rojabharathisunderneedi** [comment]
@JonRowe apologies for raising it in the wrong forum. But thank you for responding, i will include an it block and try it out.
