### ISSUE TITLE
Rspec 3.8 .change breaks object comparison (Stripe::Charge.list)

### ISSUE THREAD

**Issue by KelseyDH** [rspec/rspec-expectations#1070]
### Subject of the issue
I have a working rspec test for `Stripe::Charge.list` that works in rspec 3.7.1 but breaks in rspec 3.8.x

### Your environment
* Ruby version: 2.5.1
* rspec-expectations version: 3.8.1

### Steps to reproduce
The Stripe::Charge.list object id changes every time it is called, even if the data it gives back is the same.  Meaning a call like this now fails:

```
            it "does not create a charge in stripe" do
              expect{ true }.to_not change{ Stripe::Charge.list }
            end
```

### Expected behavior
The expected behaviour is that calls to two Stripe::Charge.list objects should consider not changed if the attributes within that object remain unchanged.

E.g.:

```
#<Stripe::ListObject:0x3feae3af47b4> JSON: {
  "object": "list",
  "data": [
    {"id":"test_ch_6","object":"charge","created":1366194027,"livemode":false,"paid":true,"amount":34800,"application_fee":null,"currency":"usd","destination":null,"fraud_details":{},"receipt_email":null,"receipt_number":null,"refunded":false,"shipping":{},"statement_descriptor":"Charge test_ch_6","status":"succeeded","source":{"object":"card","last4":"4242","type":"Visa","brand":"Visa","funding":"credit","exp_month":12,"exp_year":2013,"fingerprint":"3TQGpK9JoY1GgXPw","country":"US","name":"name","address_line1":null,"address_line2":null,"address_city":null,"address_state":null,"address_zip":null,"address_country":null,"cvc_check":null,"address_line1_check":null,"address_zip_check":null},"captured":true,"refunds":{"object":"list","total_count":0,"has_more":false,"url":"/v1/charges/test_ch_6/refunds","data":[]},"transfer":null,"balance_transaction":"test_txn_1","failure_message":null,"failure_code":null,"amount_refunded":0,"customer":{"id":"test_cus_3","email":"josh@davies.com","description":"an auto-generated stripe customer data mock","object":"customer","created":1372126710,"livemode":false,"delinquent":false,"discount":null,"account_balance":0,"currency":null,"sources":{"object":"list","total_count":1,"url":"/v1/customers/test_cus_3/sources","data":[{"id":"test_cc_2","object":"card","last4":"9191","type":"Visa","brand":"Visa","funding":"credit","exp_month":4,"exp_year":2018,"fingerprint":"wXWJT135mEK107G8","customer":"test_cus_3","country":"US","name":"Johnny App","address_line1":null,"address_line2":null,"address_city":null,"address_state":null,"address_zip":null,"address_country":null,"cvc_check":null,"address_line1_check":null,"address_zip_check":null,"tokenization_method":null,"number":null}]},"subscriptions":{"object":"list","total_count":0,"url":"/v1/customers/test_cus_3/subscriptions","data":[]},"default_source":"test_cc_2","metadata":{}},"invoice":null,"description":null,"dispute":null,"metadata":{}}
  ],
  "url": "/v1/hashs",
  "has_more": false
}
```

versus

```
#<Stripe::ListObject:0x3feae276ca0c> JSON: {
  "object": "list",
  "data": [
    {"id":"test_ch_6","object":"charge","created":1366194027,"livemode":false,"paid":true,"amount":34800,"application_fee":null,"currency":"usd","destination":null,"fraud_details":{},"receipt_email":null,"receipt_number":null,"refunded":false,"shipping":{},"statement_descriptor":"Charge test_ch_6","status":"succeeded","source":{"object":"card","last4":"4242","type":"Visa","brand":"Visa","funding":"credit","exp_month":12,"exp_year":2013,"fingerprint":"3TQGpK9JoY1GgXPw","country":"US","name":"name","address_line1":null,"address_line2":null,"address_city":null,"address_state":null,"address_zip":null,"address_country":null,"cvc_check":null,"address_line1_check":null,"address_zip_check":null},"captured":true,"refunds":{"object":"list","total_count":0,"has_more":false,"url":"/v1/charges/test_ch_6/refunds","data":[]},"transfer":null,"balance_transaction":"test_txn_1","failure_message":null,"failure_code":null,"amount_refunded":0,"customer":{"id":"test_cus_3","email":"josh@davies.com","description":"an auto-generated stripe customer data mock","object":"customer","created":1372126710,"livemode":false,"delinquent":false,"discount":null,"account_balance":0,"currency":null,"sources":{"object":"list","total_count":1,"url":"/v1/customers/test_cus_3/sources","data":[{"id":"test_cc_2","object":"card","last4":"9191","type":"Visa","brand":"Visa","funding":"credit","exp_month":4,"exp_year":2018,"fingerprint":"wXWJT135mEK107G8","customer":"test_cus_3","country":"US","name":"Johnny App","address_line1":null,"address_line2":null,"address_city":null,"address_state":null,"address_zip":null,"address_country":null,"cvc_check":null,"address_line1_check":null,"address_zip_check":null,"tokenization_method":null,"number":null}]},"subscriptions":{"object":"list","total_count":0,"url":"/v1/customers/test_cus_3/subscriptions","data":[]},"default_source":"test_cc_2","metadata":{}},"invoice":null,"description":null,"dispute":null,"metadata":{}}
  ],
  "url": "/v1/hashs",
  "has_more": false
}
```

### Actual behavior
Instead the actual behaviour is that the .change matcher on 3.8 now detects this new object ID as a change when in 3.7.x it didn't.

---

Is there a new syntax I should be using instead to change this test over?

**Comment by KelseyDH** [comment]
As a workaround for now I'm checking the `.count` to compare values between the two `Stripe::Charge.list["data"]`.  E.g.:
   
```
            it "does not create a charge in stripe" do
              expect{ invalid_request }.to_not change{ Stripe::Charge.list["data"].count }
            end
```

**Comment by myronmarston** [comment]
I believe the change causing this issue is #1034 which was implemented to address #1030.  It's worth reading those to fully understand what's going on, but the TL;DR is that the `change` matcher now uses `Object#hash` to detect if two objects are the same or not.  In the face of mutable data objects (which are themselves mutable at any level of nesting) it's the only way we could find to consistently detect changes or lack thereof.

That said, this technique depends upon `#hash` being defined properly.  Ruby semantics dictate that two equal objects must return the same `#hash` value.  (Ideally two unequal objects would return different `#hash` values but that's not strictly required).  It appears that `Stripe::ListObjects` does _not_ define `#hash` to respect these semantics.  (I'd argue that it's a bug that it does not).

If my hypothesis is correct, then I'd expect this spec to also fail:

``` ruby
set = Set.new([Stripe::Charge.list, Stripe::Charge.list])
expect(set.size).to eq 1
```

If you want to say that two consecutive calls to `Stripe::Charge.list` results in no change, I'd argue that the returned objects should de-duplicate when you put them in a set together, but if `#hash` is not defined properly they won't.  So in that sense, RSpec's change in behavior here simply reflects the reality of how `Stripe::ListObject` are defined to work even if it's not how you or I would want them to work.

So, I think the best fix here would be to get a change into the stripe gem so that they do define `#hash` on these objects properly.  Barring that, you could convert the `Strip::ListObject` to an array (would `.to_a` work?) and do `expect { invalid_request }.not_to change { Stripe::Charge.list.to_a }` or something similar.

Sorry that our change broke your spec!  Hopefully that all makes sense.

**Comment by myronmarston** [comment]
FWIW, we do document the reliance on `#hash` for the `change` matcher:

http://rspec.info/documentation/3.8/rspec-expectations/RSpec/Matchers.html#change-instance_method

> Evaluates receiver.message or block before and after it evaluates the block passed to expect. If the value is the same object, its before/after hash value is used to see if it has changed. Therefore, your object needs to properly implement hash to work correctly with this matcher.

**Comment by KelseyDH** [comment]
Thanks for the response.  I will contact the Stripe gem maintainers to let them know about this issue.

**Comment by Kukunin** [comment]
Happens to me with associations:

```ruby
      it 'does not affect it' do
        expect { my_action }.not_to(change { user.reload.articles })
      end
```

`expected 'user.reload.articles' not to have changed, but did change from #<ActiveRecord::Associations::CollectionProxy []> to #<ActiveRecord::Associations::CollectionProxy []>`

**Comment by JonRowe** [comment]
@Kukunin I'm of the belief thats a known issue, similar to this it's because they aren't actually the same object, there are some versions of Rails that cache the proxy, I'm not sure what an older version like 4.2 does. A work around is to tag on `to_a` on the end

**Comment by JonRowe** [comment]
@Kukunin `master` contains a fix which should help you, if you'd care to try it out.
