### ISSUE TITLE
Using be_instance_of/be_kind_of matchers with a class inherited from BasicObject directly fails

### ISSUE THREAD

**Issue by taichi-ishitani** [rspec/rspec-expectations#1105]
### Subject of the issue

Using `be_instance_of`/`be_kind_of` matchers with a class inherited from BasicObject directly fails due to `NoMethodError`.

### Your environment
* ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
* rspec-expectations 3.8.2

### Steps to reproduce

Run the sample test below.

```ruby
RSpec.describe 'be_kind_of/be_instance_of matcher' do
  class Foo < BasicObject
  end

  class Bar < Foo
  end

  let(:foo) { Foo.new }
  
  let(:bar) { Bar.new }

  describe 'be_kind_of matcher' do
    it 'can be used with a class inherited from BasicObject directly' do
      expect(bar).to be_kind_of Foo
    end
  end

  describe 'be_instance_of matcher' do
    it 'can be used with a class inherited from BasicObject directly' do
      expect(foo).to be_instance_of Foo
    end
  end
end
```

[foo_spec.zip](https://github.com/rspec/rspec-expectations/files/2966885/foo_spec.zip)

### Expected behavior

Above two examples should pass.

### Actual behavior

Above two examples failed due to `NoMethodError`.

```
$ rspec foo_spec.rb
FF

Failures:

  1) be_kind_of/be_instance_of matcher be_kind_of matcher can be used with a class inherited from BasicObject directly
     Failure/Error: expect(bar).to be_kind_of Foo

     NoMethodError:
       undefined method `kind_of?' for #<Bar:0x000000000391f390>
     # ./foo_spec.rb:14:in `block (3 levels) in <top (required)>'

  2) be_kind_of/be_instance_of matcher be_instance_of matcher can be used with a class inherited from BasicObject directly
     Failure/Error: expect(foo).to be_instance_of Foo

     NoMethodError:
       undefined method `instance_of?' for #<Foo:0x00000000038fe438>
     # ./foo_spec.rb:20:in `block (3 levels) in <top (required)>'

Finished in 0.01764 seconds (files took 0.3834 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./foo_spec.rb:13 # be_kind_of/be_instance_of matcher be_kind_of matcher can be used with a class inherited from BasicObject directly
rspec ./foo_spec.rb:19 # be_kind_of/be_instance_of matcher be_instance_of matcher can be used with a class inherited from BasicObject directly
```

**Comment by JonRowe** [comment]
`BasicObject` doesn't support `instance_of` or `kind_of` so our matchers don't work either. Personally I don't feel like this is a bug as we reflect on the underlying Ruby semantics, but I'd accept a PR warning of this scenario rather than raising a `NoMethodError`

**Comment by taichi-ishitani** [comment]
Hi @JonRowe ,
Thank you for your comment and I understand this is not bug.

> a PR warning of this scenario rather than raising a NoMethodError

 I will consider how to implement it.
However, I think it is difficult to check whether or not the actual object can respond to `#instance_of?` or `#kind_of?` methods because `#respond_to?` method is defined in Object class but not BasicObject class.

**Comment by mikegee** [comment]
@taichi-ishitani consider using `rescue NoMethodError` in the implementation of `be_kind_of` and `be_instance_of`

**Comment by taichi-ishitani** [comment]
@mikegee 
Thank you for your advice !

@JonRowe 
Which file can I refer to implement the feature?

**Comment by JonRowe** [comment]
So we have a way of using `Kernel` methods with `BasicObject` we could implement a fall back here with this.

In rspec-support we using this trick to get method handles, see:
https://github.com/rspec/rspec-support/blob/master/lib/rspec/support.rb#46

Essentially its:
`Kernel.instance_method(:method_name).bind(object).call(args)`

We could use this strategy to `rescue NoMethodError` and then call the kernel implementation to check `be_kind_of` and `be_instance_of`. Those would be defined in `lib/rspec/matchers/built_in/be_kind_of.rb` and `lib/rspec/matchers/built_in/be_instance_of.rb` in this project.

**Comment by taichi-ishitani** [comment]
I open a new PR(#1107) for this issue.
I added warning message as a special failure message.
