### ISSUE TITLE
Extend behavior of be_within to optionally correct DST

### ISSUE THREAD

**Issue by Startouf** [rspec/rspec-expectations#1108]
### Subject of the issue
When testing operations that involve time, it can be useful to have a modified version of the matcher `be_within` that does/does not correct DST changes.

### Your environment
* Ruby version: 2.3
* rspec-expectations version: 3.6.0

### Example use case
We are using MongoDB aggregation to perform operation on dates. Currently the framework does not handle well time zones in aggregations, and business-wize we don't really care about DST.

What happens in Ruby

```ruby
project.starts_at                # => Mon, 01 Apr 2019 15:35:52 CEST +02:00
project.starts_at - 1.week     # => Mon, 25 Mar 2019 15:35:52 CET +01:00
```

What happens in MongoDB Aggregation

```javascript
{ '$project': {
  safety_margin_starts_at: {
    '$subtract': ['$starts_at', safety_margin_duration]
  },
}
# Produces the equivalent of 
# => 2019-03-25 13:35:52.357000000 +0000 which 
#  is actually  => Mon, 25 Mar 2019 15:35:52 CET +02:00 (
#  and not      => Mon, 25 Mar 2019 15:35:52 CET +01:00
```

WHen writing a spec, 

```ruby
describe '#safety_margin_starts_at' do
  subject { aggregated_participation.safety_margin_starts_at }

  before { participation }

  it { is_expected.to be_within(0.1).of(participation.safety_margin_starts_at) }
end
```

It therefore fails with

```
Failure/Error: participation
       expected 2019-03-25 13:35:52.357000000 +0000 to be within 0.1 of 2019-03-25 15:35:52 +0100
```

### What we could do 

Implement a chainable option to the [be_within matcher](https://github.com/rspec/rspec-expectations/blob/848fcb426cca1977b75909d0cb8a10f03a104b36/lib/rspec/matchers/built_in/be_within.rb) (whose name could be `with_dst_correction_from(date)`) that would compare the expected VS actual date, see if they correspond to different DST activation, and fix the expectation by adding +1 or substracting 1.hour. In the example above it would become

`it { is_expected.to be_within(0.1).of(project.safety_margin_starts_at).with_dst_correction_from(project.starts_at) }`

THe implementation of `with_dst_correction_from(project.starts_at)` would be something like

```ruby
def with_dst_correction_from(date)
  @dst_adjust_date = date
end

def matches?(actual)
  @actual = actual
  raise needs_expected unless defined? @expected
  numeric? && (@actual - @expected + dst_correction).abs <= @tolerance # Added `+ dst_correction` here
end

def dst_correction
  return 0 unless @dst_adjust_date.present?

  if @actual.dst? && !@dst_adjust_date.dst?
    1.hour
  elsif !@actual.dst? && @dst_adjust_date.dst? 
    - 1.hour
  else
    0
  end
end
```

 
Note : I have also opened a StackOverflow here : https://stackoverflow.com/questions/55457104/mongodb-substract-a-date-with-a-duration-and-take-into-account-dst-changes-for

**Comment by JonRowe** [comment]
:wave: The `be_within` matcher, whilst it works with dates and times, is a numeric matcher, when used with dates / times it compares the numeric posix time. So in your case, the matcher is correctly failing as your data is more than 0.1 out.

It's thus rather nonsensical to add this to a matcher whose primary usage would have to error that this was not a supported feature.

I would propose that you create a custom matcher to handle this edgecase in your framework. This could be internal to your suite or be a community gem providing a new matcher than uses the `be_within` under the hood.
