### ISSUE TITLE
#1107 Somehow breaks my specs

### ISSUE THREAD

**Issue by FunkyloverOne** [rspec/rspec-expectations#1111]
### Subject of the issue
I'm getting the following error on perfectly normal object:
```
ArgumentError:
       The be_a_kind_of matcher requires that the actual object responds to either #kind_of? or #is_a? methods but it responds to neigher of two methods.
```

### Environment
* Ruby version: 2.5.1
* rspec-expectations version: 3.8.3

### Steps to reproduce
I do not really know yet, I will investigate more on it and provide details.

### Actual behavior
```ruby
value.respond_to?(:is_a?)
#=> true
::Kernel.instance_method(:respond_to?).bind(value).call(:is_a?)
#=> false
```

P.S an error message has a typo - `neigher`.

**Comment by JonRowe** [comment]
Hm. Interesting. Do you feel like patching this? We could rescue the `NoMethodError` instead which would circumvent the need to rely on a check

**Comment by dem** [comment]
The same issue for me, which not exists on rspec-expectations version: 3.8.2

**Comment by FunkyloverOne** [comment]
@JonRowe sounds good to me! I will make a PR.

**Comment by p-mongo** [comment]
#1107 also broke Mongoid test suite, it looks like the change was meant to be backwards compatible?
