### ISSUE TITLE
Spelling/grammar in #1107 message

### ISSUE THREAD

**Issue by p-mongo** [rspec/rspec-expectations#1114]
### Subject of the issue

#1107 added the following message:

> ArgumentError: The be_a_kind_of matcher requires that the actual object responds to either #kind_of? or #is_a? methods but it responds to neigher of two methods.

I believe there should be "the" in front of "two", so that the message should read:

> ArgumentError: The be_a_kind_of matcher requires that the actual object responds to either #kind_of? or #is_a? methods but it responds to neigher of the two methods.

Alternatively, "of two methods" can be removed entirely if conciseness is desired, so that the message reads:

> ArgumentError: The be_a_kind_of matcher requires that the actual object responds to either #kind_of? or #is_a? methods but it responds to neigher.

Finally, the correct spelling of "neigher" is "neither".

### Your environment
* Ruby version: 2.6
* rspec-expectations version: 3.8.3

**Comment by JonRowe** [comment]
Fixed by #1112
