### ISSUE TITLE
Testing code with `at_exit` conflicts with `raise_error`

### ISSUE THREAD

**Issue by edisonywh** [rspec/rspec-expectations#1117]
Hey guys! I currently have a class like this:

```ruby
module Gem
  def custom_method
    at_exit do
      # code_logic
      raise StandardError
    end
  end
end
```

The reason I am wrapping my code inside `at_exit` is because I want to run the execution of the code AFTER my `base` class has finished defining the methods. For example:

```ruby
class Foo
  extend Gem
  custom_method
  def method_one; end
end
```

I want to access `method_one` from inside my gem, I have two ways to do it:
1) Put my `custom_method` all the way at the bottom of the file
2) Wrap my `custom_method` around an `END` block or an `at_exit` block, both of which will ensure that my `custom_method` runs after the file that `extended` the file.

I've decided to go with the second option because I do not want to put the method call at the end of the file.

It all works fine when I test it manually, however, the issue is as follow when I try to test it with rspec.

I want to test my method like so:

```ruby
expect do
  Foo = Class.new do
    extend Gem
    custom_method
    def method_one; end
  end
end.to raise_error StandardError
```

But this won't work, rspec will think that there's no error, I presume this is because my `at_exit` runs after the rspec `raise_error`, which means the error is raised after the expectation.

How can I make my test green? Appreciate any pointers!

**Comment by edisonywh** [comment]
For a more concrete example, I just published the gem in question, so you can dig into the source code too.

https://github.com/edisonywh/behaves

**Comment by JonRowe** [comment]
:wave: This is a tough one, your test is working correctly, because `at_exit` hooks are installed at... well.. exit, by which time your test suite has already failed. The way to test this is, probably, to assert that `at_exit` is received with a stub and then check the block raises StandardError when invoked.

As far as I know there is no way to intercept the blocks and check them, and in any case would cause RSpec to exit uncleanly.

**Comment by edisonywh** [comment]
Cool, thanks for confirming what I suspected!

With that, I think I'm going to break the rules of `no testing private method`, as I don't think it should be a hard rule but rather a guideline, and one that's reasonable to break in my case.

My fix is over at https://github.com/edisonywh/behaves/pull/16 along with my rationale, if someone is interested.

Thanks for taking the time to answer my question, Jon!

**Comment by JonRowe** [comment]
You could also test it by shelling out and running your code that way, which is how we test some parts of RSpec.

**Comment by edisonywh** [comment]
I don't understand what you mean by `shelling out`, could you explain what's that? Thanks!

**Comment by JonRowe** [comment]
Running your code as a seperate process on the command line and testing the resulting output.

**Comment by JonRowe** [comment]
You could also experiment with `fork` a quick check says at_exit is run, but not rescuable but again you might be able to assert on the output
