### ISSUE TITLE
Add support for notify_expectation_failures option to match_when_negated

### ISSUE THREAD

**Issue by mojavelinux** [rspec/rspec-expectations#1124]
Unlike match, the match_when_negated function does not support the notify_expectation_failures option. As a result, any expectation inside the failure is reported as a failure of the outer expectation instead of providing the detail of the expectation that actually failed.

* Ruby version: 2.6.3
* rspec-expectations version: 3.8.4

### Steps to reproduce

Cannot define a negated match with the option notify_expectation_failures.

For example:

```rb
RSpec::Matchers.define :log_message do |expected = {}|
  ...

  match_when_negated notify_expectation_failures: true do |actual|
    with_memory_logger expected[:using_log_level] do |logger|
      actual.call
      logger ? logger.empty? : true
    end
  end

  supports_block_expectations
end
```

### Expected behavior

The match_when_negated function should accept an options Hash and should report expectation failures in the block if the notify_expectations_failures is true.

### Actual behavior

The match_when_negated function does not accept options (and thus there is no way to set notify_expectation_failures).

**Comment by JonRowe** [comment]
I'm open to supporting this, see https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/dsl.rb for the implementation, copying the existing should suffice (with a few tests of course)

**Comment by JonRowe** [comment]
We've got support for this in master, not sure when it'll be released
