### ISSUE TITLE
Error message when passing block to `and_return` could be improved?

### ISSUE THREAD

**Issue by Confusion** [rspec/rspec-expectations#1129]
### Error message when passing block to `and_return` could be improved?

This is not a bug report, but a suggestion for improvement.

Given the following code and spec
```
module M                                                                                                                                                                     
  def self.f(x)                                                                 
    x                                                                           
  end                                                                           
end                                                                             
                                                                                
RSpec.describe 'M.f' do                                                              
  it 'returns 0 when stubbed' do                                              
    expect(M).to receive(:f).and_return do                                  
      0                                                                       
    end                                                                       
    expect(M.f(5)).to eq 0                                                  
  end                                                                         
end   
```
we expected the stubbed `:f` method to return 0. Instead we got the error message
```
ArgumentError:
       wrong number of arguments (given 0, expected 1+)
# ./reproduction_spec.rb:9:in `block (2 levels) in <top (required)>'
```
which is correct. However, we spent some time figuring out that it was the `and_return` itself that was failing, while setting up the spec, instead of something in our code while the spec was being executed (of course both the spec and code involved were much more complex; if it would have been as simple as this example, it would have been obvious). After we figured that out it was of course clear that we should pass the block directly to `receive` and dispense with the `and_return` entirely. 

Since we spent a relatively large amount of time tracking this down, I figured it could be worthwhile to amend `and_return` to give a helpful message when a block is passed to it, to save others that time.

Would it be feasible and acceptable to proactively tell the user what they are doing wrong when they call `and_return` without a parameter and with a block? I'm willing to submit a PR if it is.

### Your environment
* Ruby version: 2.5.3
* rspec-expectations version: 3.8.4

### Steps to reproduce
Save the code given above to a file and execute it using `rspec`.

### Suggested behavior
Actual behavior is correct. Suggested behavior is to

**Comment by pirj** [comment]
I have some traces in memory that it was possible to use `and_return` with a block, however, I can't it in [the docs](https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/configuring-responses/returning-a-value).

You can use `and_wrap_original` for that purpose:
```ruby
    allow(M).to receive(:foo).and_wrap_original { |x| 0 }
```

There's a mismatch of `f` and `foo` in the example.

**Comment by JonRowe** [comment]
Using `and_return` with a block is not actually using `and_return` but instead is using block responses, see https://relishapp.com/rspec/rspec-mocks/v/3-8/docs/configuring-responses/block-implementation.

This is an issue with Ruby semantics, a block with no arguments raises when it is called with arguments. 

I'd happily accept a PR that caught this error when invoking the implementation and elaborated, but the solution is a little tricky as I don't really want to proactively check arguments (and slow down the result) but it must also not hide false positives... Something along the lines of (psuedo coding here)

```
begin
  implementation.call(*args)
rescue ArgumentError => error
  raise error unless given_argument_arity != expected_argument_arity
  raise MoreHelpfulError
end
```

**Comment by Confusion** [comment]
It doesn't raise the error when invoking the implementation, but already when setting up the spec. The internal RSpec stack trace looks like this:
```
["rspec-mocks/lib/rspec/mocks/message_expectation.rb:71:in `and_return'",
 "rspec-mocks/lib/rspec/mocks/matchers/expectation_customization.rb:15:in `playback_onto'",
 "rspec-mocks/lib/rspec/mocks/matchers/receive.rb:101:in `block in setup_method_substitute'",
 "rspec-mocks/lib/rspec/mocks/matchers/receive.rb:100:in `each'",
 "rspec-mocks/lib/rspec/mocks/matchers/receive.rb:100:in `setup_method_substitute'",
 "rspec-mocks/lib/rspec/mocks/matchers/receive.rb:86:in `setup_mock_proxy_method_substitute'",
 "rspec-mocks/lib/rspec/mocks/matchers/receive.rb:43:in `setup_allowance'",
 "rspec-mocks/lib/rspec/mocks/targets.rb:46:in `define_matcher'",
 "rspec-mocks/lib/rspec/mocks/targets.rb:10:in `block in delegate_to'",
 "rspec-mocks/spec/rspec/mocks/and_return_spec.rb:23:in `block (4 levels) in <module:Mocks>'",
 "rspec-expectations/lib/rspec/matchers/built_in/raise_error.rb:52:in `matches?'",
 "rspec-expectations/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'",
 "rspec-expectations/lib/rspec/expectations/handler.rb:27:in `with_matcher'",
 "rspec-expectations/lib/rspec/expectations/handler.rb:48:in `handle_matcher'",
 "rspec-expectations/lib/rspec/expectations/expectation_target.rb:65:in `to'",
 "rspec-expectations/lib/rspec/expectations/expectation_target.rb:101:in `to'",
 "rspec-mocks/spec/rspec/mocks/and_return_spec.rb:23:in `block (3 levels) in <module:Mocks>'"
```
The `and_return` method itself is never called: the attempt to call it is what fails, because it requires at least one argument. 

I now realize that what would have helped was if RSpec had decided to show the internal stack trace for this error. The elision of the internal trace makes it seem like it's the block invocation that has to be failing, as that is where the error seems to be reported.

So on closer inspection it can't be solved by amending `and_return` (or wherever the block invocation happens), but requires choosing to expose the internal RSpec stack trace for this case. Are there similar cases for which this is done? Is this something you would consider?

**Comment by pirj** [comment]
As docs above mention, `and_return` is not necessary, and it seems that it doesn't work.

I see the following possible improvements:
 - `and_return` expects an argument, not a block. Make it possible to pass a block to `and_return` similarly to `with`/`once`/`ordered` etc
 - when stubbing a method that accepts an argument using block response implementation that accepts no arguments, a cryptic `ArgumentError` is raised. Add a proper error message explaining method signature mismatch with block implementation.
 - `and_return` expects an argument, not a block. However, when a block is passed to it, a cryptic error message is raised. Add a proper error message explaining that `and_return` does not accept blocks.

Which problem you'd like to address specifically (1 & 3 are mutually exclusive)?

**Comment by JonRowe** [comment]
My apologies, I didn't look at this closely enough first time around, the use of the block was disguising the issue, the problem with your spec is `and_return` takes an argument, you are doing `and_return()` when it need to be `and_return(something)`. 

Thus RSpec is giving you a correct `ArgumentError` for the missing argument. Add an argument to `and_return` or remove it to use the block.

**Comment by Confusion** [comment]
@pirj I think the third option would be most explicit.

@JonRowe Yes, the error is entirely correct. However, since it is not attributed to `and_return` in the stack trace, the source of the problem is not obvious. Your initial response kind of demonstrates that even ;). So perhaps an improvement is possible that would keep others from being puzzled for longer than necessary.

**Comment by JonRowe** [comment]
>Yes, the error is entirely correct. However, since it is not attributed to and_return in the stack trace, the source of the problem is not obvious. 

It does for me, it indicates the line of the spec where `and_return` is used.

**Comment by Confusion** [comment]
Yes, and note that that's different from other stack traces with this kind of error: those would include an extra line, the line where `and_return` itself is defined, in the stack trace.

**Comment by JonRowe** [comment]
Given file:
```ruby
RSpec.describe do 
  it do
    expect(Object).to receive(:make).and_return do
      0
    end
    expect(Object.make).to eq 0
  end
end

```
I get:
```
ArgumentError:
       wrong number of arguments (given 0, expected 1+)
     # ./spec/bad_spec.rb:3:in `block (2 levels) in <top (required)>'
```

**Comment by JonRowe** [comment]
As the argument error is happening on line 3 of bad_spec thats what I'd expect

**Comment by Confusion** [comment]
It's the correct error, but a weird stack trace for that error. You indeed need to pass `--backtrace` to get the line that actually fails: the line where `and_return` is defined, which would normally always be present. Cf. the example below. Would it be possible/helpful to not adjust a stack trace when an error originates from a line of RSpec code? 

```
def f(x)
end
f
```
```
Traceback (most recent call last):
	1: from /tmp/example.rb:3:in `<main>'
/tmp/example.rb:1:in `f': wrong number of arguments (given 0, expected 1) (ArgumentError)
```

**Comment by JonRowe** [comment]
> You indeed need to pass --backtrace to get the line that actually fails: the line where and_return is defined, which would normally always be present. Cf. the example below. 

No you pass `--backtrace` to get the definition of the method in the stack trace, the line thats actually failing is the line in your spec. This is one of the reasons why it's hidden by default, its to highlight the cause of the error rather than the location of the method definition.

> Would it be possible/helpful to not adjust a stack trace when an error originates from a line of RSpec code?

Is it helpful? 99% of the time no, as above, we're highlighting the cause of the error rather than the definition of the method. You can always turn on full backtrace mode all the time if you wish.

**Comment by Confusion** [comment]
Note beforehand: I'm fine with the outcome of this issue, I'm just trying to make sure you understand the problem you are closing, which is not "we don't know how Ruby works" or "we can't interpret stack traces".

MRI started including the line with the *callee* because it makes it clear which one of multiple function calls on the same line is the one causing a problem. It was not quickly obvious to us that `and_return` was the cause of the failure, because the stack trace as it is suggests the *callee* is on the line shown at the top of the stack trace, not the *caller*. And the block is the top suspect for the *callee*. Especially if you are under the impression `and_return` works the same as `receive` and thus "can't be the problem".

As long as we agree that there is a difference between the stack trace shown for this situation and how Ruby 'normally' shows things and that this can make it harder to figure out where a problem comes from, then it makes complete sense to say "this doesn't happen often, not worth any effort". But so far I have the impression you believe the stack trace is entirely normal and doesn't deviate in any way from what one might expect.

**Comment by pirj** [comment]
I believe @Confusion means that [this message](https://github.com/rspec/rspec-mocks/blob/a7409d3/lib/rspec/mocks/message_expectation.rb#L78) should appear in the output giving clear indication of what went wrong exactly:
```ruby
        if block_given?
          raise ArgumentError, "Implementation blocks aren't supported with `and_return`"
        end
```
However, I suppose it will only appear in the following case:
```
allow(Foo).to receive(:bar).and_return(:baz) { 111 }
```
but not when no argument is passed to `and_return`.

I couldn't find a spec that would cover the behaviour when this error is raised though.

Confirmation:
```ruby
    RSpec.describe do
      C = Class.new { def a; end }
      it 'with argument passed to `and_return`' do
        expect {
          allow(C).to receive(:a).and_return(:baz) { 111 }
        }.to raise_error(ArgumentError, "Implementation blocks aren't supported with `and_return`")
      end
      it 'without any arguments passed to `and_return`' do
        expect {
          allow(C).to receive(:a).and_return { 111 }
        }.to raise_error(ArgumentError, /wrong number of arguments/)
      end
    end
```
```
  without any arguments passed to `and_return`
  with argument passed to `and_return`

2 examples, 0 failures
```

I suggest to slightly change the implementation of `and_return` in a way:
```diff
-      def and_return(first_value, *values)
+      def and_return(*values)
```
also removing `values.unshift(first_value)`, and pushing the logic that would trigger `wrong number of arguments` to `AndReturnImplementation`.

WDYT?

**Comment by JonRowe** [comment]
No. We specifically removed the ability to use `and_return { ... }` in 3.0.0, there is an argument error raised because you're missing an argument, it will raise an `ArgumentError` if you give a block both are unsupported cases.

**Comment by pirj** [comment]
I understand. What I mean is that if both `and_return() { }` and `and_return(...) { }` would result in the same error message, that would lead the users to a conclusion that it does not support blocks, while the current error message for `and_return() { }` is slightly confusing?

**Comment by JonRowe** [comment]
The current error message is for `and_return()` the block is not part of it, and its a standard ruby error message, we have generally held to the principle of letting Ruby error when its a such a standard situation, we could work around it with some defensive programming but thats not a policy we've believed in either.

**Comment by pirj** [comment]
This makes total sense to me now.

**Comment by rangerscience** [comment]
FYI:
Came across this issue trying to figure out how to have `and_return` execute a block to determine the return value. Answer is to use `and_invoke` instead:

```
expect(M).to receive(:f).and_invoke(-> { rand(10) })
```

(Couldn't find it in the docs - well, rather, couldn't find it in the docs that Google pointed me to _given_ that the Relish doc app is throwing an Application Error - anyway, wanted this here in case someone else came looking for the same)
