### ISSUE TITLE
Duplicate matcher does not create a warning

### ISSUE THREAD

**Issue by bsvin33t** [rspec/rspec-expectations#1135]
### Subject of the issue
When a duplicate matcher is introduced, a warning should be produced by RSpec.

### Your environment
* Ruby version: 2.5.3
* rspec-expectations version: 3.8.4

### Steps to reproduce
```ruby
RSpec::Matchers::DSL::Matcher.new(:duplicate_matcher, {}, self, nil)
RSpec::Matchers::DSL::Matcher.new(:duplicate_matcher, {}, self, nil)
```

### Expected behavior
It should create a warning

### Actual behavior
There is no warning for the user about the duplicate matcher.

**Comment by bsvin33t** [comment]
I have created a PR that does just that. But, I'm afraid that the specs everywhere are breaking because RSpec raises an error when creating a warning. Is there an alternative method that I can use that will allow RSpec to gracefully inform the user about this.

**Comment by bsvin33t** [comment]
I don't think using `config.raise_on_warning = false` would be a good idea as it would suppress all warnings.

**Comment by JonRowe** [comment]
Closing in preference to discussion on #1136 itself.
