### ISSUE TITLE
Bug: Rspec Compatibility with colour based gems for parsing

### ISSUE THREAD

**Issue by luke-hill** [rspec/rspec-expectations#1141]
### Subject of the issue
Cannot run an rspec test with a colour based output string (Given in code format)

### Your environment
* Ruby version: 2.6.3
* rspec-expectations version: 3.9.0

### Steps to reproduce
# inside an rspec test

```
      it 'informs the user that the potion dropped' do
        log_lines =
["# log started", "irrelevant:INFO - \e[0;33;49mDrop potion message\e[0m"]

        expect(log_lines).to include(/Drop potion message/) # passes
        expect(log_lines).to include(/\e[0;33;49mDrop potion message\e[0m/) #crashes
        expect(log_lines).to include(/#{'Drop potion message'.yellow}/) #crashes
      end
```
### Expected behavior
Both lines should pass

### Actual behavior
2nd line crashes with: 
```
An error occurred while loading ./spec/mud/combat/item_drops_spec.rb.
Failure/Error: __send__(method, file)

SyntaxError:
  /home/luke/Code/mud/spec/mud/combat/item_drops_spec.rb:64: premature end of char-class: /\e[0;33;49mDrop potion message\e[0m/
```

This may not be an Rspec issue, but the line of code that fails is inside rspec configuration

```
# configuration.rb:2075
def load_file_handling_errors(method, file)
        __send__(method, file)
      rescue LoadError => ex
        relative_file = Metadata.relative_path(file)
        suggestions = DidYouMean.new(relative_file).call
        reporter.notify_non_example_exception(ex, "An error occurred while loading #{relative_file}.#{suggestions}")
        RSpec.world.wants_to_quit = true
      rescue Support::AllExceptionsExceptOnesWeMustNotRescue => ex
        relative_file = Metadata.relative_path(file)
        reporter.notify_non_example_exception(ex, "An error occurred while loading #{relative_file}.")
        RSpec.world.wants_to_quit = true
      end
```

**Comment by pirj** [comment]
You may reproduce this witout RSpec involved:
```ruby
> item = "irrelevant:INFO - \e[0;33;49mDrop potion message\e[0m"
> item.match? /#{item}/
RegexpError: premature end of char-class: /irrelevant:INFO - \x1B[0;33;49mDrop potion message\x1B[0m/
```

The problem is there's a special regexp symbol, `[`, and you have to escape it.

```ruby
item.match /\e\[0;33;49mDrop potion message\e\[0m/
=> #<MatchData "\e[0;33;49mDrop potion message\e[0m">
```
Notice the `[0;33` vs `\[0;33` difference.
I can't give any advice of wheather there is some magic method that would convert a string to a regexp, but if it's possible, try to match on a full string:

```ruby
expect(log_lines).to include(Drop potion message'.yellow)
```

**Comment by luke-hill** [comment]
This is likely an error in the relevant color gems repositories then. Sorry for the mistake :)

**Comment by JonRowe** [comment]
> This is likely an error in the relevant color gems repositories then. Sorry for the mistake :)

Assuming your spec is similar to what you used here, it's not a mistake in the gem repositories, just in the regular expression. A regular expression uses `[` and `]` to denote a selection of patterns. Terminal output uses `[` as part of its control codes. You just need to escape `[` as `\[` when trying to use a regular expression to match them.

**Comment by luke-hill** [comment]
I originally used `"this string".yellow` which failed. So there needs to be some form of `regex_safe` option I would wager?

**Comment by JonRowe** [comment]
Ah I see, you need `/#{Regexp.escape "this string".yellow}/` or just try using the string as is. e.g. `include("this string".yellow)`
