### ISSUE TITLE
Unintentional passing of `nil` to `raise_error`

### ISSUE THREAD

**Issue by pirj** [rspec/rspec-expectations#1142]
### Subject of the issue

We issue a warning when `raise_error` is called with no exception class and no block:
> Instead consider providing a specific error class or message

However, it's hard to imagine why would someone explicitly pass a `nil` as an exception class.
I've stumbled across a situation when this is done unitentionally:

```ruby
let(:status_code_exception_mapping) { {404: SomethingNotFound} }
let(:expected_exception_class) do
  status_code_exception_mapping[status_code]
end
let(:status_code) { 502 }

it "raises a specific error" do
  expect { process! }
    .to raise_error(expected_exception_class)
end
```

In this example, a `raise_error(nil)` was called, even though it wasn't at all obvious since `status_code_exception_mapping` was buried in the code.
What made it even worse is that there was an exception of a different type raised, and the only way to notice that was the warning about possible exception mismatch.

This was hiding a real exception that was way different from anything expected.

### Your environment
* Ruby version: 2.5.1
* rspec-expectations version: 3.6.0 (however, glancing over the latest code it seems that the behaviour has not changed)

### Steps to reproduce

```
# spec/a_spec.rb
RSpec.describe do
  it "raises a specific error" do
    expect { process! }
      .to raise_error(nil)
  end
end
```

### Expected behavior

Error message resulting in spec failure, something like:
> `nil` is not a valid value for an expected exception.

I would expect it to be raised disregarding `on_potential_false_positives` setting.

### Actual behavior

```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call.
Actual error raised was #<TypeError: no implicit conversion of Hash into String>.
Instead consider providing a specific error class or message.
This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`.
Called from ...
```

### Proposed solution

Use
```ruby
      UndefinedValue = Module.new
```
to make a distinction between `raise_error()` and `raise_error(nil)`.

### Open questions

Is this a breaking change? Should this target 4.0?

**Comment by JonRowe** [comment]
I agree that this could use improvement, I would suggest for the current version we emit an explicit warning about `nil`, and in future we could make it error.
