### ISSUE TITLE
Chaining .change with block and .and not properly looking at expected value

### ISSUE THREAD

**Issue by tenpaiyomi** [rspec/rspec-expectations#1153]
### Subject of the issue
I have a test that performs an action and then checks 3 objects/attributes for changed values.  However, when looking at the logged output, it is clear that the last expectation in the chain is getting the value of the first expectation after the first `.and change {...}`, and seemingly ignoring the others.

### Your environment
* Ruby version: 2.6.3
* rspec-expectations version: 3.9.0

### Steps to reproduce

The code in question here:

```
          expect { user.activate! }.to change { ActionMailer::Base.deliveries.count }.by(1)
                                   .and change { user.active? }.to be_truthy
                                   .and change { user.updated_at }.to be_within(1.minute).of(Time.current)
                                   .and change { user.expires_at }.to be_within(1.minute).of(Time.current + 14.days)
```

### Expected behavior
For the test to pass.  If I break out the code into the following:

```
          user.activate!
          expect { user.activate! }.to change { ActionMailer::Base.deliveries.count }.by(1)

          expect(user.active?).to be_truthy
          expect(user.updated_at).to be_within(1.minute).of(Time.current)
          expect(user.expires_at).to be_within(1.minute).of(Time.current + 14.days)
```

then everything passes without issue (the check for `user.updated_at` was simply to see if the error was only checking against the previous `.and change {...}` value in the chain, or always against the first `.and change {...}` value)

### Actual behavior

Instead, it compared (at least) the last `.and change {...}` against the first `.and change {...}` value, and reports only a single error, essentially treating the `.and` chain all as a single expectation instead of 3 unique expectations.

```
       expect { user.activate! }.to change { ActionMailer::Base.deliveries.count }.by(1)
                                .and change { user.active? }.to be_truthy
                                .and change { user.updated_at }.to be_within(1.minute).of(Time.current)
                                .and change { user.expires_at }.to be_within(1.minute).of(Time.current + 14.days)

       expected `user.active?` to have changed to be truthy and change `user.updated_at` to be within 60 of 2020-01-02 20:25:40 UTC and change `user.expires_at` to be within 60 of 2020-01-16 20:25:40 UTC, but did not change

```

**Comment by pirj** [comment]
Does it work as expected if you change it this way:
```diff
- .and change { user.active? }.to be_truthy
+ .and change { user.active? }.to(be_truthy)
```

**Comment by tenpaiyomi** [comment]
> 
> 
> Does it work as expected if you change it this way:
> 
> ```diff
> - .and change { user.active? }.to be_truthy
> + .and change { user.active? }.to(be_truthy)
> ```

Unfortunately not.  In this case it seems like the expectation now becomes isolated down to explicitly what is within the `.and change {...}` block

```
       expect { user.activate! }.to change { ActionMailer::Base.deliveries.count }.by(1)
                                .and change { user.active? }.to(be_truthy)
                                .and change { user.updated_at }.to(be_within(1.minute).of(Time.current))
                                .and change { user.expires_at }.to(be_within(1.minute).of(Time.current + 14.days))

       expected `user.active?` to have changed to be truthy, but did not change
```

**Comment by tenpaiyomi** [comment]
@pirj I take that back, I still had the `user.activate!` isolated out prior to the `expect { user.activate! }` from changing the code around to copy/paste for this PR.  Making that change does in fact cause the test to pass. so it seems to be a scenario that there is a bug where the `.to ...` vs `.to(...)` does not properly "end" its logic in the chain.

**Comment by pirj** [comment]
That's quite strange.
Can you please try adding the following to the same example group:
```ruby
  it do
    @a = 1
    expect { @a = 2 }.to change { @a }.to(3)
      .and change { @a }.to(4)
  end
```
What is the output when you run this example?
For the reference, my output:
```
  1) a is expected to change `@a` to 3 and change `@a` to 4
     Failure/Error:
       expect { @a = 2 }.to change { @a }.to(3)
         .and change { @a }.to(4)

          expected `@a` to have changed to 3, but is now 2

       ...and:

          expected `@a` to have changed to 4, but is now 2
 ```

**Comment by tenpaiyomi** [comment]
@pirj

I got the same output:

```
Failures:

  1) User states active on a shared instance is expected to change result to 3 and change result to 4
     Failure/Error: expect { @a = 2 }.to change { @a }.to(3).and change { @a }.to(4)

          expected result to have changed to 3, but is now 2

       ...and:

          expected result to have changed to 4, but is now 2
```

**Comment by pirj** [comment]
Not sure it can be considered a bug. `be_truthy` is used as an argument matcher to `change.to` here, and I'm not certain if it would be correct to reapply the chain to the parent matcher in this case. That would break the following e.g.:
```ruby
expect([[1]])
  .to contain_exactly be_truthy
  .and contain_exactly be_positive
```

That is actually checking the inner array with `be_positive`, i.e. `be_truthy.and(contain_exacrly(be_positive))` is matched against `[1]`, and `contain_exacrly(be_positive)` also against `[1]`, and `be_positive` against `1`.

Do you propose to change this logic so that it matches `be_truthy.and(be_positive)` against `[1]` in this example?

**Comment by tenpaiyomi** [comment]
@pirj No, thinking on it now I think the current logic is really the right setup,  Perhaps it would be better to just update the documentation to better expand on changing `change` and `.and` together, since I could not find much documentation for this type of scenario.

**Comment by pirj** [comment]
Pull requests are welcome.
Thanks! Please feel free to reopen if you plan to track documentation pull request here.

**Comment by JonRowe** [comment]
@tenpaiyomi It's standard Ruby precedence, e.g.
```
expect { ... }.to(matcher).and(matcher)
```
Rather than
```
expect { ... }.to matcher.and(matcher)
```
I'm open to improving the documentation but it'd need be in the composable section rather than one specific matcher, as it applies to all
