### ISSUE TITLE
The method aggregate_failures isn't showing the lines of the failures like rspec-core

### ISSUE THREAD

**Issue by fabriciobedin** [rspec/rspec-expectations#1160]
### Subject of the issue
When I add the method aggregate_failures in my expects on Cucumber, it isn't showing the lines of the failures, just the line of the block aggregate_failures.
If you look at [RSpec Core - aggregate_failures](https://relishapp.com/rspec/rspec-core/v/3-9/docs/expectation-framework-integration/aggregating-failures#enable-failure-aggregation-globally-using-%60define-derived-metadata%60) you can see the lines of each failure, but if you look at [RSpec Expectations - aggregate_failures](https://relishapp.com/rspec/rspec-expectations/docs/aggregating-failures) it shows only the failures without the lines.

### Your environment
* Ruby version: 2.6.0
* rspec-expectations version: 3.9.0

### Steps to reproduce
```
17.  Then 'validate the return of the endpoint xyz' do
18.    aggregate_failures do
19.      expect(response.status).to eq(200)
20.      expect(response.headers).to include("Content-Type" => "application/json")
21.      expect(response.body).to eq('{"message":"Success"}')
22.    end
23.  end
```

### Expected behavior
```
Failures:
  1) Client returns a successful response
     Got 3 failures:

     1.1) Got 3 failures from failure aggregation block "testing response".
          # ./spec/use_block_form_spec.rb:18
          # ./spec/use_block_form_spec.rb:10

          1.1.1) Failure/Error: expect(response.status).to eq(200)

                   expected: 200
                        got: 404

                   (compared using ==)
                 # ./spec/use_block_form_spec.rb:19

          1.1.2) Failure/Error: expect(response.headers).to include("Content-Type" => "application/json")
                   expected {"Content-Type" => "text/plain"} to include {"Content-Type" => "application/json"}
                   Diff:
                   @@ -1,2 +1,2 @@
                   -"Content-Type" => "application/json",
                   +"Content-Type" => "text/plain",
                 # ./spec/use_block_form_spec.rb:20

          1.1.3) Failure/Error: expect(response.body).to eq('{"message":"Success"}')

                   expected: "{\"message\":\"Success\"}"
                        got: "Not Found"

                   (compared using ==)
                 # ./spec/use_block_form_spec.rb:21
```

### Actual behavior
```
Got 3 failures from failure aggregation block "testing response":

  1) expected: 200
          got: 404

     (compared using ==)

  2) expected: "application/json"
          got: "text/plain"

     (compared using ==)

  3) expected: "{\"message\":\"Success\"}"
          got: "Not Found"

     (compared using ==)
```

**Comment by pirj** [comment]
Is there a line number if you don't wrap it with `aggregate_failures`?

**Comment by fabriciobedin** [comment]
yes, when I run without aggregate_failures I can see exactly the line of the first failure, but when I execute with aggregate_failures I only can see the line of the block `aggregate_failures` and not the lines of each failure.

**Comment by pirj** [comment]
Can you please paste this output to description for completeness?

Would you like to hack on this?

**Comment by fabriciobedin** [comment]
### Base feature
```test_aggregate_failures.feature
1. Feature: Feature name
2.
3.   @test_aggregate
4.   Scenario: Some scenario description
5.     * some scenario description
```

----------------------------------

### Without aggregate_failures
```test_aggregate_features_steps.rb
7.  Given('some scenario description') do
8.    expect(1).to be_eql 2
9.    expect(2).to be_eql 3
10.   expect(8).to be_eql 8
11.   expect(3).to be_eql 4
12. end
```

```
expected 1.eql?(2) to return true, got false (RSpec::Expectations::ExpectationNotMetError)
./features/steps_definitions/test_aggregate_failures_steps.rb:8:in 'some scenario description'
features/gherkins/test_aggregate_failures.feature:5:in '* some scenario description'
```
You can see exact the line of the first failure (./features/steps_definitions/test_aggregate_failures_steps.rb:8:in 'some scenario description')


----------------------------------

### With aggregate_failures
```test_aggregate_features_steps.rb
15. Given('some scenario description') do
16.   aggregate_failures do
17.     expect(1).to be_eql 2
18.     expect(2).to be_eql 3
19.     expect(8).to be_eql 8
20.     expect(3).to be_eql 4
21.   end
22. end
```

```
Got 3 failures from failure aggregation block:

1) expected 1.eql?(2) to return true, got false

2) expected 2.eql?(3) to return true, got false

3) expected 3.eql?(4) to return true, got false (RSpec::Expectations::MultipleExpectationsNotMetError)
./features/steps_definitions/test_aggregate_failures_steps.rb:16:in 'some scenario description'
features/gherkins/test_aggregate_failures.feature:5:in '* some scenario description'
```
You only can see the line of the block aggregate_failures (./features/steps_definitions/test_aggregate_failures_steps.rb:16:in 'some scenario description')


----------------------------------


### The expected result
```test_aggregate_features_steps.rb
26. Given('some scenario description') do
27.   aggregate_failures do
28.     expect(1).to be_eql 2
29.     expect(2).to be_eql 3
30.     expect(8).to be_eql 8
31.     expect(3).to be_eql 4
32.   end
33. end
```

```
Got 3 failures from failure aggregation block:

1) expected 1.eql?(2) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:28

2) expected 2.eql?(3) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:29

3) expected 3.eql?(4) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:31

(RSpec::Expectations::MultipleExpectationsNotMetError)
./features/steps_definitions/test_aggregate_failures_steps.rb:27:in 'some scenario description'
features/gherkins/test_aggregate_failures.feature:5:in '* some scenario description'
```
Now you can see exactly the line of each failure


----------------------------------

Yes, we would like to do this change. We saw some methods in RSpec Core that has something like this.
Do you think we can copy that methods from there? Or, RSpec Core is one dependention of RSpec Expectations?

**Comment by JonRowe** [comment]
The gems are all independent for this kind of use-case, `rspec-expectations` handling of this is vastly simplified compared to `rspec-core`, I would take a look at `lib/rspec/expectations/failure_aggregator.rb` line 93 contains the overall summary, whilst 158 and 164 have the failures / errors inspection. 

You'd need to add some simple backtrace support there.

**Comment by fabriciobedin** [comment]
Great, thank you for your help.  :)
I'll change it and open a pull request.

**Comment by fabriciobedin** [comment]
This is the first time I'm working in a gem, so I'm with some doubts. Could you help me please?

Is it a good idea copy the BacktraceFormatter class from RSpec core and put it inside `lib/rspec/expectations`?

I saw I need the `relative_path` method from RSpec Core Metadata too. The best option is copy the metadata.rb with only this method or put the method inside BackTraceFormatter?

**Comment by JonRowe** [comment]
Neither, it's not expected or desired to replicate large parts of rspec-core into expectations, we're looking for a minimal improvement here to help 3rd parties such as cucumber by printing a best effort line from the stack trace in the message.

**Comment by fabriciobedin** [comment]
@JonRowe I saw this improvement and others one isn't in the 3.9.1 release. Is there something wrong?
