### ISSUE TITLE
Problems with `output().to_stdout` involving formatted strings

### ISSUE THREAD

**Issue by manu29d** [rspec/rspec-expectations#1172]
### Subject of the issue
I am trying to output something in a tabular form to `stdout` (using `puts`). I am not able to get the test to pass.

### Your environment
* Ruby version: 2.6.5
* rspec-expectations version: 3.9.1

### Steps to reproduce
Truncated for readability
```ruby
# parking_lot.rb
  def get_status
    result = "Slot No. \t Registration No \t Colour\n"
    cars.each_with_index do |car, index|
      next if empty?(index)
      result = result + "#{index + 1} \t\t #{car[:registration_number]} \t\t #{car[:colour]}\n"
    end
    puts result
  end

# parking_lot_spec.rb
  describe '#get_status' do
    before do
      subject.park %w{ KA-01-HH-1234 White }
      subject.park %w{ KA-01-HH-9999 White }
      subject.park %w{ KA-01-BB-0001 Black }
      subject.park %w{ KA-01-HH-7777 Red }
      subject.park %w{ KA-01-HH-2701 Blue }
      subject.park %w{ KA-01-HH-3141 Black }
      subject.leave(4)
    end

    let(:expected_output) {
      "Slot No. \t Registration No \t Colour
1 \t\t KA-01-HH-1234 \t\t White
2 \t\t KA-01-HH-9999 \t\t White
3 \t\t KA-01-BB-0001 \t\t Black
5 \t\t KA-01-HH-2701 \t\t Blue
6 \t\t KA-01-HH-3141 \t\t Black"
    }

    it 'should display the correct status' do
      expect { subject.get_status }.to output(expected_output).to_stdout
    end
  end
```
### Expected behavior
The test should pass.

### Actual behavior
Fails with the following message
```
<The diff is empty, are your objects producing identical `#inspect` output?>
```

If the resulting diff is not there, shouldn't that mean that the test has passed?

**Comment by pirj** [comment]
If you set a breakpoint near `expect`, what is the output of `subject.get_status`, and what is `expected_output`? Maybe a newline is missing?
You can make `get_status` to return `result` in addition to printing it for more precise comparison.

**Comment by pirj** [comment]
> If the resulting diff is not there, shouldn't that mean that the test has passed?

No. Sometimes two objects are not `a == b`, but their `a.inspect == b.inspect`, and in this case we're unable to show the diff. You have to figure that out differently.

**Comment by manu29d** [comment]
Well, I had a newline missing :man_facepalming:
