### ISSUE TITLE
Usage of all and be_withing matcher together.

### ISSUE THREAD

**Issue by klaibthe** [rspec/rspec-expectations#1180]
When `all` and `be_within` matcher is intended to be used together it gives error.

## Example
```ruby
expect([2, 3, 4]).to all(be_within(1).of(5))
```

gives error response of

      Failure/Error: expect([2, 3, 4]).to all(be_within(1).of(5))
     
       expected [2, 3, 4] to all be within 1 of 5
     
          object at index 0 failed to match:
             expected 2 to be within 1 of 5
     
          object at index 1 failed to match:
             expected 3 to be within 1 of 5

**Comment by pirj** [comment]
What did you expect excactly @klaibthe ?

**Comment by JonRowe** [comment]
Hi @klaibthe in your example that is correct, both 2 and 3 are more than 1 away from 5. I'm closing for now as this the expected behaviour, but feel free to provide more information if you feel something is wrong.

**Comment by klaibthe** [comment]
> Hi @klaibthe in your example that is correct, both 2 and 3 are more than 1 away from 5. I'm closing for now as this the expected behaviour, but feel free to provide more information if you feel something is wrong.

My bad sorry. There has been a little misunderstanding from my side. Thank you for explanation
