### ISSUE TITLE
Doesn't work contain_exactly when expect not to nil

### ISSUE THREAD

**Issue by umemotoryo** [rspec/rspec-expectations#1181]
### Subject of the issue
Doesn't work contain_exactly when expect not to nil

### Your environment
* Ruby version: 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
* rspec-expectations version: 3.10.0.pre

### Steps to reproduce
```ruby
RSpec.describe do
  it { expect([nil, nil]).not_to contain_exactly(nil) }
end
```

### Expected behavior
The test should failed.

### Actual behavior
The test succeeded.

**Comment by umemotoryo** [comment]
Sorry, i'm wrong...

**Comment by JonRowe** [comment]
The `contain_exactly` matcher expects that an array contains exactly the contents passed. One `nil` is not the same as two `nil` values. So this is working as expected.

**Comment by umemotoryo** [comment]
@JonRowe  thank you.
