### ISSUE TITLE
Compound comparison matcher

### ISSUE THREAD

**Issue by SharkBeard** [rspec/rspec-expectations#1186]
### Subject of the issue

There is no way to do compound comparisons in an expectation.

### Steps to reproduce

```Ruby
expect(rand(5) + 1).to be(> 0).and be <= 6
```

### Expected behavior

Test Pass

### Actual behavior

`unexpected '>'`

**Comment by pirj** [comment]
```ruby
    expect(rand(5) + 1).to be.>(0).and be <= 6
```
worked quite fine:
```
  is expected to be > 0 and be <= 6
```

**Comment by JonRowe** [comment]
Operators in Ruby are methods, so as @pirj points out there is a way to make this work, but you have the brackets in the wrong place to delegate operators, this also works (note the ` ` after `to`): 
``` 
expect(rand(5) + 1).to (be > 0).and be <= 6
```
