### ISSUE TITLE
`be` with a block is deceptive

### ISSUE THREAD

**Issue by pirj** [rspec/rspec-expectations#1194]
### Subject of the issue

```ruby
    expect([-1,2,3]).to all be(&:positive?)
```

Found in https://github.com/rubocop-hq/rubocop-rspec/issues/919

### Expected behavior

A warning or an error makes it obvious that `be` doesn't accept a block.

### Actual behavior

````
  is expected to all be

1 example, 0 failures
```

**Comment by JonRowe** [comment]
There are a lot of places where we don't check for a block and issue a warning, we've generally not subscribed to the philosophy of warning about Rubyisms, in Ruby you can give a block to almost any method and it'll be ignored if its not expected...

**Comment by JonRowe** [comment]
e.g.
```
"1".to_i { |x| raise x }
# => 1
```

**Comment by pirj** [comment]
Agree, there are a lot more cases than just `be`. https://github.com/rubocop-hq/rubocop/issues/7798

I guess it's a good job for RuboCop RSpec.
