### ISSUE TITLE
Unexpected behaviour using `include` matcher with Time and iso8601 timestamps

### ISSUE THREAD

**Issue by bobf** [rspec/rspec-expectations#1211]
When using the `include` matcher to compare instances of `Time` and `Time#iso8601` I get inconsistent results depending on whether _Rails_ has been loaded:

```ruby
# Fails:
it do
  time = Time.new(2000, 1, 1, 0, 0, 0)
  expect([time.iso8601]).to include(time)
end

# Passes:
it do
  require 'rails'
  time = Time.new(2000, 1, 1, 0, 0, 0)
  expect([time.iso8601]).to include(time)
end
```

However this is not consistent with either the `eq` or `eql` matchers. Is this intended behaviour ? It seems like a false positive to me.

I have made a repository to demonstrate the issue here: https://github.com/bobf/rspec_rails_time_comparison_example

Steps to reproduce:
```bash
git clone https://github.com/bobf/rspec_rails_time_comparison_example.git
cd rspec_rails_time_comparison_example
bundle install
bundle exec rspec
```

**Comment by JonRowe** [comment]
Transferred to the correct repo to help future travellers

**Comment by bobf** [comment]
@JonRowe Ah, thank you - appreciated.
