### ISSUE TITLE
What is the recommended way to create dynamic matchers?

### ISSUE THREAD

**Issue by athix** [rspec/rspec-expectations#1299]
Per: https://github.com/rspec/rspec-expectations/blob/040d1b0bba83031c9ae432fd3a4462fdd1cc74e7/lib/rspec/matchers/built_in/has.rb#L4-L7

Developers are not intended to extend the BaseMatcher or DynamicPredicate classes themselves. However, I'm struggling on how to dynamically define matchers without either inheriting these classes, or duplicating them in my own extension.

My particular use case is that I want to support the following types of matchers on model specs:

```ruby
it { is_expected.to validate_email_format_of(:email)
it { is_expected.to validate_password_complexity_of(:password) }
it { is_expected.to validate_some_validator_of(:attribute) }
# Also support shoulda format:
it { should validate_email_format_of(:email) }
# And negation:
it { is_expected.not_to validate_email_format_of(:email) }
# And hopefully support options using `is_some_option`:
it { is_expected.to validate_password_complexity_of(:password).is_greater_than_or_equal_to(3) }
```

Where anything between `validate_` and `_of` gets mapped automatically to the appropriate custom validators.
* Where: `be_some_predicate` maps to `some_predicate?`
* Similarly: `validate_email_format_of` maps to `EmailFormatValidator`

**Comment by pirj** [comment]
Is there anything specific in `DynamicPredicate` that you want to reuse?

Implement [`method_missing`](https://github.com/rspec/rspec-expectations/blob/040d1b0bba83031c9ae432fd3a4462fdd1cc74e7/lib/rspec/matchers.rb#L958), [`respond_to_missing?`](https://github.com/rspec/rspec-expectations/blob/040d1b0bba83031c9ae432fd3a4462fdd1cc74e7/lib/rspec/matchers.rb#L971) that would your `validate_*` matcher name schema in an includable module.
Include that module in your spec helper:
```ruby
RSpec.configure do |config|
  config.include MyDynamicValidationMatchers
```

I suggest we continue this conversation in our mailing list.
If you feel that some code here comes handy in your matchers with fuzzy naming, and it also makes `rspec-expectations` more structured, please feel free to send a PR.

**Comment by athix** [comment]
@pirj I just implemented a solution using method_missing, good to know I was on the right track! :smile: 

For those who find this in the future and want to do something similar, see: [athix/validator-matchers](https://github.com/athix/validator-matchers)

If I think of a clever way to abstract my solution into a reusable format, I'll open a PR. Thank you Phil!

**Comment by pirj** [comment]
You're always welcome!

**Comment by JonRowe** [comment]
> However, I'm struggling on how to dynamically define matchers without either inheriting these classes, or duplicating them in my own extension.

They are private so we can make internal changes without bumping a major version, hence the disclaimer, for a public gem duplicating them would be fine, for your own project where you are willing to accept breakage inheriting is largely fine.

**Comment by athix** [comment]
@pirj @JonRowe,

For the public interface, would you prefer creating a new block matcher similar to the existing one:

```ruby
RSpec::Matchers.define :matcher_name do |expected|
  match do |actual|
    [...]
  end
end
```

```ruby
RSpec::Matchers.dynamic /regex_here/ do |expected|
  match do |actual|
    [...]
  end
end
```

Or moving to a public class that can be inherited safely? e.g.:

```ruby
class MyCustomMatcher < RSpec::Matchers::Custom::Static
  def initialize(expected)
    @matcher_name = :matcher_name
    @expected = expected
  end

  def match(actual)
    [...]
  end
end
```

```ruby
class MyCustomMatcher < RSpec::Matchers::Custom::Dynamic
  def initialize(expected)
    @matcher_regex = /regex_here/
    @expected = expected
  end

  def match(actual)
    [...]
  end
end
```

Personally, I would prefer the latter as it gives more flexibility to the extension developer while still maintaining the abstraction layer.

(The examples are given to provide a rough idea of what it would look like, not as literal implementation)

**Comment by JonRowe** [comment]
I don't really want to encourage creating dynamic matchers with rspec itself, they already have a tonne of overloading that can be wrong and leads to ambiguity. If an extension wants to go down the `method_missing` path that seems fine, but I'm not sure its worth the complexity of adding it to rspec-expectations.

I also don't want to encourage inheriting from our classes, the preferred route is you vendor them and inherit off your own.

**Comment by athix** [comment]
Hmm. My initial thoughts are that if dynamic matchers are desirable, there should be some sort of public API available to create them, otherwise both extensions and applications that define them will become too tightly coupled to `rspec-expectations` implementation details.

That said, you raise a good point on ambiguity and complexity. Ideally, it should be easy for an application developer to see exactly where a matcher is coming from, and to know if a matcher is being overwritten.

I don't want to waste your time, so I'll put some more thought into this problem and see what I come up with.
