### ISSUE TITLE
$stdout.ioctl is not defined when using output matcher

### ISSUE THREAD

**Issue by JunichiIto** [rspec/rspec-expectations#1305]
### Subject of the issue

I noticed `$stdout.ioctl` is not defined when using output matcher. This is because StringIO class that is replaced by output matcher does not define `ioctl` method like IO class.

### Your environment
* Ruby version: 3.0.1
* rspec-expectations version: 3.10.1

### Steps to reproduce

Run the script below:

```foo.rb
# modified from https://github.com/piotrmurach/tty-screen/blob/master/lib/tty/screen.rb
TIOCGWINSZ_PPC = 0x40087468 # macos, freedbsd, netbsd, openbsd

def foo
  format = "SSSS"
  buffer = ([0] * format.size).pack(format)
  puts $stdout.ioctl(TIOCGWINSZ_PPC, buffer)
end

RSpec.describe 'ioctl' do
  example do
    foo
    expect{ foo }.to output('0').to_stdout
  end
end
```

### Expected behavior

The test should pass.

### Actual behavior

The test fails:

```
$ rspec foo.rb
0
F

Failures:

  1) ioctl is expected to output "0" to stdout
     Failure/Error: puts $stdout.ioctl(TIOCGWINSZ_PPC, buffer)
     
     NoMethodError:
       undefined method `ioctl' for #<StringIO:0x0000000149afeb88>
     # ./foo.rb:6:in `foo'
     # ./foo.rb:12:in `block (3 levels) in <top (required)>'
     # ./foo.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.0028 seconds (files took 0.08339 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./foo.rb:10 # ioctl is expected to output "0" to stdout
```

**Comment by pirj** [comment]
`ioctl` is platform-dependent and io type dependent. Would it work the same way if you redirect the output of the script to a file? Is it still the standard output? I believe `ioctl` expects a terminal.

Would this test still run on Windows?

**Comment by JonRowe** [comment]
Can you try `to_stdout_from_any_process` which uses temp files rather than a StringIO, I'm apprehensive to re-implement this behaviour ourselves, and to always use files, but if it works we can do two things 1) update the documentation to make it clear that you should use the slower matcher if you require "closer to the metal" emulation, 2) add an alias for `to_stdout_from_any_process`  to make this clearer?

**Comment by pirj** [comment]
Tried `to_stdout_from_any_process`, it expectedly fails with something like
```ruby
> File.new('1.txt', 'wb').ioctl(322355, '234234')
Errno::ENOTTY: Inappropriate ioctl for device @ rb_ioctl - 1.tx
```

**Comment by JunichiIto** [comment]
To avoid this problem, I used `allow_any_instance_of(StringIO).to receive(:ioctl).and_return(-1)` like this:
https://github.com/emsk/bundle_outdated_formatter/pull/6/files#diff-a295ebafa2ba6e52e822ef6e6c91121c606de930f63af9420709f7126b203c6bR446

`ioctl` method is used in another gem as a dependency:
https://github.com/piotrmurach/tty-screen/blob/master/lib/tty/screen.rb#L216

But I'm not sure this solution is good or not. Any suggestions are appreciated.

**Comment by pirj** [comment]
`TTY::Screen` does a good job at detecting if stdout is a tty, why it doesn't work when it's stubbed with an instance of `StringIO`? Wondering if [this](https://github.com/piotrmurach/tty-screen/blob/a553395b53cadfb2f25a0c0a4e31105d76b72644/lib/tty/screen.rb#L185) is called.

**Comment by JonRowe** [comment]
This sort of needs to be a suggestion to Ruby core, if StringIO is intended to be a drop in replacement it should implement this low level method, if we were to emulate it we open ourselves up to bugs when the ruby core implementation changes

**Comment by JunichiIto** [comment]
@pirj 
> TTY::Screen does a good job at detecting if stdout is a tty, why it doesn't work when it's stubbed with an instance of StringIO? Wondering if this is called.

This is because some examples call `output` + `to_stdout` like [this](https://github.com/emsk/bundle_outdated_formatter/pull/6/files#diff-a295ebafa2ba6e52e822ef6e6c91121c606de930f63af9420709f7126b203c6bR442).

[This line](https://github.com/piotrmurach/tty-screen/blob/a553395b53cadfb2f25a0c0a4e31105d76b72644/lib/tty/screen.rb#L185) is called via `spec_helper.rb` and `@output` and `$stdout` are IO objects at this time. So `@output.respond_to?(:ioctl)` returns `true`. But `$stdout` is [replaced](https://github.com/rspec/rspec-expectations/blob/v3.10.1/lib/rspec/matchers/built_in/output.rb#L141) with `StringIO` when `output` + `to_stdout` is called. Then `$stdout.respond_to?(:ioctl)` will return `false` and the example fails with `NoMethodError`.

**Comment by JunichiIto** [comment]
Sorry, now I noticed the latest code avoids this issue with [such a monkey patch](https://github.com/emsk/bundle_outdated_formatter/blob/v0.7.0/spec/spec_helper.rb#L16-L21). I did not have to care about it😓

**Comment by pirj** [comment]
> with such a monkey patch. I did not have to care about it

Does it solve the problem for you?

**Comment by JunichiIto** [comment]
Yes. I'll close this issue. Thank you for your support.
