### ISSUE TITLE
Compound expectations are run inside one another's context (?)

### ISSUE THREAD

**Issue by ojab** [rspec/rspec-expectations#1316]
### Subject of the issue
When custom matcher freeze time and that matcher is used multiple times in a compound expectation — I see that in the second matcher run time is already frozen and indeed I see in the backtrace that it's called from previous matcher run somehow. 

### Your environment
* Ruby version: 3.0.2
* rspec-expectations version: git main

### Steps to reproduce
```ruby
require 'active_support'
require 'active_support/testing/time_helpers'

RSpec.describe Object do
  include ActiveSupport::Testing::TimeHelpers

  RSpec::Matchers.define :date_gt do |expected_date|
    match do |proc|
      freeze_time do
        Date.parse(expected_date) > proc.call
      end
    end

    supports_block_expectations
  end

  specify do
    expect { Date.today }.to date_gt('2021-08-31').and date_gt('2021-08-30')
  end
end
```

### Expected behavior
It works!

### Actual behavior
Backtrace:
```
binding.irb here =====>>>>> "/tmp/rspec-tst/tst_spec.rb:9:in `block (3 levels) in <top (required)>'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/dsl.rb:135:in `block (2 levels) in match'",
"gems/rspec-support-28526172c423/lib/rspec/support.rb:118:in `with_failure_notifier'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/dsl.rb:133:in `block in match'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/built_in/compound.rb:166:in `block in initialize'",
Previous Date.parse =====>>>>> "/tmp/rspec-tst/tst_spec.rb:11:in `block (4 levels) in <top (required)>'",
"gems/activesupport-6.1.4.1/lib/active_support/testing/time_helpers.rb:169:in `travel_to'",
"gems/activesupport-6.1.4.1/lib/active_support/testing/time_helpers.rb:226:in `freeze_time'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/dsl.rb:533:in `method_missing'",
Previous freeze_time =====>>>>> "/tmp/rspec-tst/tst_spec.rb:10:in `block (3 levels) in <top (required)>'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/dsl.rb:135:in `block (2 levels) in match'",
"gems/rspec-support-28526172c423/lib/rspec/support.rb:118:in `with_failure_notifier'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/dsl.rb:133:in `block in match'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/built_in/compound.rb:165:in `initialize'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/built_in/compound.rb:84:in `new'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/built_in/compound.rb:84:in `match'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/built_in/compound.rb:258:in `match'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/matchers/built_in/base_matcher.rb:38:in `matches?'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/expectations/handler.rb:27:in `with_matcher'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/expectations/handler.rb:48:in `handle_matcher'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/expectations/expectation_target.rb:65:in `to'",
"gems/rspec-expectations-dba67987c63f/lib/rspec/expectations/expectation_target.rb:139:in `to'",
"/tmp/rspec-tst/tst_spec.rb:19:in `block (2 levels) in <top (required)>'",
```
Error message from ActiveSupport due to double frozen time:
```
Failures:

  1) Object is expected to date gt "2021-08-31" and date gt "2021-08-30"
     Failure/Error:
       freeze_time do
         Date.parse(expected_date) > proc.call
       end
     
     RuntimeError:
     
       Calling `travel_to` with a block, when we have previously already made a call to `travel_to`, can lead to confusing time stubbing.
     
       Instead of:
     
          travel_to 2.days.from_now do
            # 2 days from today
            travel_to 3.days.from_now do
              # 5 days from today
            end
          end
     
       preferred way to achieve above is:
     
          travel 2.days do
            # 2 days from today
          end
     
          travel 5.days do
            # 5 days from today
          end
```

**Comment by JonRowe** [comment]
This is to be expected, RSpec does not prevent mutating global state and ActiveSupport is mutating the global time library, you must work around this or detect it yourself.

**Comment by ojab** [comment]
It's not about global state per se, it's about expectation that expectations (no pun intended) are executed serially instead of inside one another.

To tell it differently:
```ruby
  specify do
    expect { Date.today }.to date_gt('2021-08-31').and date_gt('2021-08-30')
  end
```
should do the same as
```ruby
expect { Date.today }.to date_gt('2021-08-31')
expect { Date.today }.to date_gt('2021-08-30')
```
I suppose it could be the edge case because we're trying to execute block only once, but then I either don't understand the behavior: why we [simplified ofc] don't memoizing first block invocation somewhere inside the compound matcher and just passing `proc { memoized_result }` to the latter invocations.

It would give incorrect result if, for example, matchers would travel to different date, but this could happen right now as well:
```ruby
  RSpec::Matchers.define :date_gt do |expected_date|
    match do |proc|
      freeze_time
      Date.parse(expected_date) > proc.call
    ensure
      travel_back
    end

    supports_block_expectations
  end
```
does exactly that.

**Comment by JonRowe** [comment]
Matchers are not able to memoise results because they can be passed around and used multiple times.

**Comment by ojab** [comment]
Ok, in that case I suppose I should check the code then, current behavior is completely unclear to me.
For me looks like compound matcher should do [pseudocode] `expectations.reduce(&:success?)` instead of calling one matcher from inside of the other one.

**Comment by JonRowe** [comment]
They are sequential when values are used and nested when blocks are used, this is so that the block is executed once. e.g.

```
expect { Date.today }.to date_gt('2021-08-31').and date_gt('2021-08-30')
```

Is equivalent to:

```
expect {
  expect {Date.today }.to date_gt('2021-08-31')
}.to  date_gt('2021-08-30')
```

Whilst:

```
expect(Date.today).to date_gt('2021-08-31').and date_gt('2021-08-30')
```

Is equivalent to:

```
expect(Date.today).to date_gt('2021-08-31')
expect(Date.today).to date_gt('2021-08-30')
```

**Comment by JonRowe** [comment]
As you can imagine, with blocks that have side effects (like inserting into the database) it is critical they are executed once.

**Comment by ojab** [comment]
Oh, got it. Thanks for clarification.

**Comment by pirj** [comment]
Looking at `TimeHelpers`'s implementation it seems that you can get around this issue by using a non-block form of `freeze_time`:
  RSpec::Matchers.define :date_gt do |expected_date|
    match do |proc|
      freeze_time
      Date.parse(expected_date) > proc.call
      travel_back
    end

    supports_block_expectations
  end
```

**Comment by ojab** [comment]
Yeah, but as noted in https://github.com/rspec/rspec-expectations/issues/1316#issuecomment-911533772 it's broken a bit (or, let's say, different from two non-compound expectations), time from the first `freeze_time` is returned in subsequent expectations.

**Comment by pirj** [comment]
How does it matter if it freezes at two different points of time if the block is only called once?

Let's see it from another point of view. The following:
```ruby
expect { Date.today }.to date_gt('2021-08-31').and date_gt('2021-08-30')
```
expands to:
```ruby
expect { 
  expect { Date.today }.to date_gt('2021-08-31')
}.to date_gt('2021-08-30')
```

and, as you may notice, the fact that the inner call's `proc.call` will return the return value of `Date.today`.
But in the second matcher, it will get the return value of the `match` call of the previous matcher. Not a date, but rather a boolean.

I might be mistaken, but it looks like that `actual.call` does not guarantee that it will return the value returned by your block, and it does that coincidentally in the first matcher.

What's worst of all, it might be deceiving if it happens that `freeze_time` returns time. In this case, `actual.call` in the second matcher will return the result of `freeze_time` from the first matcher, and good luck debugging that.

Built-in matchers do not rely on the return value of `actual.call`. You may see nothing related fails if you wrap the block to return a `nil`:
```diff
     class BlockExpectationTarget < ExpectationTarget
+      def initialize(target)
+        @target = proc { |*args| target.call(*args); nil }
+      end
```
And your matchers shouldn't rely on the return value, too.
