### ISSUE TITLE
`BuiltIn::Compound` vs redefined `actual`

### ISSUE THREAD

**Issue by zverok** [rspec/rspec-expectations#1317]
### Subject of the issue

When we compound (by `.and`, say), several diffable matchers with redefined `actual`, the compound ignores actual redefinition

### Your environment
* Ruby version: 2.7
* rspec-expectations version: 3.10.1

### Steps to reproduce

Taking the [textbook example](https://relishapp.com/rspec/rspec-expectations/docs/custom-matchers/define-diffable-matcher#redefine-actual-(with-diff-lcs-1.4.4)), and adding `.and` to it:

```ruby
RSpec::Matchers.define :have_content do |expected|
  match do |actual|
    @actual = File.read(actual).chomp

    values_match? expected, @actual
  end

  diffable
end

RSpec.describe 'Compare files' do
  before { File.write 'data.txt', 'Data' }

  context 'when files are different' do
    it {
      expect('data.txt').to have_content("No\nData\nhere")
        .and have_content("No\nData\nthere!")
    }
  end
end
```

### Expected behavior

Something like...
```
     Failure/Error:
       expect('data.txt').to have_content("No\nData\nhere")
         .and have_content("No\nData\nthere!")
     
          expected "Data" to have content "No\nData\nhere"
     
       ...and:
     
          expected "Data" to have content "No\nData\nthere!"
       Diff for (have content "No\nData\nhere"):
       @@ -1,4 +1,2 @@
       -No
       Data
       -here
       
       Diff for (have content "No\nData\nthere!"):
       @@ -1,4 +1,2 @@
       -No
       Data
       -there!
```

### Actual behavior
```
     Failure/Error:
       expect('data.txt').to have_content("No\nData\nhere")
         .and have_content("No\nData\nthere!")
     
          expected "Data" to have content "No\nData\nhere"
     
       ...and:
     
          expected "Data" to have content "No\nData\nthere!"
       Diff for (have content "No\nData\nhere"):
       @@ -1,4 +1,2 @@
       -No
       -Data
       -here
       +data.txt
       
       Diff for (have content "No\nData\nthere!"):
       @@ -1,4 +1,2 @@
       -No
       -Data
       -there!
       +data.txt
```

### Analysis

There is no "bug" actually, rather a missing feature; nothing in Compound handles non-default `actual` for diffing, while non-default `expected` is [accounted for](https://github.com/rspec/rspec-expectations/blob/main/lib/rspec/matchers/built_in/compound.rb#L55). Fixing it will probably require the full redesign of `::RSpec::Matchers::ExpectedsForMultipleDiffs` into some `DataForMultipleDiffs` or something.

I can work on the PR if the reasoning above is approved.

(I suspect the problem should've been discussed already, but couldn't find the previous discussions :shrug: )

**Comment by JonRowe** [comment]
I am on the fence about fixing this, the instance variable is technically a private implementation detail and overriding it is not really expected, and really you are doing repeated work here with actual when it is not expected to change in this fashion. On the other hand the instance method actual is public api, and you could be returning something different there so perhaps the multiple diff code should take that into account. 

> I suspect the problem should've been discussed already, but couldn't find the previous discussions 🤷 
As far as I know this is the first time it has come up, most people don't override actual.

**Comment by zverok** [comment]
> , the instance variable is technically a private implementation detail and overriding it is not really expected, and really you are doing repeated work here with actual when it is not expected to change in this fashion. On the other hand the instance method actual is public API,

I demonstrated it with instance variable because that's how the docs do it :shrug: 
Overriding `actual` (whether with the method, or with instance var) is documented thing to do, and on my way with RSpec matchers I did that a lot, actually; just somehow never `.and`ed them :grinning: 

>  most people don't override actual

To the best of my knowledge, most people don't create (complex) custom matchers at all, but we do it all the time, so :shrug: 

Overriding `actual` is super-useful on block expectations, for example: `expect { some code }.to create_list_of_data(...)` -- here any useful diff of what happened is impossible without redefining.

**Comment by JonRowe** [comment]
Plenty of people create complex custom matchers :p

**Comment by pirj** [comment]
I arrived to a relatively minor change that allows for compound matchers to work correctly with both overridden `actual` and reassigned `@actual`.
The change exclusively touches the private API. If you agree to such an approach, I'll be happy to send a PR:

![image](https://user-images.githubusercontent.com/6916/131917452-bdd822f9-cfb2-4e6b-bf66-91abdc59869d.png)

No specs fail apart from `spec/rspec/matchers/expecteds_for_multiple_diffs_spec.rb`.

**Comment by JonRowe** [comment]
Seems reasonable, I was also going to suggest that class as the target for a fix, it just needs to handle multiple "pairs" of data, might need a new name...

**Comment by pirj** [comment]
I'd go with `MultiMatcherDiff`. WDYT?

There seem to be some evidence of recursive behaviour:
> If provided value is already an ExpectedForMultipleDiffs then it just returns it.

so I'm reluctant to splitting it into two classes (one for single diff, one for multiple that could reuse the first one).

**Comment by JonRowe** [comment]
The intent of the original class is to handle this scenario, there is no need for multiple classes.

**Comment by konovalov-nk** [comment]
Is there a workaround? Spent around 5 hours on this: googling, reading RSpec documentation, code, going step-by-step through `binding.pry` and figuring out why reassigning `@actual` never works when using compound `and` matcher 🤣

**Comment by pirj** [comment]
@konovalov-nk I apologize for the frustration you're dealing with. Can you try if [this PR's branch](#1319) fixes it for you?

**Comment by konovalov-nk** [comment]
@pirj thanks for a swift response!

I'm pretty sure it would fix it but I haven't tested yet.
I'll let you know once I do 🙇

My use case is pretty simple:

```ruby
def render_tags(current_tags)
  # some code that takes array of hashes
  # and merges them into a single Hash
end

RSpec::Matchers.define :include_tags do |expected|
  match do |actual|
    @actual = render_tags(actual.formatter.current_tags)
    values_match? @actual, @actual.merge(expected)
  end

  diffable
end

RSpec::Matchers.define :include_tag_keys do |expected|
  match do |actual|
    @actual = render_tags(actual.formatter.current_tags).keys
    expected.all? { |expected_key| @actual.include?(expected_key) }
  end

  diffable
end

# Usage
it "contains tags with keys" do
  logger = Rails.logger
    .tagged({ meta: "abc" })
    .tagged({ payload: "sample" })
    .tagged({ error: "some error" })

  expect(logger).to include_tags(
    meta: metadata,
    payload: payload,
  ).and include_tag_keys(:metadata, :payload, :error)
end
```
