### ISSUE TITLE
expect(actual).to eq(expected) is giving error -> Error Message: TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by adalberto02** [rspec/rspec-expectations#1335]
Im using Gauge-UI with Capybara

I Use **expect(actual).to eq(expected)**  and if they are not equal the test throws an error: **Error Message: TypeError: no implicit conversion of nil into String**

both **actual** and **expected** are not empty.

<img width="498" alt="Screen Shot 2021-12-04 at 6 10 09 PM" src="https://user-images.githubusercontent.com/3419059/144727381-22641d63-f839-4e3e-8907-5f3e608dcefd.png">

expect behavior:
Test Should Fail and message should be actual does not equal expected

Thank you

**Comment by JonRowe** [comment]
:wave: Can you provide more details, what is `expected` and `actual`? The `eq` matcher is well tested so we'll need you to reproduce this failure in a small isolated snippet for us to investigate further, its possible this is a failure in guage-ui or other gems.

**Comment by adalberto02** [comment]
Hi 👋 , Thank you so much for taking a Look. Below is the Step I created:
What I do is update a rule in a previous step, then in the Step below I refresh the page to make sure that the rule is update.
But there is a bug in our system that is causing the rule not to be updated. 

Below I get the updated rule name from the field in the UI and I try to verify that it equals to the rule name the updated it to. 
so this should return a fail because of our bug, because **rule_name** and **rule** are not equal. But the test returns an error:   **Error Message: TypeError: no implicit conversion of nil into String**
```
step 'RULES: Verify that <rule> was updated' do | rule | 
  page.driver.browser.navigate.refresh
  rule_name = find(:xpath, '//*[@name="name"]')["value"]
  expect(rule_name).to eq(rule)
end

```

If the the names are equal the test passes fine, if not, you get the error.

Thank you

**Comment by pirj** [comment]
A  few lines of backtrace would be very helpful. Appreciate if you run `rspec` with `--backtrace` flag not to skip any internals that may contain the information to pinpoint the problem.

**Comment by adalberto02** [comment]
Hi,
I run the Test with: **bundle exec gauge run specs/**
And it's not returning a trace. 
Here is a screenshot below, The original name for the rule is on the First box, the updated name is the Second box. 


<img width="808" alt="Screen Shot 2021-12-05 at 9 57 25 AM" src="https://user-images.githubusercontent.com/3419059/144752791-cb36086a-180b-453e-9390-3f5f05f55349.png">

**Comment by pirj** [comment]
There are various ways to have more debug information.
One obvious way is to monkey patch `TypeError`'s `initialize`, set a breakpoint there, and call `caller` to get the trace.
Another way that may or may not work is to put `--backtrace` to `.rspec` file.
Yet another is to use `pry-rescue` gem to automatically stop in a REPL when an exception occurs, and call `caller` there.

With the information you've provided so far we're blindfolded.

**Comment by JonRowe** [comment]
This: `bundle exec gauge run specs/` is not an RSpec command, and this:

```
step 'RULES: Verify that <rule> was updated' do | rule | 
  page.driver.browser.navigate.refresh
  rule_name = find(:xpath, '//*[@name="name"]')["value"]
  expect(rule_name).to eq(rule)
end
```

Is not RSpec code, given you don't have a backtrace from guage its possible this is a guage bug.

**Comment by adalberto02** [comment]
Yeah, I try all day Yesterday debugging this issue, I realize it could be a gauge bug too. Thank you for the Suggestions, I will try that today.

**Comment by JonRowe** [comment]
I'm going to close this for now, but if you find something that is isolatable to RSpec please do follow up.

**Comment by adalberto02** [comment]
Sounds Good. Thank you

**Comment by adalberto02** [comment]
Hi, I was able to more information. When I use the Code below, so it's something to do with the **expect()**:

<img width="615" alt="Screen Shot 2021-12-08 at 12 36 57 PM" src="https://user-images.githubusercontent.com/3419059/145256583-01048b54-b030-4c6b-a612-35a55bb5c806.png">

I get this error:

<img width="1056" alt="Screen Shot 2021-12-08 at 12 36 05 PM" src="https://user-images.githubusercontent.com/3419059/145256689-103c03a0-675a-42e4-87df-8b6e8bd3fd46.png">

**Comment by JonRowe** [comment]
Thats not an error, that byebug stepping into an implementation.

**Comment by adalberto02** [comment]
Yeah, You're right. It's steps in there even for a Successful scenario.

Thank you.
