### ISSUE TITLE
Chaining different block-expecting matchers

### ISSUE THREAD

**Issue by apotonick** [rspec/rspec-expectations#1336]
Hi everyone! :heart:

My "quick" question is, Is it possible to chain multiple block-expecting matchers like `change` with other third-party matchers?

In [`rspec-trailblazer`](https://github.com/trailblazer/rspec-trailblazer/blob/master/lib/rspec/trailblazer/matchers.rb#L25) we are playing around with a new `pass_with` matcher and it would be cool to be able to use it as follows.

```ruby
expect { run({duration: "2.24"}) } # `run` invokes an operation and returns a {Result} object
  .to pass_with({duration: 144})
  .and change { "yo" }.by(1)
```

I understand that `Change` runs the to-be-tested code using `#perform_change` in order to catch before and after snapshots. As this makes sense in a `change`-only chain, how would that work in combination with our `pass_with` matcher? Currently, we receive a proc from `rspec/matchers/built_in/compound.rb:173` as `actual` but if we were to invoke this block, `change` cannot capture snapshots anymore.

After looking through the `Change` matcher code and attempting to understand how `supports_block_expectations` works I'm skeptical if this could work at all. Any clues here? Is maybe our matcher design wrong?

**Comment by pirj** [comment]
> as actual but if we were to invoke this block, change cannot capture snapshots anymore

To my best memory, the way there are combined allows them all to capture before and after snapshots. The block passed to each matcher is not the original block you pass to `expect`, but rather a wrapped other matcher's `matches?`. Only the deepest matcher will receive the block, and only it will ever call this block.

You can check for an example [in a spec](https://github.com/rspec/rspec-expectations/blob/d9fd9a5589e3914bcd25d66560eccadd75493727/spec/rspec/matchers/built_in/compound_spec.rb#L54). It's not so easy to read as is, but it's basically:
```ruby
expect {
  w += 1; x += 2; y += 3; z += 4
}
  .to change { w }.to(1)
  .and change { x }.to(2)
  .and change { y }.to(3)
  .and change { z }.to(4)
```

[Here is](https://github.com/rspec/rspec-expectations/blob/62f31bc18f6f4ff2f0154890ba29ee3508b945af/lib/rspec/matchers/built_in/compound.rb#L165) where the wrapping happens.

If you have further questions, you are welcome to [our mailing list](https://rspec.info/help/). We strive to keep the issue tracker for bugs and features. Thanks for understanding.
