### ISSUE TITLE
`expect` with no arguments can cause confusion

### ISSUE THREAD

**Issue by solnic** [rspec/rspec-expectations#1354]
### Subject of the issue

One of my team mates had a failing test and couldn't figure it out. I was asked to help and it turned out there was a space between `expect` and its arguments

This syntax is valid Ruby but obviously it doesn't do what you want it to do and causes a confusing failure. That's why I thought that it should simply raise an argument error instead.

WDYT?

### Your environment

* Ruby version: 2.7
* rspec-expectations version: 3.10.0

### Steps to reproduce

```ruby
expect (foo).to receive(:bar)
```

### Expected behavior

It should raise an argument error so that it's clear you misused `expect` method.

### Actual behavior

Raises a confusing error depending on what your example is doing. In our case it was something like:

```
     NoMethodError:
       undefined method `to' for #<OurObject>
```

Which was really confusing because it happened to be a spec for a mailer and there was a `to` method and a `to` key in one of the options hashes that we use, so when you looked at the exception quickly you thought it had something to do with that.

**Comment by pirj** [comment]
What if it's also followed by a block?

```ruby
expect (foo).to receive(:bar) { 'and return this ' }
```

I can't tell of the top of my head what will receive the block as an argument, `expect` or `receive`?
Luckily enough, from my brief testing, it's `receive`. But is it always the case? I recall that `do`/`end` would behave differently.

It would make sense to add such a warning. Wondering if it's not naturally fixed already with the [separation from block and value expectations](https://github.com/rspec/rspec-expectations/pull/1285) already that we did in [RSpec 4](https://github.com/rspec/rspec-expectations/tree/4-0-dev). Do you want to test that?

If it wasn't fixed - a PR is welcome.

**Comment by JonRowe** [comment]
Isn't this a Ruby precendence issue? It's parsing `(foo).to` before it ever goes to `expect`

**Comment by JonRowe** [comment]
```
class BasicTo
  def initialize(thing)
    @thing = thing
  end

  def to(matcher)
    matcher.run(@thing)
  end
end

class BasicEq
  def initialize(thing)
    @thing = thing
  end

  def run(other)
    other == @thing
  end
end

def eq(thing)
  BasicEq.new(thing)
end

def expect(thing)
  BasicTo.new(thing)
end

expect(1).to eq 2
# passes
expect (1).to eq 2
#  undefined method `to' for 1:Integer (NoMethodError)
```

**Comment by JonRowe** [comment]
In fact if you do use `expect` with no argument e.g.
```
RSpec.describe do
  specify do
    expect
  end
end
```

You do get an error:
```
 ArgumentError:
       You must pass either an argument or a block to `expect`.
```

So theres really not much we can do here short of monkey patching `to` everywhere which is not something we really want to do.

**Comment by pirj** [comment]
Yep, it takes the whole thing to the right of that extra space as an argument to `expect`.

And `expect` will never have a chance to print that warning message before the exception that you see that `#to` is not defined on MyObject is raised.

**Comment by solnic** [comment]
Oh wow, Ruby confused even me 🙂 Thanks for such a quick response. I suppose we could have a cop for that in rubocop-rspec! I'm gonna close this as clearly you can't do anything about it. I appreciate your work!
