### ISSUE TITLE
Comparison between BigDecimal and Floats fails using match_array

### ISSUE THREAD

**Issue by jeduardo824** [rspec/rspec-expectations#1356]
### Subject of the issue
When I compare the equality of an array of Big Decimal numbers with Floats, the spec fails.

![image](https://user-images.githubusercontent.com/27960597/155156028-db90e6a4-5c28-4a59-98c4-b32a8831a5e9.png)

I know BigDecimal and Floats are different in terms of implementation, but since `0.42e1` is the same as `4.2`, I wondered if `match_array` should return `true` in this case or not?

### Your environment
* Ruby version: 2.7.5
* rspec-expectations version: 3.9.2

### Steps to reproduce
```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.9.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.describe 'match_array with BigDecimal and Floats' do
  it 'fails' do
    expect([BigDecimal("4.2"), BigDecimal("8.2")]).to match_array([4.2, 8.2])
  end
end
```

### Expected behavior
The expectation should return true

### Actual behavior
The expectation returns false

**Comment by pirj** [comment]
Thanks for reporting.

Matching fails [here](https://github.com/rspec/rspec-support/blob/623608b4f49c063fca2616cb3e35ae62ea5fe5cf/lib/rspec/support/fuzzy_matcher.rb#L31) when comparing specifically `8.2` and `0.82e1`.
Problem is:
```
BigDecimal("8.2") == 8.2 # => false
BigDecimal("4.2") == 4.2 # => true
```
This remains unfixed in Ruby 3.0.3. But both return `true` in Ruby 3.1.0.

So it's not specifically RSpec, it's Ruby. I'd suggest finding a corresponding Ruby ticket and see if there are plans to backport this into 2.7.x and 3.0.x.

I'm on the fence to working around the default Ruby behaviour in RSpec, as it's a double-edged sword.

**Comment by JonRowe** [comment]
I'm inclined to say this is a Ruby semantic, even if its a broken one in 3.0.3, and close this.

**Comment by pirj** [comment]
I can't find anything in [`ruby/bigdecimal`'s changelog](https://github.com/ruby/bigdecimal/blob/master/CHANGES.md#310) that would directly hint that such scenario was buggy and was fixed.

Again, I'm opposed on working this around in RSpec, as a passing test for a failing comparison in production code is even less fun than a failing test that there's a possible workaround for:
```diff
- expect([BigDecimal("4.2"), BigDecimal("8.2")]).to match_array([4.2, 8.2])
+ expect([BigDecimal("4.2"), BigDecimal("8.2")].map(&:to_f)).to match_array([4.2, 8.2])
```

**Comment by jeduardo824** [comment]
Thank you all for the explanations!

Just for record, another workaround would be:
`expect([BigDecimal("4.2"), BigDecimal("8.2")]).to match_array([4.2, 8.2].map(&:to_d))`
