### ISSUE TITLE
Ruby 3.0.2 bundle install tries to install rubysl

### ISSUE THREAD

**Issue by dblock** [rspec/rspec-expectations#1358]
### Subject of the issue

Ruby 3.0.2 bundle install complains on rubysl. 

Works with Ruby 2.6.5.

```
$ bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby

    rspec-expectations was resolved to 3.10.0.pre, which depends on
      Ruby (>= 1.8.7)

    rubysl was resolved to 1.1.0, which depends on
      rubysl-irb (~> 1.0) was resolved to 1.0.2, which depends on
        Ruby (~> 1.8.7)
```

This gets evaluated somehow:

```
platforms :rbx do
  gem 'rubysl'
end
```

### Your environment

* Ruby version: 3.0.2
* rspec-expectations version: HEAD

### Steps to reproduce

```
export USE_GIT_REPOS=1
rvm use 3.0.2
bundle
```

### Expected behavior

Bundle install should succeed.

### Actual behavior

See error above.

**Comment by JonRowe** [comment]
I'm not sure thats up with your local bundler, try ensuring its on the latest version, that platform should only be run on rubinius.

**Comment by dblock** [comment]
Btw, it looks similar to https://github.com/rubygems/bundler/issues/2774.
