### ISSUE TITLE
match_array is not documented

### ISSUE THREAD

**Issue by yskkin** [rspec/rspec-expectations#1369]
### Subject of the issue

https://relishapp.com/rspec/rspec-expectations/v/3-10/docs/built-in-matchers
match_array is not listed in "Built in matchers" headings.

It is explained in [`contain_exactly` matcher](https://relishapp.com/rspec/rspec-expectations/v/3-10/docs/built-in-matchers/contain-exactly-matcher) page, but is not navigatable.

How about change title to "array membership matchers"  or have independent page for match_array?

**Comment by pirj** [comment]
Changing the page name would break versionless links, e.g. https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/contain-exactly-matcher

`match_array` is almost an alias for `contains_exactly`. To my personal taste, `contain_exactly` is more intent revealing than `match_array` in most cases, though it may depend.

"array membership matchers" would also be confusing, as `include`/`end_with`/`start_with` also play a role of array membership matchers.

There are plenty of defined matchers that are not documented (see `alias_matcher` definitions [here](https://github.com/rspec/rspec-expectations/blob/77889b879be7bb72991d9f86ee63843d1aebbd71/lib/rspec/matchers.rb)), so our docs can see an improvement on this front.

Any PR is welcome.
