### ISSUE TITLE
Suggestion: Add :not_change and :not_raise_error matchers

### ISSUE THREAD

**Issue by unicornzero** [rspec/rspec-expectations#1378]
### Matchers!
My team and I use these all the time:
`expect { something }.to not_change(thing, :count)`
`expect { something }.to not_raise_error(SpecificError)`

It was only when mentioning `not_change` to someone today that I remembered these aren't available in vanilla rspec.

Would you be interested in adding `.not_change` and `.not_raise_error` as built-in matchers?

In case it's useful to someone else who comes across this, our project's setup for them is like this:
in `spec/support/not_helpers.rb`
```Ruby
RSpec::Matchers.define_negated_matcher :not_change, :change
RSpec::Matchers.define_negated_matcher :not_raise_error, :raise_error
```

**Comment by JonRowe** [comment]
Thanks for the suggestion but as you can see they are very simple to implement yourself and it becomes a never ending list if we start adding negated matchers for everything, but prehaps we can highlight this more as part of the install process that this is an option with a commented out snippet in the generated spec helper?
