### ISSUE TITLE
Include string encoding differences in failure messages

### ISSUE THREAD

**Issue by adfoster-r7** [rspec/rspec-expectations#1422]
### Your environment

* Ruby version: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-darwin20]
* rspec-expectations version: 3.12.3

### Steps to reproduce

Create the following test file:

```ruby
require 'spec_helper'

RSpec.describe 'Example' do
  it 'Example' do
    actual = 'abc'.encode('UTF-16LE')
    expected = 'abc'.force_encoding('ASCII-8BIT')

    expect(actual).to eql(expected)
  end
end
```

### Expected behavior

If the string's encoding is the reason for failure, this information could additionally be shown to the user:

```
Example F

  1) Example Example
     Failure/Error: expect(actual).to eq(expected)
     
       expected: #<Encoding:ASCII-8BIT> "abc"
            got: #<Encoding:UTF-16LE> "abc"
     
       (compared using ==)
```

### Actual behavior

There's no visual indication as to why the string comparison as failed:

```
Example F

  1) Example Example
     Failure/Error: expect(actual).to eq(expected)
     
       expected: "abc"
            got: "abc"
     
       (compared using ==)
```

**Comment by pirj** [comment]
Would you like to submit a PR to fix this?

**Comment by adfoster-r7** [comment]
I'll take a look :+1:
