### ISSUE TITLE
match_array not raising when comparing array-of-arrays to hash

### ISSUE THREAD

**Issue by unicornzero** [rspec/rspec-expectations#1435]
### Subject of the issue

`match_array` false-negative when comparing array-of-arrays to hash

I am using `match_array` to validate the contents of an array of arrays, regardless of order. My test is still passing when the actual result is a hash.

### Your environment
* Ruby version:
* rspec-expectations version:
```
    rspec (3.12.0)
    rspec-core (3.12.2)
    rspec-expectations (3.12.3)
    rspec-mocks (3.12.6)
    rspec-rails (6.0.3)
```
### Steps to reproduce
```ruby
    it "simple repro of match_array issue" do
      foo_string = "foo"
      fizz_string = "fizz"
      expected_array = [
        [foo_string, nil],
        [fizz_string, nil],
      ]
      actual_hash = {
        fizz_string => nil,
        foo_string => nil,
      }

      expect(expected_array).to match_array(expected_array.reverse)
      expect(actual_hash).not_to match_array(expected_array) # This errors
    end

    it "fuller repro of match_array issue" do
      foo_string = "foo"
      fizz_string = "fizz"
      foo_object = { "a" => 1, "b" => 1.4 }
      fizz_object = { "c" => "something" }
      expected_array = [
        [foo_string, foo_object],
        [fizz_string, fizz_object],
      ]
      actual_hash = {
        fizz_string => fizz_object,
        foo_string => foo_object,
      }

      expect(expected_array).to match_array(expected_array.reverse)
      expect(actual_hash).not_to match_array(expected_array) # This errors
    end
```

### Expected behavior
I expect to use `match_array` to verify that an array matches another array, regardless of sort order.
When using `match_array`, I expect it error on a hash to match an array of arrays.

I expect this to pass: `expect(actual_hash).not_to match_array(expected_array)`
I expect this to error: `expect(actual_hash).to match_array(expected_array)`

### Actual behavior
This is passing: `expect(actual_hash).to match_array(expected_array)`

**Comment by pirj** [comment]
Would you like to submit a pr?

**Comment by unicornzero** [comment]
@pirj Thanks for the quick reply! Do you have a good understanding of the root cause of this and how it might be addressed? I have limited bandwidth but I'm open to potentially contributing!

**Comment by pirj** [comment]
I beg my pardon for the initial conclusion. It turns out that `match_array`/`contains_exactly` [converts the actual into an array](https://github.com/rspec/rspec-expectations/blob/562d327cb951575d13db2a43b232c9ca1456ea6a/lib/rspec/matchers/built_in/contain_exactly.rb#L82) if it is not an array.
This deserves to be documented in a [feature spec](https://github.com/rspec/rspec-expectations/blob/562d327cb951575d13db2a43b232c9ca1456ea6a/features/built_in_matchers/contain_exactly.feature#L1).
It's unlikely that we want to change this behaviour.
You may `expect(actual).to be_an(Array).and match_array(expected_array)` if you intend to be stricter with types.

**Comment by unicornzero** [comment]
I'm sorry to hear that. My team and I find it very unexpected that these very different objects would be considered to match and that we'd have to write a custom matcher to work around this. This issue reduces my team's confidence in rspec matching, particularly with concern to whether to trust matchers like `match_array`.

We'd expect that the elements in the array must be equal (but in any order), but instead, it's mutating the objects in the array we're matching. Adding `be_an(Array).and ` to all our usage of `match_array` is problematic as it's a matcher we use very heavily.

Is it possible that the rspec team would be open to reevaluating this decision?

(thanks again for your prompt responses, @pirj !)

**Comment by JonRowe** [comment]
I'm on the fence about this, it is something the matcher has done for a very long time and is actually necessary when dealing with certain array like objects, in the end this matcher is not "equals array" or "be array" its "match" which in our semantics is array shaped objects. 

Its also faily easy to create an additional matcher for your own project as you point out:
```
def match_arrays_only(array)
  be_an(Array).and(contain_exactly(array))
end
```
