### ISSUE TITLE
Custom Matcher Used via alias_matcher Conflicts With ActiveSupport's `Object#with`

### ISSUE THREAD

**Issue by sshaw** [rspec/rspec-expectations#1437]
### Subject of the issue
Rails 7.1 added [`Object#with`](https://api.rubyonrails.org/classes/Object.html#method-i-with) which can conflict with custom matchers that define a `#with` method (`chain :with`) when used via an `alias_matcher`

### Your environment
* Ruby version: 3.1.3
* rspec-expectations version: 3.12.3

### Steps to reproduce

```rb
RSpec::Matchers.define :foo do
  match do |n|
    true
  end

  chain :with do |n|
  end
end

RSpec::Matchers.alias_matcher :bar, :foo

expect(1).to foo(1).with(2)
expect(1).to bar(1).with(2)
```

### Expected behavior

Neither assertion should raise an `ArgumentError`

### Actual behavior

The call to the aliased matcher (`bar`)'s `with` results in an argument error as the `#with` that is called is ActiveSupport's  `Object#with` no the custom  matchers

**Comment by JonRowe** [comment]
Can you try `main`?

**Comment by pirj** [comment]
Just for the reference:
 - https://github.com/rspec/rspec-expectations/pull/1434
 - https://github.com/rspec/rspec-mocks/pull/1534

**Comment by sshaw** [comment]
> Can you try main?

@JonRowe can't install it (with relative ease). Get various `3.13.0.pre` version not found. 

```rb
gem 'rspec-expectations', :github => "rspec/rspec-expectations", :branch => "main"
```
Gives me:
```
Could not find compatible versions\n\nBecause every version of rspec-expectations depends on rspec-support = 3.13.0.pre\n  and rspec-support = 3.13.0.pre could not be found in rubygems repository https://rubygems.org/ or installed locally,
```

```
gem 'rspec', :github => "rspec/rspec", :branch => "main"
```
Gives me similar error

**Comment by JonRowe** [comment]
```
%w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'main'
  end
```

**Comment by sshaw** [comment]
Thanks @JonRowe, looks to be working under `3.13.0.pre` 💪
