### ISSUE TITLE
Inconsistent markdown use causing documentation to not highlight syntax

### ISSUE THREAD

**Issue by threeplanetssoftware** [rspec/rspec-expectations#1446]
### Inconsistent markdown use causing documentation to not highlight syntax
Let me start by saying I am transitioning one of my packages to RSpec and I have become a quick fan of this work! I am by no means trying to grammar-snipe your work, I was looking up a particular use case and noticed that the formatting on the pages I was reading was inconsistent. I would love to help fix that, but I want to make sure I know what is intended and what is just a legacy commit.

I give two examples under the "Actual behavior" section below, but the bottom line is in this repo and the other rspec-* repositories, the documentation generated on https://rspec.info is not appropriately flagging code blocks for syntax highlighting. This is obviously NOT a blocking issue by any stretch, but for people new to the gem such as myself, it would be helpful to see examples with more syntax highlighting. 

The crux of this issue appears to be that code blocks are indicated in a few different ways:

- As double indented code blocks (such as on the rspec-expectations [main page](https://rspec.info/features/3-12/rspec-expectations/)). This does not render as code either on rspec.info or on [Github](https://github.com/rspec/rspec-expectations/blob/main/features/README.md).

https://github.com/rspec/rspec-expectations/blob/d0bb212c371fb6381cae2f9b86c4a025881f7ead/features/README.md?plain=1#L3-L10

- As double indented triple-quotes blocks (such as on the built-in matchers [include matcher](https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/include/) page). This renders as code on rspec.info.

https://github.com/rspec/rspec-expectations/blob/d0bb212c371fb6381cae2f9b86c4a025881f7ead/features/built_in_matchers/include.feature#L155-L173

 - As double indented triple-backticks (such as on the built-in matchers [include matcher](https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/include/) page). This does not render as code on rspec.info. 

https://github.com/rspec/rspec-expectations/blob/d0bb212c371fb6381cae2f9b86c4a025881f7ead/features/built_in_matchers/include.feature#L4-L18

Of note, other RSpec projects also have varying methods for producing code blocks, but this example from RSpec-Core's [clear-examples page](https://rspec.info/features/3-12/rspec-core/clear-examples/) makes me believe that the issue with formatting above for backticks is that it should be only indented once from the Feature class, not twice, since this does render as proper markdown on rspec.info.

https://github.com/rspec/rspec-core/blob/f8c8880dabd8f0544a6f91d8d4c857c1bd8df903/features/clear_examples.feature#L11-L20

All this to say: thank you for the great gems that have made adding tests to this specific package a dream. I would be willing to try to clean up these code blocks, but wanted to make sure I knew your ultimate goal. My assumption is that you want the code blocks to render properly on rpsec.info first and foremost and, ideally, also on Github for those that are Markdown pages. There are 36 examples of double-indented backticks, and 129 of double-indented quotes for opening code blocks in this repo, I haven't checked the other rspec repos, but that seems tackle-able. Just let me know what your intentions are!

### Your environment
* Ruby version: Not applicable, these are the web-based docs
* rspec-expectations version: 3.12 (and versions likely going back 12 years, based on git blame and #195 )

### Steps to reproduce
Point your browser at [this page](https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/include/).

### Expected behavior
When reading the documentation on https://rspec.info, I expected the code blocks to properly highlight Ruby syntax. 

### Actual behavior
Code blocks on https://rspec.info  inconsistently highlight the syntax. For example, on the [Include Matcher page ](https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/include/) the first two code blocks are not highlighted, the following four are. On the main [RSpec Expectations page](https://rspec.info/features/3-12/rspec-expectations/) none of the code blocks are highlighted.

**Comment by pirj** [comment]
Hi! Thanks for the detailed analysis. A PR is welcome. Please note that we use the feature files as both runnable specs and a source for our documentation.
You may need rspec.github.io and rspec-dev repos in your adventure.

**Comment by threeplanetssoftware** [comment]
Closing thanks to your merging #1447
