### ISSUE TITLE
have_attributes not showing a correct diff when used in a compound matcher

### ISSUE THREAD

**Issue by simonc** [rspec/rspec-expectations#1448]
### Subject of the issue

When the `have_attributes` matcher is used as part of a compound matcher, its `actual` method is not used when building the diff message, resulting in a diff that is not showing the non-matching values. It seems that within a compound matcher the `BaseMatcher#actual` method is used.

### Your environment

* Ruby version: 2.7
* rspec-expectations version: 3.12

### Steps to reproduce

Call the `have_attributes` matcher within a compound matcher.

```ruby
RSpec.describe 'A simple struct' do
  it 'has an id' do
    obj = Struct.new(:id).new(id: 1)
    expect(obj).to be_a(Struct).and have_attributes(id: 2)
  end
end
```

### Expected behavior

The error message should be

```
Failure/Error: expect(obj).to be_a(Struct).and have_attributes(id: 2)

  expected #<struct id=1> to have attributes {:id => 2} but had attributes {:id => 1}
  Diff for (have attributes {:id => 2}):
  @@ -1 +1 @@
  -:id => 2,
  +:id => 1,
```

### Actual behavior

The actual message is

```
Failure/Error: expect(obj).to be_a(Struct).and have_attributes(id: 2)

  expected #<struct id=1> to have attributes {:id => 2} but had attributes {:id => 1}
  Diff for (have attributes {:id => 2}):
  @@ -1 +1 @@
  -:id => 2,
  +"#<struct id=1>"
```

**Comment by pirj** [comment]
> its `actual` method is not used when building the diff message

Can you please check what happens if you change this to it se the `actual`?

before you dive too deep, can you please check if https://github.com/rspec/rspec-expectations/pull/1440 fixes your case?

**Comment by simonc** [comment]
Hey @pirj! I upgraded to 3.13 and the issue does seem to be fixed. Thank you! 😊
