### ISSUE TITLE
Possible issue in the documentation for syntax-configuration

### ISSUE THREAD

**Issue by Zain-Bin-Arshad** [rspec/rspec-expectations#1453]
### Missing documentation issue in syntax-configuration

If you look at the documentation for syntax-configuration both v3.13 & v3.12, there is no code for the `spec_helper`, but this might be intentional or not?

https://github.com/rspec/rspec-expectations/blob/e859d358fff504f9132cb9eaa9b33765e73fc187/features/syntax_configuration.feature#L41-L47

<img width="697" alt="image" src="https://github.com/rspec/rspec-expectations/assets/49767636/ad0ee973-f390-4bbe-aa7b-79853a3fc93d">

**Comment by pirj** [comment]
This is intentional, as it says “by default”
