### ISSUE TITLE
Use `RSpec.warning` instead of `::Kernel.warn`

### ISSUE THREAD

**Issue by runephilosof-abtion** [rspec/rspec-expectations#1461]
I expected this to raise an error when `Rspec.configure { |config| config.raise_on_warning = true }`

https://github.com/rspec/rspec-expectations/blob/0139c22a62624849c09dd33980554215e63ab9eb/lib/rspec/expectations/handler.rb#L7-L11

**Comment by pirj** [comment]
Nice catch, @runephilosof-abtion . A PR is welcome.
