### ISSUE TITLE
be_unprocessable_entity matcher not working with rack 3.1.x

### ISSUE THREAD

**Issue by Aqualon** [rspec/rspec-expectations#1464]
### Subject of the issue
Not sure where this fits, but I have an issue in a controller spec that should verify a 422 response.
```
it 'returns 422' do
  post :create, params: share_params
  expect(response).to be_unprocessable_entity
end
```
With rack 3.0.11 this works fine and via byebug found out that `be_unprocessable_entity` comes from rspec-expecations DSL
```
(byebug) be_unprocessable_entity
#<RSpec::Matchers::DSL::Matcher be_unprocessable_entity>
(byebug) method(:be_unprocessable_entity).source_location
["/Users/bruno.escherl/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rspec-expectations-3.13.1/lib/rspec/matchers/dsl.rb", 75]
```
Updating to rack 3.1.3 I get this error
```
Failure/Error: expect(response).to be_unprocessable_entity
       expected #<ActionDispatch::TestResponse:0x000000013573d530 @mon_data=#<Monitor:0x0000000135af03d0>, @mon_data_...equest POST "http://test.host/rest/activities/legacy/users/2322146568/activities.json" for 0.0.0.0>> to respond to `unprocessable_entity?
```
and checked again and this time get
```
(byebug) be_unprocessable_entity
#<RSpec::Matchers::BuiltIn::BePredicate:0x00000001317d6130 @method_name=:be_unprocessable_entity, @args=[], @block=nil>
(byebug) method(:be_unprocessable_entity).source_location
nil
```
So somehow updating rack causes `be_unprocessable_entity` to be something different?

I can change the expectation to `expect(response).to be_unprocessable` which still works, but would be curious what is up there?

### Your environment
* Ruby version: 3.3.3
* rspec-expectations version: 3.13.1
* rails: 7.1.3.4

**Comment by pirj** [comment]
> be_unprocessable_entity comes from rspec-expecations DSL

It’s a generic [predicate matcher](https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/predicates/), and it delegates to the underlying object.

The failure you’re seeing is most certainly due to a change in the rack API. You can read more about this [here](https://github.com/rspec/rspec-rails/issues/2763#issuecomment-2172602162). In a minor version update you may still see [breaking changes like this](https://github.com/rack/rack/blob/main/CHANGELOG.md#310---2024-06-11).

**Comment by Aqualon** [comment]
Thanks, seems to have been this change: https://github.com/rack/rack/pull/2137. 422s were renamed from unprocessable_entity to unprocessable_content leading to the observed behavior.

**Comment by pirj** [comment]
@Aqualon What surprises me is how `be_unprocessable_entity` used to work. I can only see just the [unprocessable?](https://github.com/rack/rack/blob/db844cb978bd2a52369205de481c80c7f69f3489/lib/rack/response.rb#L198) defined, and this hasn’t changed for a decade.

I was about to complain in that Rack PR that a predicate method has been removed/renamed, but I don’t see a clear trace where this happened.
Would you like to dig a bit deeper into this?

I don’t think that the Rack guys intended to break specs i a minor version except for printing a warning.

**Comment by pirj** [comment]
Maybe some metaprogramming in Rails that builds on too of Rack?

**Comment by pirj** [comment]
This is not the first time this happens, see [Rails 4.2 notes](https://guides.rubyonrails.org/4_2_release_notes.html#changed-status-option-symbols-for-render). Was rack pinned in Rails back then?

**Comment by Aqualon** [comment]
I figured it out, the `be_unprocessable_entity` matcher was defined in our own codebase using
```
Rack::Utils::SYMBOL_TO_STATUS_CODE.each_pair do |symbol, status_code|
  RSpec::Matchers.define :"be_#{symbol}" do
    match do |actual|
      actual.present? && actual.code.to_s == status_code.to_s
    end
    failure_message do |actual|
      "expected response code to be #{status_code}, but was #{actual.code}"
    end
  end
end
```
and since `Rack::Utils::SYMBOL_TO_STATUS_CODE` now contains `unprocessable_content: 422` instead of `unprocessable_entity: 422`, we don't get the matcher we used anymore.
