### ISSUE TITLE
`Has` doesn't respect keyword arguments

### ISSUE THREAD

**Issue by romanbsd** [rspec/rspec-expectations#1480]
### Subject of the issue
When working with capybara, the following fails:
```ruby
expect(page).to have_field('object_title', with: 'some name')
```
### Your environment
* Ruby version: 3.2.4
* rspec-expectations version: 3.13.1

### Steps to reproduce
Using capybara do `expect(page).to have_field('object_title', with: 'some name')`

### Expected behavior
It delegates to `has_field?('object_title', with: 'some name')`
### Actual behavior
It calls `has_field?('object_title', { with: 'some name' })`

I made a following monkey patch to workaround the problem:
```ruby
module RSpec
  module Matchers
    module BuiltIn
      class Has
        private

        def predicate_result
          if @args.last.is_a?(Hash)
            # Extract the last element of @args and pass it as keyword arguments
            args_without_last = @args[0...-1]
            last_hash = @args.last
            actual.__send__(predicate_method_name, *args_without_last, **last_hash, &@block)
          else
            # Fallback to the default behavior if there's no hash at the end of @args
            actual.__send__(predicate_method_name, *@args, &@block)
          end
        end
      end
    end
  end
end
```

**Comment by romanbsd** [comment]
Interestingly enough, I cannot reproduce is in a simple case. The capybara code (as I checked in debugger callstack) is from 
https://github.com/teamcapybara/capybara/blob/master/lib/capybara/session.rb#L774 and then https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/matchers.rb#L421 
However, for this simple test case it passes:
```ruby
class TestModel
  class Internal
    def has_field?(locator = nil, **options, &optional_filter_block)
      true
    end
  end

  def initialize
    @internal = Internal.new
  end

  def has_field?(...)
    @internal.has_field?(...)
  end
end

RSpec.describe TestModel, type: :model do
  let(:instance) { described_class.new }

  it 'passes keyword arguments' do
    expect(instance).to have_field('secret', with: 'something')
  end
end
```
I'm puzzled.

**Comment by JonRowe** [comment]
I did some more investigation and at a guess, whats happening is that the capture of the arguments up in the `DynamicPrediate` parent class is somehow being overriden, so that these hashes are not being marked as ruby2_keywords hashes, by default we use:
```
        def initialize(method_name, *args, &block)
          @method_name, @args, @block = method_name, args, block
        end
        ruby2_keywords :initialize if respond_to?(:ruby2_keywords, true)
```

Which captures the keywords as the hash but marks them as ruby2 style which allows the splat to work.

So we're going to need some more information from you as to what else you have that might be monkey patching over the top, can you check the source location of `RSpec::Matchers::BuiltIn::DynamicMatcher#initialize` in your broken suite?

**Comment by romanbsd** [comment]
I'm having hard time finding the source location:
```
(byebug) RSpec::Matchers::BuiltIn::DynamicPredicate.method(:initialize).source_location
nil
(byebug) RSpec::Matchers::BuiltIn::DynamicPredicate.method(:new).source_location
nil
```

**Comment by romanbsd** [comment]
`.rvm/gems/ruby-3.2.4/gems/rspec-expectations-3.13.1/lib/rspec/matchers/built_in/has.rb", 10`

**Comment by JonRowe** [comment]
In your monkey patch, what is the value of `Hash.ruby2_keywords_hash(last_hash)`

**Comment by romanbsd** [comment]
it's for example:
```ruby
{:with=>"Beta experiment"}
```

**Comment by pirj** [comment]
I think what is interesting is the result of the predicate method Hash.ruby2_keywords_hash?(last_hash) which would be true or false.

What tools do you use for debugging, @romanbsd ?

**Comment by JonRowe** [comment]
Sorry yes thats what I meant

**Comment by romanbsd** [comment]
I use byebug, but can try anything else.

**Comment by pirj** [comment]
Can you please check what Hash.ruby2_keywords_hash?(last_hash) returns?

**Comment by romanbsd** [comment]
```
(byebug) Hash.ruby2_keywords_hash?(last_hash)
false
```

**Comment by JonRowe** [comment]
Ok I think this is likely something else interferring with the ruby2 keyword hash stuff then, in our vanilla implementation it returns true and everything works as expected. I'd recommend trying to eliminate things from your stack (temporarily) until you find what gem / code is interfering with this.

I'm closing this for now but if you can come up with a reproduction please re-open.

**Comment by romanbsd** [comment]
Any idea what it could be, or what code patterns should I search for?

**Comment by JonRowe** [comment]
You could try searching your code/dependencies for things monkey patching has's initializer,

**Comment by romanbsd** [comment]
The Has initializer is not monkey patched as far as I can tell. Is there some mechanism of ruby2_keywords that can be in effect here? How some external library can have an effect on this code?

**Comment by JonRowe** [comment]
Anything which intefers with the vanilla behaviour of the ruby2_keywords flag or our class and its methods could be at fault, you should also search for anything thats reopening the class (including er including itself into the class form example).

As I mentioned eliminating one gem at a time might be the best way to debug this
