### ISSUE TITLE
Strict negated predicate matchers

### ISSUE THREAD

**Issue by marcandre** [rspec/rspec-expectations#1487]
### Negated Predicate Matchers should be strict.

I just realized that negated predicate matchers are not strict, i.e. `expect(something).not_to be_foo` will pass if `foo?` returns `nil`. We have a bunch of these mistakes in `rubocop` and [in `rubocop-ast`](https://github.com/rubocop/rubocop-ast/issues/319).

I believe it should fail. To be correct, methods ending with `?` should typically not return `nil`. It's quite easy to return `nil` without wanting to. It's also easy to not realize a method if returning `nil` (e.g. `if x.foo?`), but sometimes the `nil` and `false` might be treated differently (often without meaning too) and subtle bugs can be introduced.

It may be advisable for compatibility's sake to put that under a flag. I believe that flag should default to strict although that may have to wait for a major version (if ever?).

Note that the only other choice given to rspec [user is quite ugly](https://github.com/rubocop/rubocop-rspec/issues/1966), in particular:

```
# currently not strict enough version
it_is_expected.not_to be_foo
# correct version
expect(subject.foo?).to be false
```

### Your environment
* rspec-expectations version: 3.13.3

**Comment by JonRowe** [comment]
Can you double check you've turned on the existing strict predicate check? 
e.g `RSpec::Expectations.configuration.strict_predicate_matchers = false`

**Comment by marcandre** [comment]
I have such a bad memory 🤦‍♂️
https://github.com/rspec/rspec-expectations/issues/1102
