### ISSUE TITLE
DEPRECATION warning due to RSpec matchers (from rspec-expectations)

### ISSUE THREAD

**Issue by likethesky** [rspec/rspec-expectations#286]
I am currently getting the following when I bundle update everything on a gem I build:

```
DEPRECATION: `expect { }.not_to raise_error(SpecificErrorClass)` is deprecated. Use `expect { }.not_to raise_error()` instead. Called from /Users/me/.rvm/gems/ruby-1.9.3-p374@wize_thrift/gems/rspec-expectations-2.14.0/lib/rspec/matchers/built_in/raise_error.rb:53:in `does_not_match?'.
```

I had just changed a 'mock' to 'double' as well, in case that helps (the fact that I'm using doubles)...  I assume 2.14.0 is the latest rspec I should be using, but that you simply aren't eating your own dogfood yet (i.e. fixing these deprecation warnings yet)?  So I should just ignore them for now?  Or ... ?  Thanks!

**Comment by williamcodes** [comment]
I was also just confused by this the same way @adamgotterer was. The message is not clear. It makes it sound like `raise_error` never takes arguments. It says nothing about the difference between using it with `to` and `not_to`.

**Comment by JonRowe** [comment]
Because it's only triggered when you use `not_to` so it's pretty obviously

**Comment by williamcodes** [comment]
That wasn't obvious to me or to the previous commenter, and I would wager it's not obvious to a lot of other people as well. It is surprising for `to` and `not_to` to result in different types of errors. I've been using RSpec for a long time and this is the first time I've ever run into an issue like that.

**Comment by chrisarcand** [comment]
FWIW I remember the first time I saw this deprecation, and it seemed very clear to me. Why would `not_to` be used if that wasn't specifically what the message was getting at?

Fortunately, if you do not believe the message is clear enough you are welcome to create a pull request to suggest how to make it succinctly clearer instead of wagging your finger at the decision made for a rather subjective issue created over two years ago.

**Comment by williamcodes** [comment]
If I make the pull request, will it be merged? If so, I will happily create one.

**Comment by myronmarston** [comment]
> If I make the pull request, will it be merged? If so, I will happily create one.

It depends on the suggested wording changed.

**Comment by williamcodes** [comment]
`expect { }.not_to raise_error(SpecificErrorClass)` is deprecated. Use `expect { }.not_to raise_error() or expect { }.to raise_error(DifferentSpecificErrorClass)`

**Comment by myronmarston** [comment]
:+1: That sounds great.

**Comment by williamcodes** [comment]
Okay cool, I'll link here to the PR.

**Comment by mikegee** [comment]
I can sympathize with your confusion on this. We can't know how many other folks were also confused, but didn't bring it up.

Thanks for volunteering to change the wording. Hopefully that clears it up for everyone going forward.
