### ISSUE TITLE
obj.should != something doesn't work properly

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-expectations#33]
A coworker of mine who has never used RSpec but is interested in it pointed me to [this code snippet](http://zenspider.pastebin.com/9QknBh7M) from zenspider:

<pre>
describe Integer do
  it "sucks" do
    10.should == 10
    10.should != 10
  end
end
</pre>

This spec passes.  I know that the recommended RSpec way is to use `should_not ==` rather than `should !=` but this is definitely very confusing behavior.

I was going to go fix it, but this is such a simple case that I'm surprised it hasn't been addressed before, and it made me wonder if there's a specific reason it's not supported.  If we're only going to support `should_not ==` then we should at least give the user an error or warning when they use `should !=` as this is very confusing behavior.

**Comment by taw** [comment]
> _That will likely change in the future as >= 1.9 adoption increases._

Well, nobody uses 1.8 any more and  `a.should == b` and `a.should != b` look far better than any alternative syntax, so maybe time to add them back?

**Comment by myronmarston** [comment]
@taw that ship has sailed, given the `should` syntax, while still there, is no longer the "main" syntax, and `expect` (intentionally) does not support direct operator usage like `expect(x).to == y`.
