### ISSUE TITLE
Unexpected target/handler behavior with respect to blocks

### ISSUE THREAD

**Issue by laserlemon** [rspec/rspec-expectations#536]
I would expect the following two assertions to behave similarly, at least to the point that they would both pass, but they don't.

``` ruby
expect("foo").to eq("foo")
expect { "foo" }.to eq("foo")
```

In the same vein, I would expect these two assertions to behave differently but they are identical.

``` ruby
expect { "foo" }.to eq("foo")
expect(proc { "foo" }).to eq("foo")
```

It seems that the handoff between the target and the handler could be improved by somehow providing context/insight into whether the incoming "actual" value is something dynamic to be evaluated (a given block) or a static value (even a proc) given as an argument.

I'm hoping it's worth a conversation. Thank you!

**Comment by mixelpixel** [comment]
How does one get the rspec matcher to implement `supports_block_expectations?`?

**Comment by myronmarston** [comment]
> How does one get the rspec matcher to implement `supports_block_expectations?`?

Just define it as a method inside your matcher definition, e.g.

``` ruby
class MyMatcher
  def supports_block_expectations?
    true
  end

  # ...
end
```

If you are using the matcher definition DSL, you can just call [`supports_block_expectations`](http://rspec.info/documentation/3.5/rspec-expectations/RSpec/Matchers/DSL/Macros.html#supports_block_expectations-instance_method):

``` ruby
RSpec::Matchers.define :my_matcher do
  supports_block_expectations

  # ..
end
```

**Comment by mixelpixel** [comment]
hi @myronmarston , thanks for the reply - I'm fairly new to Ruby and rspec. I really appreciate the helpful info!

**Comment by nicktime** [comment]
@myronmarston 
```
You must pass an argument rather than a block to use the provided matcher (eq "foo"),
or the matcher must implement `supports_block_expectations?`.
```
is a really confusing message. It made me think `eq` got a block but needs an argument. Couldn't figure it out until googled up this issue.

**Comment by myronmarston** [comment]
@nicktime what is your code snippet that generated that message?

**Comment by nicktime** [comment]
@myronmarston https://github.com/nicktime/tomograph/blob/add-json-support/spec/lib/tomograph/api_blueprint/yaml_spec.rb#L70
when put in a curly braces like this
```
      expect { subject.to_tomogram.map(&:to_hash) }.to eq(tomogram_hash)
```
So I was thinking the problem is with `tomogram_hash`.

**Comment by JonRowe** [comment]
Do you have a suggested wording improvement? It means `expect` was given a block but `eg(tomogram_hash)` needs a value

**Comment by nicktime** [comment]
I'd suggest
```
You must pass an argument rather than a block to `expect` to use the provided matcher (eq "foo"),
or the matcher must implement `supports_block_expectations?`.
```
Confusion is only about which method it is that can't take a block, otherwise message is clear.

**Comment by JonRowe** [comment]
Thanks :)
