### ISSUE TITLE
level by level diff of unequal nested data structures. srsly.

### ISSUE THREAD

**Issue by dchelimsky** [rspec/rspec-expectations#54]
Per http://twitter.com/mcmire/status/19288568174219266.

**Comment by jfelchner** [comment]
@myronmarston I just found this and not being able to easily see the difference between large API responses that we're testing is a nightmare for us currently.

I'm definitely interested in taking a look at this.

If you just want to give me an idea of what you'd like the API to look like and which files I need to look at to get me started and then I'll try to take it the rest of the way.

**Comment by myronmarston** [comment]
I think there are two routes we could take with the API:

* The custom differ would be responsible for providing the actual full diff.
* The custom differ would be more of an "inspector" that would convert the expected and actual data structures into some kind of line-by-line string form, and then RSpec would pass that to `Diff:::LCS` to have it do a line-by-line textual diff.  Essentially, the "inspector" would be like `Object#inspect` except it would be diff aware and would produce string output that diffs well.

Which would you prefer?

**Comment by jfelchner** [comment]
@myronmarston I feel like `Diff::LCS` is a great diffing tool, so if we can find a solution that lets it do what it's good at, that that would be preferable.

The one major difficulty that I can see is the sub matchers and how those would be displayed.

Example:

```ruby
expect(
  {
    a: match(/[fb]oo/),
    b: 'yo',
  }
).to eql(
  {
    a: 'foo',
    b: 'YO!',
  }
)
```

So that doesn't match, but we wouldn't want to diff of `a` to be shown.  Only the `b` line doesn't match.

Although I'd love to just be able to give `Diff::LCS` a couple strings and rely on it to do its job, that may not be possible.

Thoughts?

**Comment by mcmire** [comment]
@jfelchner I never finished it, but check out the project I created for ideas and challenges: http://github.com/mcmire/super_diff

**Comment by jfelchner** [comment]
@mcmire cool I'll take a look.  Any thoughts on the specific regex example I gave above?  Where there are sub matchers involved?

**Comment by mcmire** [comment]
In that case it would say:

```
Error: Hashes of same size but with differing elements.

Expected: {:a => match(/[fb]oo/)), :b => 'yo'}
Got: {:a => 'foo', :b => 'YO!'}

Details:
- *[:b]: Differing strings.
  - Expected: "yo"
  - Got: "YO!"
```

**Comment by jfelchner** [comment]
Hmmmmm... I'll look more into the gym.

**Comment by mcmire** [comment]
Cool. And by the way it does hook into Diff::LCS: https://github.com/mcmire/super_diff/blob/master/lib/super_diff/recursive_differ.rb

**Comment by bunyk** [comment]
While I don't know how to use your differ in our tests (I'm not a ruby dev), nicely formatted failures could be achieved by writing specs like:

```ruby
requre 'json'
...
    expect(JSON.pretty_generate(actual)).to eq(JSON.pretty_generate(expected))
...
```
Just in case someone is looking for something like this.

**Comment by jponc** [comment]
https://github.com/mcmire/super_diff

@mcmire it'll be great if this gets merged to rspec-expectations, good stuff man 👍

**Comment by mcmire** [comment]
@jponc Thanks! I started rewriting this recently as you can see. It works okay — right now I'm sort of testing it out on an existing app. Once I have it working well I'll make a PR!

**Comment by jfelchner** [comment]
If the option is there, I’d like to see this library be able to output a structure of only what is different between two hashes. Is that in the plans?

**Comment by mcmire** [comment]
@jfelchner Are you talking about a data structure that represents a diff or a string that represents a diff?

**Comment by jfelchner** [comment]
A data structure. So:

```ruby
{
  foo: ‘bar’,
  baz: 2,
}

# vs

{
  foo: ‘baz’,
  baz: 2,
  wiz: ‘ard’
}

# would output something like:

{
  foo: ‘baz’,
  wiz: ‘ard’
}
```

**Comment by jfelchner** [comment]
@JonRowe I was just talking about allowing this gem to be able to do this. Outside of usage in RSpec. Not that this would be the format I’d want to see in specs. 

The format is want in a spec run is what you’re proposing.

**Comment by mcmire** [comment]
@jfelchner That's not one of the goals of the gem, but if you want to open an issue so you can provide more context and we can discuss it there then I'm all ears!
