### ISSUE TITLE
Waiting matcher

### ISSUE THREAD

**Issue by abotalov** [rspec/rspec-expectations#580]
I'd like to propose to add a matcher that will retry given block until it will match all other matchers or time expired.

The matcher is applied to other matchers (like Compound).

Usage examples:

``` ruby
expect { find('#id')[:class] }.to eq('some_class').during(3, every: 0.2)
expect { response.headers }.to include({'Content-type' => 'text/html'}).and include({'Content-Encoding' => 'gzip'}).during(2)
```

Currently users should use some gem like [retriable](https://github.com/kamui/retriable) or some other form of `wait_until` like:

``` ruby
wait_until(3) { find('#id')[:class] == 'some_class' }
Retriable.retriable :on => Timeout::Error, :tries => 3, :interval => 1 do
  find('#id')[:class] == 'some_class'
end
```

So error messages don't tell what was the actual value of e.g. `find('#id')[:class]` in those cases. I think handling this issue at RSpec side instead of adding additional waiting matchers to e.g. Capybara would be a more proper solution since its not webapp-only problem.

Please tell if you think the idea is good or not.

**Comment by bootstraponline** [comment]
There's also [wait_for](https://github.com/laserlemon/rspec-wait) via the rspec-wait gem which is cool.
