### ISSUE TITLE
Extended `Time`/`BigDecimal` logic for all diff output

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-expectations#611]
This comes out of rspec/rspec-core#1649. [Per Myron](https://github.com/rspec/rspec-core/issues/1649#issuecomment-50046730):

> we should extend the `Time`/`BigDecimal` logic we put in the `eq` matcher so that it is used as the output for all diffs:
>
> https://github.com/rspec/rspec-expectations/blob/099d8821b/lib/rspec/matchers/built_in/eq.rb#L38-L48

**Comment by myronmarston** [comment]
So there's another issue here...the improvements we made only apply to when a time object is the direct thing being compared, and not to when the time object is embedded in an array or hash data structure.  In that case, you still get the same confusing output as before. For example, see this tweet from @mhenrixon:

https://twitter.com/mhenrixon/status/552857545397010432

![twitter-failure](https://cloud.githubusercontent.com/assets/49391/5650243/7e0a81c8-9651-11e4-8cee-b7b94ad8408e.png)

Ideally, the improved output would apply to these objects where ever they appear in any common data structure.
