### ISSUE TITLE
A failing `include` on arrays should diff their content

### ISSUE THREAD

**Issue by gioele** [rspec/rspec-expectations#676]
Tests that compare arrays with `include` do not report a useful diff because they compare the complete arrays instead of their contents.

For example these test

```
it "contains all the needed values" do
    generated_values = [:foo, :quuz, :foobar]
    target_values = [:bar, :quuz]

    generated_values.should include(*target_values)
end
```

will report

```
Failure/Error: generated_values.should include(*target_values)
  expected [:foo, :quuz, :foobar] to include :bar and :quuz
  Diff:
  @@ -1,2 +1,2 @@
  -[:bar, :quuz]
  +[:foo, :quuz, :foobar]
```

For longer values this is completely unhelpful. It would be better to focus on the missing values, like

```
Failure/Error: generated_values.should include(*target_values)
  the expected values were: :bar and :quuz
  actual array contained: [:foo, :quuz, :foobar]
  the missing values were: :bar
```

similarly to what is done for `match_array`.

**Comment by laurenfackler** [comment]
One alternative would be to diff the arrays, like this:

```
expect(params - whitelist).to be_empty
```

That way, you'll get just the missing values in the error output:

```
expected `["created_by_ip_address"].empty?` to return true, got false
```

Note that order matters; `params - whitelist` versus `whitelist - params` will produce different output. I wanted to make sure that everything in `params` was also in the `whitelist`.
