### ISSUE TITLE
Documentation example (feature spec) on using a subject in a custom matcher or extension library

### ISSUE THREAD

**Issue by oveddan** [rspec/rspec-expectations#705]
The rspec-core documentation, in the [explicit subject](https://www.relishapp.com/rspec/rspec-core/v/3-1/docs/subject/explicit-subject) section, mentions that:

> Note that while the examples below demonstrate how the subject helper can be used
as a user-facing concept, we recommend that you reserve it for support of custom
matchers and/or extension libraries that hide its use from examples.

It would be great if there was an example in the [custom matcher documentation](https://www.relishapp.com/rspec/rspec-expectations/v/2-4/docs/custom-matchers) that shows a use case with a custom matcher leveraging an explicit subject.

**Comment by JonRowe** [comment]
Closing because I don't feel this would be a useful addition to the documentation.
