### ISSUE TITLE
Allow a custom message for satisfy expectations

### ISSUE THREAD

**Issue by postmodern** [rspec/rspec-expectations#719]
I noticed that "satisfy block" description is hardcoded into the `Satisfy` matcher class. It should be possible to override the default message with a more meaningful one.

    satisfy("are even numbers") { |e| e % 2 == 0 }

I currently modified `Satisfy` and `#satisfy` to allow this.

### satisfy.rb

      class Satisfy < RSpec::Matchers::BuiltIn::Satisfy

        # @api private
        # @return [String]
        attr_reader :description

        def initialize(description='satify block',&block)
          super(&block)

          @description = description
        end

        # @api private
        # @return [String]
        def failure_message
          "expected #{@actual} to #{@description}"
        end

        # @api private
        # @return [String]
        def failure_message_when_negated
          "expected #{@actual} not to #{@description}"
        end

      end

**Comment by myronmarston** [comment]
I like it. Want to submit a PR?

**Comment by postmodern** [comment]
Sure, which branch should I pull from? It will take a while to write a test for this new behavior.

**Comment by JonRowe** [comment]
`master`
