### ISSUE TITLE
anything() regression in rspec-3

### ISSUE THREAD

**Issue by kellyfelkins** [rspec/rspec-expectations#723]
```
      expect({:a => 1}).to eq({:a => anything})
```

This passes in rspec 2 but fails in 3 with

```
expected: {:a=>#<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007faa02d3f320>}
     got: {:a=>1}

(compared using ==)

Diff:
@@ -1,2 +1,2 @@
-:a => #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007faa02d3f320>,
+:a => 1,
```

I'm not sure this was ever a valid use of anything(), which is implemented in rspec-mocks and appears to be intended for argument matching.

That said, the fact that there are tests using anything for hash_including indicates that its not just for arguments.

I don't think hash_including meets my needs because I don't want to specify the minimum hash. I want to say that the expected hash is the same as the hash, but that I don't know some of the expected values.

**Comment by kellyfelkins** [comment]
BTW I investigated a pull request, but its not clear to me if this belongs in expectactions/matchers or mocks. It seems like it should be in expectations/matchers, but is currently implemented in mocks.

**Comment by kellyfelkins** [comment]
I hate to just report problems. Please provide some guidance and I'll create a pull request.

**Comment by myronmarston** [comment]
The RSpec 3 behavior is intended. The eq matched is documented to have exact == semantics and those two hashes are not exactly equal.

Instead, use the 'match' matcher -- it allows matchers to be sibstituted for hash values.

**Comment by kellyfelkins** [comment]
Will do. Thank you.
