### ISSUE TITLE
contain_exactly strange behavior with Date and DateTime

### ISSUE THREAD

**Issue by kaelumania** [rspec/rspec-expectations#724]
I found a strange behavior when using contain_exactly with Date and DateTime objects.
The following test fails:
```
it 'should not match DateTime with Date', :focus do
      h = Hash.new
      h[DateTime.new(2015,1,1,12,0,0)] = 1
      expect(h.keys).not_to contain_exactly(Date.new(2015,1,1))
    end
```
I could track down the reason to the [FuzzyMatcher](https://www.omniref.com/ruby/gems/rspec-support/3.0.1/symbols/RSpec::Support::FuzzyMatcher#line=16) module. Where the elements are compared using the `===` operator, which is defined to compare only the day on Date and DateTime.

**Comment by JonRowe** [comment]
You can't compare Dates with DateTimes like that, so the matcher won't work properly.
