### ISSUE TITLE
respond_to_missing? isn't defined in RSpec::Matchers

### ISSUE THREAD

**Issue by abotalov** [rspec/rspec-expectations#745]
Currently `method_missing` is defined in RSpec::Matchers (https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers.rb#L919-L928) but `respond_to_missing?` isn't defined. It looks like because of it checking for `respond_to?` doesn't work.

**Comment by myronmarston** [comment]
Huh, you're right.  I'm surprised we forgot to do that!

Want to work up a PR to add it?  The one suggestion I have is to be sure to define `respond_to?` on 1.8.7 rather than `respond_to_missing?` since `respond_to_missing?` wasn't around in 1.8.

**Comment by abotalov** [comment]
Where should I put tests for it?

**Comment by myronmarston** [comment]
Since it's missing from the `RSpec::Matchers` module, how about it's spec?

https://github.com/rspec/rspec-expectations/blob/master/spec/rspec/matchers_spec.rb
