### ISSUE TITLE
reverse `include` matcher?

### ISSUE THREAD

**Issue by eostrom** [rspec/rspec-expectations#760]
When a function's output is nondeterministic, I sometimes see developers write a spec like:

```ruby
expect(result).to eq :a || :b
```

which of course doesn't do what they expect, and eventually they usually settle on `include`:

```ruby
expect([:a, :b]).to include result
```

which works, but subverts the standard pattern of `expect(actual).to match(expected)`.

Would a PR for a `be_included_in` matcher be welcome?

```ruby
expect(result).to be_included_in([:a, :b])
```

(Apologies if this has been discussed and rejected; I looked around a bit but didn't find anything but a few lonely gists.)

**Comment by myronmarston** [comment]
This use case is why we added support for compound matchers in RSpec 3:

``` ruby
expect(result).to eq(:a).or eq(:b)
```

# or:

``` ruby
expect(result).to eq(:a) | eq(:b)
```

With `or` in place, I'm not convinced `be_included_in` is necessary.  Thoughts?

BTW, if you want to read more about the new compound matchers in RSpec 3, it was announced here:

http://rspec.info/blog/2014/01/new-in-rspec-3-composable-matchers/

**Comment by eostrom** [comment]
Thanks, that is great – I'd read about compound matchers but hadn't made the connection with this use case.

I think I've had other tests where `and` and `or` would be unwieldy – where there's a longer list of potential values, say, or a range. But I don't have those at hand, and I can't say whether they are otherwise justifiable.

I'd say close this, and at least the concept will still be here if I or someone else wants to argue for it in the future.

**Comment by myronmarston** [comment]
With a longer list, you could do something like:

``` ruby
def be_included_in(first_value, *rest)
  rest.inject(eq(first_value)) do |matcher, value|
    matcher.or eq(value)
  end
end
```

**Comment by dpisarewski** [comment]
I can't imagine how compound matchers could work in many non-trivial cases, like this:

```ruby
let(:urls) { %w[http://example.com/example.jpg http://example.com/example2.jpg] }

it 'sets proper urls on download files' do
  create_downloads
  expect(download_files).to all(have_attributes(url: be_included_in(urls)))
end
```

**Comment by myronmarston** [comment]
``` ruby
it 'sets proper urls on download files' do
  create_downloads
  expect(download_files).to all(have_attributes(url:
    eq('http://example.com/example.jpg').or eq('http://example.com/example2.jpg')
  ))
end
```

Or:

``` ruby
it 'sets proper urls on download files' do
  create_downloads
  expect(download_files).to all(have_attributes(url: match(~r|\Ahttp://example\.com/example2?\.jpg\z|)))
end
```

**Comment by dpisarewski** [comment]
That was the point. I want to reference an arbitrary collection instead of listing all values in the matcher.

**Comment by trejkaz** [comment]
We have an existing custom matcher:

```
matcher :item_processed_info do |state, stage, count, items|
  match do |info|
    info.state == state       &&
    info.stage == stage       &&
    info.stage_count == count &&
    info.failure.nil?         &&
    items.include?(info.item)
  end
end
```

I half wondered whether we could rewrite it like...

```
def item_processed_info(state, stage, count, items)
  have_attributes(state: state,
                  stage: stage,
                  stage_count: count,
                  failure: nil,
                  item: whatever_matcher_matches_one_item_from(items))
end
```

But I wasn't able to think of a good matcher to fill in the blank. It seemed like a new matcher which was the exact inverse of `include`...

Or we build a custom matcher from `satisfy`, and then include that?

**Comment by entwanderer** [comment]
I have the problem @eostrom mentioned above, when the expected value is an dynamic array with 1-n values:
```
expect(400).to be_included_in(dynamic_array)
```
@myronmarston your example may be fine ... but i would expect that in the rspec standard, because it's quite basic ... so i assert that most developers switch expectation and actual value and forget about it.

**Comment by JonRowe** [comment]
@entwanderer if you'd like to create a PR I'd be happy to take a look at it
