### ISSUE TITLE
Nesting array matchers does not seem to work

### ISSUE THREAD

**Issue by mattgibson** [rspec/rspec-expectations#764]
`expect([[2]]).to match array_including(array_including(2))`

Fails with 

`expected [[2]] to match #<RSpec::Mocks::ArgumentMatchers::ArrayIncludingMatcher:0x000001090ca350 @expected=[#<RSpec::Mocks::ArgumentMatchers::ArrayIncludingMatcher:0x000001090ca3a0 @expected=[2]>]>`

**Comment by myronmarston** [comment]
I can't repro against either master or 3.2.  I can repro against 3.1.  Are you on RSpec 3.0 or 3.1?  If so, this should be fixed if you upgrade.  It was addressed in rspec/rspec-mocks#819.

**Comment by mattgibson** [comment]
3.1.3. I'll try upgrading. Thanks for taking a look.
