### ISSUE TITLE
how to stop script execution when rspec`include` matcher fails

### ISSUE THREAD

**Issue by chandanaGollapudi** [rspec/rspec-expectations#779]
Hi,

Recently we have migrated from Rspec 2.X to rpsec 3.2. to verify few of checkpoints  i am using rspec ' include' matches.i.e,

expect(page.getpagetitle()).to include("Customer Service Details")

 I would like to break test execution when checkpoint fails. But with  rspec 3.2 matches , i am not able to achieve this. I am able to do this by using Rspec 2.x by using "should" .

Could somebody help in doing this.

Thanks,
Chandana

**Comment by JonRowe** [comment]
If `page.getpagetitle` returns a string not including `"Customer Service Details"` then the test should fail and not continue executing, can you provide more of an example?

**Comment by chandanaGollapudi** [comment]
sure. please find the attached code here

shared_example :Provide_provisioning_Details do |data|
   page = ''
	it 'When provisioning wizard page is available' do
      page = visit(ProvisioningWizardPage)
	  puts data['technology']
      $logger.info(data['technology'])
       expect(page.getpagetitle()).to include("Customer Service Details")
	end  
	it 'User should able to provide data' do  
	  page.provide_ProvisioningDetails(data)
    end
end

result file : 
![image](https://cloud.githubusercontent.com/assets/11437366/7250620/977e273a-e841-11e4-9d19-d720ed709766.png)

Here in the code, though the first step failed, it is reporting and continuing with next step.

Please  let me know if doing anything wrong.

thanks,
Chandana

**Comment by JonRowe** [comment]
Those aren't steps, they're tests, thats how RSpec is supposed to and always has behaved, I'm not sure what your could looked like before but that currently looks correct.

**Comment by JonRowe** [comment]
Note, I'm closing this because I don't think theres an RSpec issue here, please continue to ask questions if you want to understand what's going on, feel free to paste the code you had before the upgrade for comparison, its possible it's been translated wrongly in the upgrade process.

**Comment by chandanaGollapudi** [comment]
Ok..i got it now. Previously we are  writing complete code related test cases under  "it " block.

recently we started using shared examples , so because of this i  divided the same code into different  shared examples.

previous code :

it "should provide UNI service" do            
						
					   visit(ProvisioningWizardPage) do |page|
                                                 page.getpagetitle()).should == "Customer Service Details"
						   page.provide_ProvisioningDetails(data)
					   end
				    visit(CustomerServiceDetailsPage) do |page|  
					  page.provide_customerserviceDetails(data) 	  
				     end
end

now ,latest code:

shared_example :Provide_provisioning_Details do |data|
   page = ''
	it 'When provisioning wizard page is available' do
      page = visit(ProvisioningWizardPage)
	  puts data['technology']
      $logger.info(data['technology'])
      #expect(page.getpagetitle()).to include("Provisioning Wizard")
	  expect(page.getpagetitle()).to include("Customer Service Details")
	end  
	it 'User should able to provide data' do  
	  page.provide_ProvisioningDetails(data)
    end
end
shared_examples :Provide_customer_Details do |data|	
	page = ''
	it 'CustomerServiceDetailsPage should be success' do
      page = visit(CustomerServiceDetailsPage)
      $logger.info("CustomerServiceDetailsPage should be success")
      expect(page.getpagetitle()).to include("Customer Service Details")
	end  
	it 'User should able to provide data' do
	  page.provide_customerserviceDetails(data)
    end

shared_examples :provide_uni_service do |data,strServiceName| 
include_examples :Provide_provisioning_Details,data 
include_examples :Provide_customer_Details,data
end

i would like to break execution if any of the check point fails. could u let me know how to achieve it with latest code? 

thanks,
chandana

**Comment by myronmarston** [comment]
You can use the '--fail-fast' option to have RSpec abort after one failure.

**Comment by JonRowe** [comment]
You've changed the meaning of your tests by introducing the extra `it` blocks, but like @myronmarston you can simulate the previous behaviour using `--order defined` and `--fail-fast` both of which are configurable in your `spec_helper.rb` (using the relevant `config.` methods) or in your `.rspec` file.

**Comment by chandanaGollapudi** [comment]
thanks Myron. but is there any option which continues with suite execution but breaks the testcase execution when one of the checkpoint fails. for example, i have 10 tests in suite, if  test 2 fails bcoz of checkpoint failure .i would like to break test  2 execution and continues with 3rd  test cases in suite.

this is bcoz in some cases ,if major check point fails then there is not point to proceed further in executing test. for ex ,user not able to login to app, in this case i would like to stop the test case execution n continue executing other test.

Thanks,
Chandana

**Comment by myronmarston** [comment]
I may be misunderstanding what you're asking for, but I'd say that what you described is exactly RSpec's default behavior:

``` ruby
RSpec.describe "An example group" do
  it "aborts an example when it fails" do
    expect(1).to eq(2)
    # it will not make it past that first expectation since it failed
    do_other_stuff
  end

  it "still runs other examples" do
    expect(1).to eq(1)
  end
end
```

Or am I misunderstanding you?  If that's not what you mean than please push up an example project that's not producing the output you would expect and give us an example of what output you would like instead.

**Comment by chandanaGollapudi** [comment]
i guess my question is different. in the above example , as you mentioned if  first example fail, still it executes second example. my question is ,if first example fails in example group then i am looking for ways which stops execution of second example. 

In the below the code,  My spec file contains different test cases that uses shared-example file .

Spec File :
$uni_data = YAML.load_file('data/daily-test/provisioning/uni_usecase.yml')
$UNI = $uni_data['PROVISION_UNI']

describe 'create UNI-1 ',:sanity do
  include_examples :provide_uni_service , $UNI['UNI_TEST1'],"UNI"  
end
describe 'create UNI-2 ',:regression do
  include_examples :provide_uni_service , $UNI['UNI_TEST2'],"UNI"  
end

In both my test cases i am calling "provide_uni_service" shared_example.i.e.

shared_examples :provide_uni_service do |data,strServiceName| 
include_examples :Provide_provisioning_Details,data 
include_examples :Provide_customer_Details,data
end

In side this , i am calling other shared examples which contains examples that actually perform test actions.

shared_example :Provide_provisioning_Details do |data|
   page = ''
 1.   it 'When provisioning wizard page is available' do
      page = visit(ProvisioningWizardPage)
      puts data['technology']
      $logger.info(data['technology'])
      #expect(page.getpagetitle()).to include("Provisioning Wizard")
      expect(page.getpagetitle()).to include("Customer Service Details")
    end  
 2.   it 'User should able to provide data' do  
      page.provide_ProvisioningDetails(data)
    end
end
shared_examples :Provide_customer_Details do |data| 
    page = ''
  1.  it 'CustomerServiceDetailsPage should be success' do
      page = visit(CustomerServiceDetailsPage)
      $logger.info("CustomerServiceDetailsPage should be success")
      expect(page.getpagetitle()).to include("Customer Service Details")
    end  
    2.it 'User should able to provide data' do
      page.provide_customerserviceDetails(data)
    end

In code, each "it " block/example is a test step for me. so , If any of the test step fails, then i would like to break execution , fail the test  and  proceed with other tests in the spec file.

I understand the problem, i am using  "it " block to represent my test step instead test case. this is bcoz  to procedure detailed reports after execution. In this way, it allows to include  detailed description of each test step/ check point in report.

if use --fail-fast option  teststep /example  fails, then it breaks complete suite execution.

Hope you understand the issue now.

1. please let me know if there flaws in test design.

2. if failure of one example is not have control over other examples execution then is there any way to include each step in the report?

3. How example failure in exmaple-group effects other example-groups in terms of execution? can we create some dependency b/w examples n example-groups ?

Thanks,
Chandana

**Comment by myronmarston** [comment]
@chandanaGollapudi -- I'm not able to understand the code you've written above because of the formatting (you've got code mixed into lists...).  Can you use [github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) to format the code blocks?  You'd want to use fenced code blocks (triple backtick) with a `ruby` label.

Anyhow, it sounds like you are mis-using RSpec's structure.  Examples (defined by `it`) are not intended to be used to define separate steps of one long test.  Each example should be a self-contained thing, capable of being run individually, in any order.  You ask about whether or not you can create some dependency between examples in an example group....the answer is that yes, you can, but that's setting yourself up for a world of pain in the future.  RSpec has features that specifically exist to help users avoid accidental dependencies between examples, because ordering dependencies in your examples create flickering tests and other pain.

If you simply want additional output sent to the formatter within an example, there are other ways to achieve that.  You can publish custom events to a formatter and use your own formatter to output that however you want.  There are also a couple gems that may do what you want:

* https://github.com/railsware/rspec-example_steps
* https://github.com/LRDesign/rspec-steps

**Comment by chandanaGollapudi** [comment]
I am glad to see your detailed  explanation. It is very informative. Rpsec-steps makes my work easy.  

Thanks a lot Myron!!

**Comment by chandanaGollapudi** [comment]
Hi , 

I  am not able to use "it" block inside "shared_steps" block as described in below link.
https://github.com/LRDesign/rspec-steps
code

![shared_steps_with_itblock](https://cloud.githubusercontent.com/assets/11437366/7471073/4ba12c86-f340-11e4-8dda-c61134109d8f.jpg)


Error Message

![error_msg](https://cloud.githubusercontent.com/assets/11437366/7471077/5e29fc16-f340-11e4-9b95-9eef6607e0e9.jpg)


 but other example worked fine that has When, Given,And and Given blocks provided under below link .

https://github.com/railsware/rspec-example_steps 

code
![shared_steps_with_gerkin](https://cloud.githubusercontent.com/assets/11437366/7471148/201bc2fa-f341-11e4-9f42-46438415c204.jpg)


could you please clarify me on below points

1. can i use "it " block under "shared_steps" ?

2.  is gem 'rspec-example_steps' supports Gherkin Language by default?

3. for example, if i am using multiple steps under "describe " block , how to skip remaining steps , if one step fail?

4. Along with Step block description  I would like to add  (Given, When, And, Then ) blocks description to HTML report . Could you please let me different gems/ways that are available to support this.

thanks,
Chandana

**Comment by myronmarston** [comment]
We're not involved in either the rspec-steps or rspec-example_steps projects.  You'll have to send your questions to the authors of those gems.

**Comment by chandanaGollapudi** [comment]
ok..thanks Myron
