### ISSUE TITLE
Support for a size expectation

### ISSUE THREAD

**Issue by krainboltgreene** [rspec/rspec-expectations#785]
Sadly Ruby's enumerable doesn't have a `size?` or `length?` function, so sometimes I have to write specs like this:

``` ruby
it("should contain 11 objects") do
  expect(data.size).to eq(11)
end
```

This is a bit awkward since I can do other things.

I propose a new expectation for collection objects:

``` ruby
it("should contain 11 objects") do
  expect(data).to total(11)
end
```

I think this also opens the gateway for some interesting extended matchers:

``` ruby
it("should contain 11 objects") do
  expect(data).to total(11).all(Net::Request::Header)
  # satisfy do |object|
  #   object.size == 11 && object.all? { item| item.kind_of?(Net::Request::Header) }
  # end
  expect(data).to total(11).some(Net::Request::Header)
  expect(data).to total(11).none(Net::Request::Header)
  expect(data).to total(11).all do |object|
    object == value
  end
end
```

**Comment by JonRowe** [comment]
You can eazily define a custom matcher for this:

```Ruby
RSpec::Matchers.define :total do |expected|
  match do |actual|
    actual.size == expected
  end
end
```

Although personally I'd call it `have_size`

**Comment by myronmarston** [comment]
There's also https://github.com/rspec/rspec-collection_matchers, which provides cardinality matchers.

IMO, the proposed `total` doesn't read well; based on the word "total" I'd expect it to sum up the array, but that's not what you intend.

Also, if you want to do a compound expectation, where you specify both the cardinality and an aspect that is true of all items, you can easily do that if you use the gem I linked to above or define your own cardinality matcher:

``` ruby
expect(data).to have(11).entries.and all be_a Net::Request::Header
```

**Comment by krainboltgreene** [comment]
The issue isn't titled "How do I do X".

**Comment by krainboltgreene** [comment]
I didn't know about collection_matchers, gracias.

**Comment by krainboltgreene** [comment]
Although this cause me to question why collection matchers have their own gem, the only official "extras" matcher gem in rspec.

**Comment by JonRowe** [comment]
We decided to extract them because we felt they were a bit too magical and didn't really aline with our recommended practises. It's not the only official "extras" gem, there's also `rspec-its` which was similarly extracted. See http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/

**Comment by skalee** [comment]
> Sadly Ruby's enumerable doesn't have a size? or length? function, so sometimes I have to write specs like this…

Oh, simply use `have_attributes` matcher:

```ruby
expect("abc").to have_attributes(size: 3) # passes
expect("abc").to have_attributes(size: (be > 2)) # passes
expect([1, 2, 3]).to have_attributes(size: 3) # passes
```
