### ISSUE TITLE
Make diffable output.

### ISSUE THREAD

**Issue by dg-ratiodata** [rspec/rspec-expectations#795]
Hi @myronmarston I would like to use the suggested values_match?-helper in a matcher which should be diffable - on another project.

```ruby
RSpec::Matchers.define :have_option_value do |expected|
  match do |actual|
    values_match? subject.public_send(actual.to_sym), expected
  end

  diffable

  failure_message do |actual|
    format(%(expected that option "%s" has value "%s"), actual, expected)
  end

  failure_message_when_negated do |actual|
    format(%(expected that option "%s" does not have value "%s"), actual, expected)
  end
end
```

The diff should be done by using the value of subject.public_send(actual.to_sym) leaving the actual-value untouched because I need it for the failure messages.

Is there a way to express this using the dsl? While reading the rspec sources I didn't find a proper way to do it. Thanks a lot in advance.

**Comment by myronmarston** [comment]
First off, it's important that you pass `expected` as the first argument to `values_match?` and `actual` as the second argument, so your match block should be:

``` ruby
  match do |actual|
    values_match? expected, subject.public_send(actual.to_sym)
  end
```

The order matters because internally RSpec uses the `===` protocol, which is not a symmetrical operator.  (As an example, consider that `be > 10` knows how to match `20`, but `20` does not know how to match `be > 10` nor should it).

As to your question about diffing -- it simply calls `expected` and `actual` on the matcher.  To redefine `actual`, you could do:

``` ruby
attr_reader :actual

match do |option|
  @actual = subject.public_send(option.to_sym)
  values_match? expected, actual
end
```

**Comment by dg-ratiodata** [comment]
Cool. Thanks, ok. And to make the "old" value available within 

```  ruby
failure_message do |actual|
    format(%(expected that option "%s" has value "%s"), @old_actual, expected)
end
```

I use  just another instance variable, correct?

**Comment by dg-ratiodata** [comment]
Just for the protocol. This works and makes the "old" value available for error messages.

```ruby
RSpec::Matchers.define :have_option_value do |expected|
  match do |actual|
    @old_actual = actual
    @actual     = subject.public_send(actual.to_sym)
    values_match? expected, @actual
  end

  diffable

  failure_message do |actual|
    format(%(expected that option "%s" has value "%s"), @old_actual, expected)
  end

  failure_message_when_negated do |actual|
    format(%(expected that option "%s" does not have value "%s"), @old_actual, expected)
  end
end
```
