### ISSUE TITLE
How to pass in methods into matcher

### ISSUE THREAD

**Issue by dg-ratiodata** [rspec/rspec-expectations#803]
Hi, I use

```ruby
RSpec.configure do |config|
  config.include Aruba::Api
end
```
to include methods in Rspec and something like

```ruby
World(Aruba::Api)
```

to include methods in Cucumber.

This matcher works fine, ...

```ruby
RSpec::Matchers.define :have_exit_status do |expected|
  match do |actual|
    @old_actual = actual

    @old_actual.stop(announcer) unless @old_actual.stopped? # <<<< --- announcer cannot be found -> NoMethodError
    @actual = actual.exit_status

    next false unless @old_actual.respond_to? :exit_status

    values_match? expected, @actual
  end

  failure_message do |actual|
    format(%(expected that command "%s" has exit status of "%s", but has "%s".), @old_actual.commandline, expected.to_s, actual.to_s)
  end

  failure_message_when_negated do |actual|
    format(%(expected that command "%s" does not have exit status of "%s", but has "%s".), @old_actual.commandline, expected.to_s, actual.to_s)
  end
end
```

... when using the matcher in RSpec-tests.

```ruby
RSpec.describe 'Test' do
  it { expect(last_command).to have_exit_status(0) }
end
```

But fails if I use it in a cucumber step.

```ruby
Given/^step a$/ do
  expect(last_command).to have_exit_status(status)
end
```

The `announcer`-method is part of the aruba-API. What should I do, to make it available in RSpec-matchers used in cucumber-steps? Any suggestion?

**Comment by JonRowe** [comment]
If the matcher is failing because of the announcer method not being present then adding `include Aruba::Api` inside the matcher definition should fix it. Thus:

```
RSpec::Matchers.define :have_exit_status do |expected|
  include Aruba::Api
  # ...
end
```

**Comment by dg-ratiodata** [comment]
Ok. I think this will do the trick for the `announcer`-use case. But what should I do, if I need information/state from the outside.

Given the following code:

```ruby
module MyApi
  def my_method
    @cached_ob ||= MyObject.new
  end
end
```

And this matcher:

```ruby
RSpec::Matchers.define :have_exit_status do |expected|
  include MyApi

  match do |actual|
    @old_actual = actual

    @old_actual.stop(my_method) unless @old_actual.stopped?
    @actual = actual.exit_status

    next false unless @old_actual.respond_to? :exit_status

    values_match? expected, @actual
  end
end
```

This will a have different instance of `MyObject` inside the matcher. Any suggestion for such a case? I think about attaching state to the `actual`-object to make it available within the matcher. Is there any other way to do this?

```ruby
RSpec::Matchers.define :have_exit_status do |expected|
  match do |actual|
    @old_actual = actual

    @old_actual.stop(actual.my_method) unless @old_actual.stopped?
    @actual = actual.exit_status

    next false unless @old_actual.respond_to? :exit_status

    values_match? expected, @actual
  end
end
```

**Comment by JonRowe** [comment]
> This will a have different instance of MyObject inside the matcher. Any suggestion for such a case? I think about attaching state to the actual-object to make it available within the matcher. Is there any other way to do this?

My suggestion is don't do that. If you need a singleton state do it on the module itself
```
module MyApi
  def self.object
    @cached_ob ||= MyObject.new
  end
end
```

and access via `MyApi.object`. Remember that each test is an individual object, as is (I believe) each cucumber scenario. The difference is the evaluation context of the matcher DSL. We can't control that outside of RSpec and you should assume it's isolated (as it appears to be in the case of cucumber) and assume you can't access anything outside the matcher context.

**Comment by dg-ratiodata** [comment]
Thanks for the feedback. I think I should have avoided the term "state". Sorry for that. But anyway this is very helpful for matchers I will build in the future.

As this might be helpful for others:

For my current use case I needed to switch to the observer- and decorator-pattern. Every time a command is [stopped](https://github.com/dg-ratiodata/aruba/blob/feature/refactor_command_execution_2/lib/aruba/matchers/command.rb#L23) (in the matcher and everywhere else), I want to be able to [announce](https://github.com/cucumber/aruba#seeing-more-output-with-announce-) information about the stopped program like exit status, stderr, stdout to my terminal's stdout.

I [wrapped](https://github.com/dg-ratiodata/aruba/blob/feature/refactor_command_execution_2/lib/aruba/command_monitor.rb#L36) the actual - RSpec actual - object now within a [decorator](https://github.com/dg-ratiodata/aruba/blob/feature/refactor_command_execution_2/lib/aruba/aruba_command.rb). The decorator takes the [process](https://github.com/cucumber/aruba/blob/feature/refactor_command_execution_2/lib/aruba/processes/spawn_process.rb) and an [event queue](https://github.com/dg-ratiodata/aruba/blob/feature/refactor_command_execution_2/lib/aruba/event_queue.rb).

Within the matcher only the decorated actual object is available. When the `#stop`-method is [called](https://github.com/dg-ratiodata/aruba/blob/feature/refactor_command_execution_2/lib/aruba/matchers/command.rb#L23) the decorator [notifies](https://github.com/dg-ratiodata/aruba/blob/feature/refactor_command_execution_2/lib/aruba/aruba_command.rb#L13) the observers about that.

Doing this no state leaks into the matcher and it works with `RSpec` and `Cucumber` - at least I hope that as the code is not finished yet. :wink:

**Comment by JonRowe** [comment]
It's worth pointing out here the matcher DSL is actually just short hand for creating a class, so the context within the DSL is that of the matcher class, see https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/dsl.rb

**Comment by dg-ratiodata** [comment]
BTW:
I looked through my code and found a strange thing: Only the `#announcer`-method raises a NoMethodError. All other methods from `Aruba::Api` used in matchers work in `Cucumber`like they work in `RSpec`. I think I need to dig a little bit deeper. Maybe I did something wrong.
