### ISSUE TITLE
Recommendations for using matcher with single and multiple objects

### ISSUE THREAD

**Issue by maxmeyer** [rspec/rspec-expectations#806]
@myronmarston Do you have any recommendations for creating matchers which should match single and multiple objects withe the same api/are from the same class?

```ruby
# @!method have_output_on_stderr
#   This matchers checks if <command> has created output on stderr
#
#   @return [TrueClass, FalseClass] The result
#
#     false:
#     * if command has not created output on stderr
#     true:
#     * if command created output on stderr
#
#   @example Use matcher
#
#     RSpec.describe do
#       it { expect(last_command).to have_output_on_stderr }
#     end
RSpec::Matchers.define :have_output do |expected, combine_output|
  match do |actual|
    if actual.is_a?(Enumerable) && combine_output
      combined_match(actual, expected)
    elsif actual.is_a?(Enumerable)
      all_match(actual, expected)
    elsif
      single_match(actual, expected)
    else
      false
    end
  end

  diffable

  description { "have #{description_of expected}" }

  private

  def all_match(actual, expected)
    Array(actual).flatten.each do |a| 
      @actual = a.output.chomp
      return false unless a.respond_to? :output
      return false unless values_match? expected, @actual
    end

    true
  end

  def combined_match(actual, expected)
    @actual = Array(actual).flatten.each_with_object([]) do |e, a| 
      next unless e.respond_to? :output
      a << e.output.chomp 
    end.join("\n")

    values_match? expected, @actual
  end

  def single_match(actual, expected)
    return false unless actual.respond_to? :output

    @actual = actual.output.chomp

    values_match?(expected, @actual)
  end
end
```

This is an exampe of a matcher which matches a single `command` in aruba. I've got different matchers which can be devided in two main use cases, when coming to multiple `actual`s.

1. Match against each "element" of array (e.g. match agains each stderr and fail on first mismatch)
2. Combine each element of array (e.g. sum up all stderrs and match against that combined string)

What would you do, to make it match multiple commands as well? Just a loop which returns true/false?

Thanks a lot in advance.

**Comment by myronmarston** [comment]
We have a number of matchers that can match against 1 or many:

``` ruby
expect(object).to respond_to(:foo)
expect(object).to respond_to(:foo, :bar)
expect(object).to respond_to(:foo, :bar, :bazz)

expect(collection).to include(foo)
expect(collection).to include(foo, bar)
expect(collection).to include(foo, bar, bazz)
```

In addition we support the `all` matcher:

``` ruby
expect(collection).to all satisfy_some_matcher
```

And you can `and` together an arbitrary number of matchers:

``` ruby
expect(object).to match(x).and match(y).and match(z)
```

RSpec 3.3 supports `aggregate_failures` so uses can always group a set of expectations together:

``` ruby
aggregate_failures "output" do
  expect(last_command).to have_output("foo")
  expect(last_command).to have_output("bar")
  expect(last_command).to have_output("bazz")
end
```

Maybe that will give you some idea?  With `and`, `all` and `aggregate_failures` there's already a lot of flexibility built in.

**Comment by maxmeyer** [comment]
`all` sounds good. Is there an `any`, too?

**Comment by maxmeyer** [comment]
Is there a reason, why "rspec" does not support `not_to` for `all`?

```ruby
raise NotImplementedError, '`expect().not_to all( matcher )` is not supported.'
```

**Comment by maxmeyer** [comment]
@myronmarston I added the `Any`-matcher using my coporate account, see #807.

**Comment by maxmeyer** [comment]
Let me know if this PR needs improvement... :-)

**Comment by myronmarston** [comment]
> Wonderful. Thanks a lot. `all` sounds good. Is there an `any`, too? I would then get rid of a lot of code :smile:

Yes, we provide `any` but it's called `include`.

**Comment by Jorge-Ortiz-M** [comment]
The negative form not_to all is not supported. Instead use not_to include or pass a negative form of a matcher as the argument (e.g. all exclude(:foo))

https://rubydoc.info/gems/rspec-expectations/RSpec/Matchers

You can see more examples about how to use the all matcher.
