### ISSUE TITLE
`contain_exactly` fails on an unsortable array

### ISSUE THREAD

**Issue by dividedmind** [rspec/rspec-expectations#812]
I've been upgrading a project from RSpec 2 and got new failures after transpec and changing to RSpec 3. Those seem to be related to `contain_exactly` trying to sort arrays, but the types being incomparable, for example:

```
  1) WidgetsController audit methods #audit_index_forbidden populates the event
     Failure/Error: expect(event[:widgets]).to contain_exactly(widget_ids << current_widget)
     ArgumentError:
       comparison of String with RSpec::Mocks::Double failed
     # ./spec/support/matchers/contains_exactly.rb:23:in `sort'
     # ./spec/support/matchers/contains_exactly.rb:23:in `match_when_sorted?'
     # ./spec/support/matchers/contains_exactly.rb:32:in `block (2 levels) in <top (required)>'
     # ./spec/controllers/widget_controller_spec.rb:77:in `block (5 levels) in <top (required)>'
     # [...]
```

Note this is a change of behaviour compared to RSpec 2 (the tests were green before changing the version in Gemfile to 3).

**Comment by dividedmind** [comment]
Whoops, just realized the matcher comes from my own code (although it's lifted from rspec). Closing pending investigation (ie. why did it work in RSpec 2?). Sorry!

**Comment by JonRowe** [comment]
We changed the matcher protocol between RSpec 2 and 3, we don't really expect people to be lifting our own matchers so monkey patched code would probably break... I believe we do have an upgrade path for legacy matcher syntax tho

**Comment by dividedmind** [comment]
Yes, I fixed it by removing the local matcher copy and adding a splat in the calls. (No idea why it stopped working on changing to rspec3; but I suspect class name shadowing caused the class to get some code from RSpec and some from our copy.) Thanks for taking the time to reply!

**Comment by JonRowe** [comment]
Like I said, we changed the protocol, internal RSpec 2.x matchers are not be expected to work with 3.x

**Comment by dividedmind** [comment]
That matcher was backported from RSpec3 :)

**Comment by JonRowe** [comment]
Hmm, odd, but still, if removing it fixed it ;)
