### ISSUE TITLE
raise_error warning should include current error message

### ISSUE THREAD

**Issue by xaviershay** [rspec/rspec-expectations#822]
In upgrade some applications to latest RSpec, I've noticed a common pattern:

* Get a warning about using `raise_error` without an argument.
* Comment out `raise_error` expectation and re-run test to see what an appropriate argument would be from the failure.
* Add argument, re-run test to see it green.

Looking at `BuiltIn::RaiseError#matches?` seems like it could be pretty straight-forward to include the exception message (if raised) in the warning.

**Comment by xaviershay** [comment]
I'll probably tackle this when I get a moment, just leaving a reminder here since I'm not going to get to it tonight.

**Comment by myronmarston** [comment]
I think this is a good idea, but there are a couple potential issues to bear in mind:

* The error currently being raised may not be the one the user actually cares about.  For example, if the false positive issue the warning warns about has occurred (e.g. the method being tested was renamed without the call site in the `raise_error` block being updated) than the error isn't the one that user cares about.
* Writing a non-brittle test requires judging which parts of the exception identify the exception while being unlikely to change.  Simply putting the entire current exception message in the expectation is a bad idea as the spec will fail at a simple punctuation, capitolization, whitespace or spelling change.

So I think it's great for the warning to give the user more detail about the exception currently being raised as long as it doesn't direct them to encode the full details of the current exception into the expectation.

**Comment by xaviershay** [comment]
> So I think it's great for the warning to give the user more detail about the exception currently being raised as long as it doesn't direct them to encode the full details of the current exception into the expectation.

Totally agree.

I actually discovered a `NoMethodError` this way, it just took me more messing around than seemed necessary.

**Comment by mrageh** [comment]
@xaviershay I was thinking of attempting to fix this issue, but so far I don't fully understand what the issue is. Can you please provide a test that describes the problem in more detail?

**Comment by xaviershay** [comment]
``` ruby
describe do
  it 'works' do
    expect {
      raise "it failed"
    }.to raise_error
  end
end
```

Gives this output
```
> rspec test_spec.rb
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /private/tmp/test_spec.rb:3:in `block (2 levels) in <top (required)>'.
.

Finished in 0.00293 seconds (files took 0.2837 seconds to load)
1 example, 0 failures
```

Notice how from the warning message, it's not obvious how to fix? It's a three step process, as outlined in the initial report. If the warning included the actual error that was raised (`it failed`) then I could fix it in a one spec process.

Does that make sense?

**Comment by mrageh** [comment]
Yeah thank you, you're initially description did make sense but I just wanted to double check my own understanding of the problem.

I'll attempt to fix this problem and hopefully you can review my solution :)

**Comment by mrageh** [comment]
@xaviershay I've finally got around to looking into this issue and I think the out from the warning below may be more helpful. What do you think?

```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. Maybe you meant to pass #<RuntimeError: it failed> to the raise_error matcher. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /private/tmp/test_spec.rb:3:in `block (2 levels) in <top (required)>'.
```

**Comment by xaviershay** [comment]
Love it! Slight wording change to "Actual error raised was <>" to address myron's concern in earlier comment.

**Comment by mrageh** [comment]
Thanks @xaviershay.

 I've updated the message and will submit my PR today hopefully.

```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. Actual error raised was #<RuntimeError: it failed>. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /private/tmp/test_spec.rb:3:in `block (2 levels) in <top (required)>'.
```

**Comment by xaviershay** [comment]
I think this has always been here, but just noticed a typo in "supressed"

**Comment by mrageh** [comment]
This can be closed now

**Comment by JonRowe** [comment]
Thanks

**Comment by nerdrew** [comment]
Is there a way to convert the `raise_error` warnings into hard errors?

**Comment by JonRowe** [comment]
Yes. I believe `RSpec.configuration.raise_on_warning = true` will do that for you.
