### ISSUE TITLE
Inconsistent expectation behavior for received calls between RSpec 2.99 and 3.0.0

### ISSUE THREAD

**Issue by rickypai** [rspec/rspec-expectations#824]
I need to make assertion on whether a code path would log a particular event in midst of multiple logging calls:

Suppose in code:

```ruby
Logging::Tracking.logger.log_event(event_name: 'some event')
Logging::Tracking.logger.log_event(event_name: 'some other event')
Logging::Tracking.logger.log_event(
  event_name: 'cool_event',
  event_data: { request_id: @request.id, user_id: @user.id }
)
```

in spec:

```ruby
allow(Logging::Tracking.logger).to receive(:log_event)
expect(Logging::Tracking.logger).to receive(:log_event) do |params|
  expect(params[:event_name]).to eq('cool_event')
  expect(params[:event_data][:request_id]).to eq(@request.id)
  expect(params[:event_data][:user_id]).to eq(@user.id)
end
```

This assertion passes in RSpec 2.99, however, in RSpec 3.0.0, the test would fail with: (Also tested in RSpec 3.3.0)

```
Failure/Error: expect(params[:event_name]).to eq('cool_event')

  expected: "cool_event"
  got: "some event"

  (compared using ==)
```

According to the upgrade guide, this is considered a bug. If not, I'm also opened to suggestion of how to better improve the spec.

Thank you,

**Comment by JonRowe** [comment]
I would not consider this a bug, it's matching against the first call and then failing because the values don't match. You should refactor this to something like:

```Ruby
allow(Logging::Tracking.logger).to receive(:log_event)
expect(Logging::Tracking.logger).to receive(:log_event).with(event_name: 'cool event', event_data: anything) do |params|
  expect(params[:event_data][:request_id]).to eq(@request.id)
  expect(params[:event_data][:user_id]).to eq(@user.id)
end
```

**Comment by rickypai** [comment]
Thank you so much for the prompt response! I forgot about `anything`, this really helped!

**Comment by myronmarston** [comment]
Honestly, I'm surprised that that passed on 2.99.  Sounds like we may have had a bug there that got fixed in 3.x.
