### ISSUE TITLE
Improved match_array

### ISSUE THREAD

**Issue by morgoth** [rspec/rspec-expectations#826]
By accident I wrote spec, where I compared two hashes instead of two arrays:
```
expect({"root" => [{"a" => 1}, {"a" => 2}]}).to match_array({"root" => [{"a" => 1}, {"a" => 2}]})
```
this passed, but (flipped hashes in expected array)
```
expect({"root" => [{"a" => 1}, {"a" => 2}]}).to match_array({"root" => [{"a" => 2}, {"a" => 1}]})
```
failed with confusing message:
```
     Failure/Error: expect({"root" => [{"a" => 1}, {"a" => 2}]}).to match_array({"root" => [{"a" => 2}, {"a" => 1}]})
       expected collection contained:  [["root", [{"a"=>2}, {"a"=>1}]]]
       actual collection contained:    [["root", [{"a"=>1}, {"a"=>2}]]]
       the missing elements were:      [["root", [{"a"=>2}, {"a"=>1}]]]
       the extra elements were:        [["root", [{"a"=>1}, {"a"=>2}]]]
```

As the first one passed, it gives false positive.
Do you think we can add Array type checking, to avoid such situations? If yes, I can work on PR.

**Comment by myronmarston** [comment]
The matcher is specifically designed to work with objects that are not arrays but that can be converted to an array with `to_ary` and `to_a`:

https://github.com/rspec/rspec-expectations/blob/0970537d9876b9699920f73d58d15fd26ec5585e/spec/rspec/matchers/built_in/contain_exactly_spec.rb#L311-L327

https://github.com/rspec/rspec-expectations/blob/0970537d9876b9699920f73d58d15fd26ec5585e/lib/rspec/matchers/built_in/contain_exactly.rb#L52-L60

Hashes implement `to_a` and can be treated as an array (a list of k/v pairs), so the behavior you saw seems correct to me.  You could argue that we should have forced users to be explicit and pass us arrays (by calling `to_a` on the arguments they pass, or whatever) but changing it at this point would be a breaking API change, so it's not something we'd consider.  IMO, the behavior you are reporting is exactly what I would expect.
