### ISSUE TITLE
Add capturing support to the `match` built-in matcher

### ISSUE THREAD

**Issue by jasonkarns** [rspec/rspec-expectations#831]
Some regexes are complicated enough to warrant their own specs, which naturally leads to specifying not only that the regex matches a given string, but that it captures the correct substrings.

It would be great if there were a method chain on `match()` that accepted an array or hash to match against the captures from the regex. (Array if using indexed capture groups, Hash if using named capture groups)

Example:

``` ruby
module Indexed
  COMPLEX_REGEX = /^.*(\d+).*$/
end
module Named
  COMPLEX_REGEX = /^.*(?<num>\d+).*$/
end

describe "complicated regex" do
  it "should capture the digits" do
    expect(Indexed::COMPLEX_REGEX).to match("foo123bar").capturing(["123"])
    expect(Named::COMPLEX_REGEX).to match("foo123bar").capturing(num: "123")
  end
end
```

The example above doesn't demonstrate it, but I would expect the matching of named captures (specified using a hash) to do normal hash matching, thus allowing nested matchers in the hash itself.

I have already created a custom matcher that inherits from `RSpec::Matchers::BuiltIn::Match` that supports chaining the `capturing` method to specify expected capture groups. https://gist.github.com/jasonkarns/0b4c9483d11be82bae56.  Description of how the matcher works is commented: https://gist.github.com/jasonkarns/0b4c9483d11be82bae56#gistcomment-1515425

(To be clear, the custom matcher linked above is a quick-fix attempt that covers my scenario. It does *not* handle indexed captures, only named captures matched using a hash. And it does some brittle ivar swapping to provide better error message which would not be suitable for production as-is.)

**Comment by myronmarston** [comment]
I think this is a great idea, although I wonder if the chained method should be `with_captures` instead of `capturing` -- which would align better with `raise_error(...).with_message(...)`.  I don't feel strongly about the name, though.

Any desire to work on a PR for this?  My time these days to work on new features is unfortunately short :(.

**Comment by jasonkarns** [comment]
I like `with_captures`.

I *might* be able to work on a PR. One area of concern is how this will interact with the other uses of `match` (when `actual` is the string instead of the regex, or when using `match` to compare deeply nested objects)

Hopefully I'll get enough ground work on the PR to at least expose the issues and generate some more discussion.

**Comment by myronmarston** [comment]
> when `actual` is the string instead of the regex,

A `MatchData` object is returned in either case so it shouldn't be a problem:

```
"irb(main):001:0> "abc".match(/(a)/)
=> #<MatchData "a" 1:"a">
irb(main):002:0> /(a)/.match("abc")
=> #<MatchData "a" 1:"a">
```

> when using match to compare deeply nested objects

I think we'd just want to raise an error when `match` is given an argument besides a string or regex and `with_captures` is called on it.

Actually, a perhaps better idea: we can put conditional logic in the definition of the `match` method to instantiate an appropriate matcher implementation based on the provided argument.  Then the matcher object returned for the deeply nested object case can simply not define a `with_captures` method.

**Comment by samphippen** [comment]
Closed by #848

**Comment by jasonkarns** [comment]
cool to see this get implemented!

any guesses as to when the next release that includes this might be?

**Comment by myronmarston** [comment]
> any guesses as to when the next release that includes this might be?

Good question.  I was on an extended vacation recently but now that I'm back I'm going to take stock of where the repos are at and see if we can do a release soon.

**Comment by jasonkarns** [comment]
Cool. I don't mean to rush anyone. But if it will be within weeks then I'll
just wait for a release instead of pointing to github-HEAD.

thanks!

**Comment by myronmarston** [comment]
No guarantees but I'm hoping to release within weeks.
