### ISSUE TITLE
`expect(thing).to receive` passes on individual specs, fails to run/block execution when running whole file

### ISSUE THREAD

**Issue by thewatts** [rspec/rspec-expectations#845]
I have some specs:

```ruby
it "sends all requests for a single id to the store" do
  expect(store).to receive(:find).with(1)
  Manager.find(1)
end

it "sends all requests for multiple ids to the store" do
  expect(store).to receive(:find).with([1, 2, 3])
  Manager.find([1, 2, 3])
end
```

And the (simplified) implementation:
```ruby
# Manager
class Manager
  def self.find(id)
    cache.fetch(id)
  end
end

# Cache
class Cache
  def fetch(id)
    store.find(id)
  end
end
```

If I run the specs individually - they pass.
But if I run them together, one of them fails (due to `store.find` getting executed in the code instead of being stubbed out).

Something to note - if I move `store.find` from inside of the `Cache` class, to inside of `Manager.find` - they pass every time.

Any help is greatly appreciated!
Thanks for your hard work on this great project!

**Comment by JonRowe** [comment]
Looking at your simplified example I would wager that theres some shared state going on between the tests and that cache is not being reset in between examples (it's a class variable or something), setting a memoized value here for example would cause this behaviour as the old stub would be cleaned up after the first test, but then the second value would never be used as the first value from the first test would persist in your code.

If you can paste a more detailed example I may be able to help more.

**Comment by myronmarston** [comment]
RSpec's bisect option can probably help you track down the ordering dependency:

https://relishapp.com/rspec/rspec-core/v/3-3/docs/command-line/bisect
