### ISSUE TITLE
Keyword argument and optional argument support for #respond_to matcher.

### ISSUE THREAD

**Issue by sleepingkingstudios** [rspec/rspec-expectations#846]
I maintain a library of additional features for RSpec users, one of whom recently asked me if I planned to backport some of the features to the core project. Specifically, the feature mentioned was an implementation of support for expecting optional and/or keyword arguments using the `#respond_to` matcher, with the following API:

```ruby
expect(instance).to respond_to(:method_name).with(1).argument
expect(instance).to respond_to(:method_name).with(1..2).arguments
expect(instance).to respond_to(:method_name).with_unlimited_arguments

expect(instance).to respond_to(:method_name).with_keywords(:headers, :body, :cookies)
expect(instance).to respond_to(:method_name).with(3).arguments.and_keywords(:options, :http_options)
expect(instance).to respond_to(:method_name).with_arbitrary_keywords
```

Unfortunately, much of this functionality was added before RSpec 3, effectively forking the matcher. The work to update it to use RSpec 3 internals would be non-trivial, but I can do it if there is interest. Is this a feature that other developers would find useful as part of rspec-expectations, and if so, enough so that it would be a candidate for inclusion by the core team if put in a PR?

**Comment by JonRowe** [comment]
Absolutely, we have an open issue about this #471 and I had a first pass at solving this in #502 but have never had the time to finish it.

**Comment by sleepingkingstudios** [comment]
I should be good on the tech side. Where I would appreciate help the most is the soft stuff - method names and syntax, the format of error messages, and so on. For reference, my current implementation is at https://github.com/sleepingkingstudios/rspec-sleeping_king_studios/blob/master/lib/rspec/sleeping_king_studios/matchers/built_in/respond_to.rb, with a Cucumber feature at https://github.com/sleepingkingstudios/rspec-sleeping_king_studios/blob/master/features/matchers/built_in/respond_to_matcher.feature with the syntax details and examples.

**Comment by sleepingkingstudios** [comment]
I've got a first-pass, bare-bones implementation here:
https://github.com/rspec/rspec-expectations/compare/master...sleepingkingstudios:respond_to-keyword-arguments?expand=1

It also requires an update to rspec-support:
https://github.com/rspec/rspec-support/compare/master...sleepingkingstudios:method-signature-expectation?expand=1

Basically, from looking at the code history it seems that existing comparison code in `RSpec::Support` originally came from `RSpec::Mocks`, to verify whether or not a specific parameter list is valid for a given method. When we use it for the `#respond_to` matcher in `RSpec::Expectations`, we're verifying that an abstract set of arguments is valid. The current approach is to take the abstract set and generate actual parameters that are a member of the set, but that limits us to expectations that can be expressed as one specific parameter list, such as splatted arguments or keywords or min-max argument counts. The `MethodSignatureExpectation` isn't strictly necessary for keyword arguments alone, but I'd like to flesh out the api a bit further and support a few of the other features from my lib, particularly using a Range to specify min/max argument counts and `respond_to(...).with_unlimited_arguments` and its kin.

I'm also a little concerned about handling error messages - as the matcher gets more sensitive and has more ways to fail, we should let the user know exactly why it failed. Maybe something like `"expected .* to respond to :my_method with 2 arguments and keywords :ichi and :ni, but :my_method expects at most 1 argument and requires keyword :san"`. Any thoughts?

**Comment by sleepingkingstudios** [comment]
See https://github.com/rspec/rspec-support/pull/250/files

**Comment by mneumark** [comment]
Any word on this? Been sorta ignored...Kinda an important one...

**Comment by sleepingkingstudios** [comment]
I put the code together, but I think I'm missing the right steps for a cross-repo update (needs an update to rspec-support as well). Any recommendations from the maintainers on the proper procedure would be appreciated. I'll go ahead and rebase my changes on the latest versions.

In the mean time, I added support for this in an extension gem: https://github.com/sleepingkingstudios/rspec-sleeping_king_studios. Has a few other features that might be useful even if/when this gets backported.

**Comment by dbachet** [comment]
@sleepingkingstudios Shouldn't this issue be closed?

It looks like 3.5 is implementing `respond_to(:plant).with_keywords(:seed)` etc...

from your commit https://github.com/rspec/rspec-expectations/commit/402075be9dda60f566e5299755b457a2e354cb54

Same for #471 I think

cc @JonRowe

**Comment by sleepingkingstudios** [comment]
Looks good on my end.
