### ISSUE TITLE
`expect { fail.to_not raise_error }` simply passes

### ISSUE THREAD

**Issue by mvidner** [rspec/rspec-expectations#863]
I have recently written this expectation for a buggy method and wondered why it did not fail as I expected it to:
```ruby
expect { some_method.to_not raise_error }
```
Of course the correct form is this, as I was quick to find:
```ruby
expect { some_method }.to_not raise_error
```

and I can call whatever I want in a block that does not executed at all.

I wonder if there is a way to detect such a "void" `ExpectationTarget` without a chained `to/not_to(matcher)` and warn the user.

I tested with version 3.2.1 but I don't see a related change in the [recent Changelog.md](https://github.com/rspec/rspec-expectations/blob/d4586a42ae3ff92a277e46e04863ea0131b02b7c/Changelog.md)

**Comment by JonRowe** [comment]
In general we don't protect against errors like this that we consider to be "syntax" errors, and while I'll admit this is confusing I'm not sure we should go to lengths to protect against this one either.

**Comment by myronmarston** [comment]
I concur.  It's not an error to do `expect(object)` and return that to a caller.  We do that actually to support `is_expected` -- it's defined simply as `expect(subject)`.

**Comment by mvidner** [comment]
Ah, I was not aware of `is_expected`. Thanks for the explanation!
