### ISSUE TITLE
Add smart matcher for `can_` prefixed predicate methods

### ISSUE THREAD

**Issue by jfelchner** [rspec/rspec-expectations#869]
For authorization logic, a lot of times the authorizer has a `can_` prefixed method. I was wondering if it would be desirable to add something similar to how the `have`/`has` works and the predicate matchers work to make it so that if the matcher starts with `be_able_to_foo`, it would look for a method called `can_foo?`.

**Comment by JonRowe** [comment]
Whilst I'm sympathetic to this (I often run into grammatical things like this myself), the problem with that is `be_able_to_foo` already smartly matches to `#able_to_foo?` which is more idiomatic Ruby. My suggestion here is to create a custom matcher for youself like this:

```Ruby
RSpec::Matchers.define :be_able_to do |thing|
  match do |target|
    target.send("can_#{thing}?")
  end
end
```

`expect(thing).to be_able_to :foo`

**Comment by jfelchner** [comment]
@JonRowe completely understandable. Thanks for the reply sir!
