### ISSUE TITLE
More traditional assertion-like syntax

### ISSUE THREAD

**Issue by paddor** [rspec/rspec-expectations#877]
I'm really sorry, but I have to finally bring it up. I guess RSpec is a great testing framework and very mature. Impressive support from other tools. But there's one thing that has always kept me from really using it: The "English" like syntax. It just doesn't feel right.

I love the `describe { ... }` blocks (as opposed to `class MyTest < TestingFramework::TestCase`) and I love the `it "does this" {...}` blocks (as opposed to `def test_does_this; ...; end`) but I can't stand this `expect(foo).to eq(bar)` syntax. Honestly, it reminds me of Perl and Java.

Furthermore, regarding the matchers: the order of the arguments feels wrong. I want to specify the expectation first, and then the expression for the actual value.

Is there a way to use `assert_equal expected, actual`, `assert_kind_of klass, obj`, `assert_raises(klass) { ... }`, ..., well, assertions instead of expectations? (yeah, like Minitest's assertions) Maybe a gem? My search didn't turn up anything.

Thanks. And sorry to file this in the Rspec-_expectations_ project. :sweat_smile:

**Comment by myronmarston** [comment]
Yes, you can use any assertion library you like.  It just has to raise errors to indicate failures.   Using minitest's assertions instead of rspec-expectations is one line of config:

https://relishapp.com/rspec/rspec-core/v/3-4/docs/expectation-framework-integration/configure-expectation-framework

**Comment by paddor** [comment]
Wow, I had no clue. Thanks!
