### ISSUE TITLE
`change.from().to()` does not work properly with sets

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-expectations#878]
As reported by @listrophy on twitter:

https://twitter.com/listrophy/status/671832869946441728

The problem is happening in `Composable#values_match?`:

https://github.com/rspec/rspec-expectations/blob/acc409a0c4055ac0b1b098bd6df29d86807f233b/lib/rspec/matchers/composable.rb#L67

`with_matchers_cloned` treats any enumerable as an ordered list and converts it to an array as part of its logic.  This is bad as it breaks set equality.  We should fix `with_matches_cloned` to not do that.

More generally, I'm thinking that we should stop treating enumerables generically, and only handle arrays in this fashion.  Converting arbitrary enumerables to an array before checking equality is a bad idea.  Or maybe we can find a different way to handle the case `with_matchers_cloned` is there for.

**Comment by listrophy** [comment]
Heh, thanks for taking my gripe in stride, @myronmarston. I actually tried diving in to finding the root cause, but I'm too unfamiliar with the codebase to see the abstractions correctly.
