### ISSUE TITLE
Pretty printing of expected/actual goes too deep

### ISSUE THREAD

**Issue by brightbits** [rspec/rspec-expectations#881]
Hi there,

Is it possible to customise how RSpec displays objects?

Currently, I'm seeing expected X, got Y, which is great, but Y actually takes about 1500 lines and takes 30 seconds to scroll to the top.. is there a way to limit the depth or just plain limit the length of each object  printed?

**Comment by JonRowe** [comment]
Currently your options are to customise your inspect method on your object, or to write a custom matcher that doesn't use inspect. There is an open issue on `rspec-support` for limiting this length, closing in favour of rspec/rspec-support#252.
