### ISSUE TITLE
include matcher shows misleading diff for hashes

### ISSUE THREAD

**Issue by imtayadeway** [rspec/rspec-expectations#887]
With the following example:

```ruby
RSpec.describe "hash matching" do
  it "shows a diff when include matcher fails" do
    actual = {foo: "bar", baz: "qux"}
    expected = {foo: "bar", baz: "quux"}
    expect(actual).to include(expected)
  end
end
```

I get this when it fails:

```
Failures:

  1) hash matching shows a diff when include matcher fails
     Failure/Error: expect(actual).to include(expected)
     
       expected {:foo => "bar", :baz => "qux"} to include {:baz => "quux"}
       Diff:
       @@ -1,2 +1,3 @@
       -[{:foo=>"bar", :baz=>"quux"}]
       +:baz => "qux",
       +:foo => "bar",
       
     # ./hash_include_spec.rb:5:in `block (2 levels) in <top (required)>'
```

There are a couple of things that strike me as wrong here:
1. It seems to indicate that the expected is an array, when it is a hash
2. It didn't show that the `:foo` value was correct

Could this be an issue? Or is this just showing the unavoidable complexity of checking for inclusion here?

**Comment by JonRowe** [comment]
This is a side effect of expected actually being an array (as it takes multiple arguments) for the purposes of the diff...

**Comment by imtayadeway** [comment]
@JonRowe ah, that makes sense now. So...not a bug? Or could this be enhanced?

**Comment by myronmarston** [comment]
I consider it a bug, but not one easily fixed :-(
