### ISSUE TITLE
Suggestion: raise_about_potential_false_positives option

### ISSUE THREAD

**Issue by chrisarcand** [rspec/rspec-expectations#888]
In the `expect { }.to raise_error` (without explicit exception) War™ (see https://github.com/rspec/rspec-expectations/issues/655), I'm of the opinion that raise_error without an argument is dangerous enough to wish to _prevent_ its authorship in projects - not just a warning in the output that can be ignored. 

Perhaps a `raise_about_potential_false_positives` option should be added? I'm assuming `on_potential_false_positives = :warn | :raise` is too much of an API change.

Considering that talk in the aforementioned issue is that this behavior might not be allowed at all in RSpec 4, a stricter prevention mechanism would only encourage a smoother transition in an upgrade.

**Comment by JonRowe** [comment]
I like `on_potential_false_positives = :warn | :raise`, and we could remove `warn_about_potential_false_positives` later on.

**Comment by mknapik** [comment]
:+1:

**Comment by chrisarcand** [comment]
Thanks @JonRowe !
