### ISSUE TITLE
Missing output to stderr matcher

### ISSUE THREAD

**Issue by hjkatz** [rspec/rspec-expectations#903]
I have a spec example defined as follows:

```
describe "#sync" do
    it "must be run as root" do
      expect {
        begin @sync.invoke( :sync )
        rescue SystemExit
        end
      }.to output( /must run as root/i ).to_stderr_from_any_process
    end   
  end  
```

My thor `:sync` task is defined as follows:

```
    def sync
      abort "Must run as root" unless Process.euid == 0

      ...
    end 
```

I expect this test to pass, instead it fails:

```
Failure/Error:
       expect {
         begin @sync.invoke( :sync )
         rescue SystemExit
         end
       }.to output( /must run as root/i ).to_stderr_from_any_process
     
       expected block to output /must run as root/i to stderr, but output nothing
       Diff:
       @@ -1,2 +1,2 @@
       -/must run as root/i
       +""
```

Stating that it does not see any output to stderr. However when I run `rspec spec 1>/dev/null 2>/tmp/stderr` the words "Must be run as root" do not get filtered and appear in `/tmp/stderr`.

Expected: The test should pass, I'm printing to stderr in a thread wrapped in the expect block.

Actual: The test fails stating that there was no output found.

**Comment by myronmarston** [comment]
I've tried to repro this with a snippet like:

``` ruby
class Sync
  def invoke(_)
    abort "must run as root"
  end
end

RSpec.describe "#sync" do
  it "must be run as root" do
    expect {
      begin
        Sync.new.invoke( :sync )
      rescue SystemExit
      end
    }.to output( /must run as root/i ).to_stderr_from_any_process
  end
end
```

...and it passes.  Can you provide a reproducible example (or edit mine until you get it to the point where it reproduces the issue)?

**Comment by hjkatz** [comment]
Does it continue to work if Sync is a Thor class? I think that might be causing the issue.

```
require "thor"
require "rspec"

class Sync < Thor
  desc "sync", "fake description here"
  def sync
    abort "must run as root"
  end
end

RSpec.describe "#sync" do
  it "must be run as root" do
    expect {
      begin
        Sync.new.invoke( :sync )
      rescue SystemExit
      end
    }.to output( /must run as root/i ).to_stderr_from_any_process
  end
end
```

**Comment by myronmarston** [comment]
I tried your snippet and it's still passing for me.  I suspect there might be some ruby and gem versions at play here, where this happens with some combination of versions and not with others.  Can you create a gist or a github repo with the snippet, a `Gemfile` and `Gemfile.lock` and link to it from here?  (And please list your ruby version in that as well).

**Comment by hjkatz** [comment]
The issue was a misunderstanding of how Thor invoke works. Invocations will only occur one time to avoid duplicates. In my spec example I had 2 invocations, therefore the second one would do nothing. Sorry bout this :)

**Comment by myronmarston** [comment]
No worries!  In the future please try to get your problem into an isolated reproducible snippet. Having such a snippet helps maintainers of a project repro your problem (and hopefully solve it) quickly and sometimes (as in your case) going through that exercise helps you realize there's something else going on entirely.
