### ISSUE TITLE
The `raise_block_syntax_error` message too confident.

### ISSUE THREAD

**Issue by alexaltair** [rspec/rspec-expectations#907]
I'd like to suggest changing the message for this error (currently [here](https://github.com/rspec/rspec-expectations/blob/52bfebf53e8025371d2869aac2b9f272e5b60f3/lib/rspec/matchers/built_in/change.rb#L89)) which says "The block passed to the \`change\` matcher must use \`{ ... }\` instead of do/end".

My first thought was, "How does it know??" because I didn't expect the ruby parser to pass that information on. As it turns out, it doesn't know for sure, it just guesses based on which method received the block argument (discussion [here](https://github.com/rspec/rspec-expectations/issues/137#issuecomment-46356503)). This means that false positives and negatives are possible.

This passes;
```ruby
expect{ subject }.to((change do some_query.count end).by(1))
```

and this fails with the `raise_block_syntax_error`;
```ruby
expect{ subject }.to(change) { some_query.count }.by(1)
```

I'd like the message to say something like, "The \`to\` method does not take a block. Perhaps you used do/end instead of \`{ ... }\`?" (Feel free to close if this issue has been discussed and decided before.)

**Comment by myronmarston** [comment]
If the error message is confusing, I definitely want to see it change.  Want to work up a PR?

**Comment by JonRowe** [comment]
Closing in favour of #908
