### ISSUE TITLE
expect when syntax

### ISSUE THREAD

**Issue by abrom** [rspec/rspec-expectations#924]
This is something I've been thinking about as an extension to the expect syntax to help in dry'ing up repetitive specs. 

The gist of the syntax is `expect(foo).when(flag).to eq bar`

Essentially when `flag` is true, the test would be equivalent to `expect(foo).to eq bar`. When it's false, equivalent to `expect(foo).not_to eq bar`

Until now I've been writing this as `expect(foo).send(flag ? :to : :not_to, eq(bar))` but it looks nasty and it feels nasty

A (very) simple example of its use might be something like:

```
['Bob', 'John'].each do |name|
  let(:is_a_beatle_name) { ['John', 'Paul', 'Ringo', 'George'].include? name }

  subject { name.length }
  it { is_expected.when(is_a_beatle_name).to be_between(4, 6).inclusive
end
```

Basic implementation would be along the lines of (over simplified of course):

```
module RSpec
  module Expectations
    class ExpectationTarget
      def when(expected)
        WhenExpectationTarget.new @target, expected
      end
    end

    class WhenExpectationTarget < ExpectationTarget
      def initialize(value, when_expected)
        @target = value
        @when_expected = when_expected
      end

      alias_method :expect_to, :to
      alias_method :expect_not_to, :not_to

      def to(matcher=nil, message=nil, &block)
        send(@when_expected ? :expect_to : :expect_not_to, matcher, message, &block)
      end

      def not_to(matcher=nil, message=nil, &block)
        send(@when_expected ? :expect_not_to : :expect_to, matcher, message, &block)
      end
      alias to_not not_to
    end
  end
end
```

Happy of course to write it up properly with a PR but just wanted to get some feedback first

**Comment by myronmarston** [comment]
It's an interesting idea, but I can't think of a single time I've ever wanted functionality like this.  And I think the meaning/purpose of `when` is not immediately clear (it requires an explanation).

IMO, this is a great idea for an extension.  If it sees significant use among the community we can consider including it in rspec-expectations in a future release.

**Comment by abrom** [comment]
No problems, fair call. I'll have a bit more of a think about it but will take your suggestion to build it as an extension. Thanks

**Comment by abrom** [comment]
FYI I've built this as a gem, available here: https://github.com/abrom/rspec-when (or rubygems)

I ended up going with `expect(foo).when(flag).to .. ` to equate to `expect(foo).to .. if flag`.  Then added `with_inverse` (to be more explicit) to test the negative case when the flag is false. ie `expect(foo).when(flag).with_inverse.to ...`
