### ISSUE TITLE
::Rspec.configuration calling Ruby's ::MakeMakefile.configuration

### ISSUE THREAD

**Issue by reedlaw** [rspec/rspec-expectations#927]
I'm getting this backtrace from a cucumber test:

    Then I should see "Thanks for signing up!"                        # features/step_definitions/web_steps.rb:105
      wrong number of arguments (given 0, expected 1) (ArgumentError)
      /usr/lib/ruby/2.3.0/mkmf.rb:1887:in `configuration'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/configuration.rb:66:in `color?'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:8:in `differ'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:25:in `fail_with'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
      /home/reed/.gem/ruby/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
      /home/reed/sb/ampms/features/step_definitions/web_steps.rb:106:in `block in <top (required)>'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/core_ext/instance_exec.rb:48:in `instance_exec'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/core_ext/instance_exec.rb:48:in `block in cucumber_instance_exec'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/core_ext/instance_exec.rb:69:in `cucumber_run_with_backtrace_filtering'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/core_ext/instance_exec.rb:36:in `cucumber_instance_exec'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_step_definition.rb:97:in `invoke'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/step_match.rb:25:in `invoke'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/step_invocation.rb:60:in `invoke'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/step_invocation.rb:38:in `accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:106:in `block in visit_step'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:105:in `visit_step'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/step_collection.rb:19:in `block in accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/step_collection.rb:18:in `each'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/step_collection.rb:18:in `accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:100:in `block in visit_steps'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:99:in `visit_steps'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:15:in `block in execute'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:83:in `block (2 levels) in with_hooks'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:99:in `before_and_after'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:82:in `block in with_hooks'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:120:in `block (3 levels) in around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/language_support/language_methods.rb:9:in `block in around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/language_support/language_methods.rb:97:in `execute_around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/language_support/language_methods.rb:8:in `around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:119:in `block (2 levels) in around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:123:in `around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:94:in `around'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:81:in `with_hooks'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:13:in `execute'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/scenario.rb:32:in `block in accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/scenario.rb:79:in `with_visitor'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/scenario.rb:31:in `accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:58:in `block in visit_feature_element'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:57:in `visit_feature_element'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/feature.rb:38:in `block in accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/feature.rb:37:in `each'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/feature.rb:37:in `accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:27:in `block in visit_feature'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/features.rb:28:in `block in accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/features.rb:17:in `each'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/features.rb:17:in `each'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/features.rb:27:in `accept'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:21:in `block in visit_features'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:49:in `run!'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in `execute!'
      /home/reed/.gem/ruby/2.3.0/gems/cucumber-1.3.20/bin/cucumber:13:in `<top (required)>'
      /home/reed/.gem/ruby/2.3.0/bin/cucumber:23:in `load'
      /home/reed/.gem/ruby/2.3.0/bin/cucumber:23:in `<main>'
      features/registration.feature:33:in `Then I should see "Thanks for signing up!"'

The code from `rspec-expectations` has the correct namespace but somehow is calling another method which returns the argument error. This only happens on one test

**Comment by JonRowe** [comment]
It looks like you're using `rspec-expectations` without `rspec-core` but somehow `#configuration` has been defined on `RSpec` to be from `mkmf`, are you including modules into main anywhere? (e.g. a include / extend call in any file in your cucumber support on the raw file, or a World call with that module)

**Comment by reedlaw** [comment]
I'm using `rspec-rails` 3.4.2 which includes both `rspec-core` and `rspec-expectations` (3.4.0). I'm not including modules (certainly not MakeMakefile).

**Comment by reedlaw** [comment]
After upgrading/removing various gems the problem resolved itself. Unfortunately I'm not sure which gem was the culprit.

**Comment by kmazanec** [comment]
Encountered this same issue with cucumber/capybara/rspec, was able to resolve by explicitly requiring `rspec-expectations` before the `rspec-rails` gem.

```ruby
group :development, :test do
  ...
  gem "rspec-expectations"
  gem "rspec-rails", "~> 3.5"
  ...
end
```
