### ISSUE TITLE
Make .to (expected changed value) accept a block

### ISSUE THREAD

**Issue by vemv** [rspec/rspec-expectations#932]
Hi there!

I have a feature request which hopefully isn't a dupe. Was hard to google.

I use `.to change {...}.from(x).to(y)` a lot. Occasionally I need the second `.to` to accept a block instead of a value.

Something like:

`expect {...}.to change {...}.from(x).to{...}`
## Sample use case

Imagine a capybara spec for an ajax functionality. The ajax widget creates a `MyModel` (an ActiveRecord object) and displays its generated id on screen.

One could test it with:

``` ruby
expect {
  find("#the_widget").click # capybara api
}.to change {
  find("#the_id").value # capybara api
}.from("").to(MyModel.last.id.to_s)
```

This snippet would not work, because at the time RSpec reads this ruby code, `MyModel.last.id.to_s` will have a different value than seconds later, when `find("#the_widget").click` is executed.

So I'd want to solve it by making `.to` accept a block:

``` ruby
expect {
  find("#the_widget").click # capybara api
}.to change {
  find("#the_id").value # capybara api
}.from("").to {
  MyModel.last.id.to_s
}
```

The point being that the call to this `.to` block is deferred until the very last moment.

---

I hope my example was clear enough and that you find the feature worth it.

Cheers - Victor

**Comment by myronmarston** [comment]
You can pass any object that implements `===` to `from` or `to`.  This includes things like regular expressions, ranges, and RSpec matchers,  It also includes 1-arg lambdas:

``` ruby
expect {
  find("#the_widget").click # capybara api
}.to change {
  find("#the_id").value # capybara api
}.from("").to(lambda { |id| id == MyModel.last.id.to_s })
```

**Comment by vemv** [comment]
Good enough - thanks much!

Victor

**Comment by vemv** [comment]
I'm not sure accepting lambdas/procs is an ideal API.

Sometimes they work as expected, but often I get these:

`expected result to have changed to #<Proc:0x007f8cbbbfa398>, but is now "€8.006,41"`

One can understand this error - a proc is an object like any other, so RSpec can feel tempted to compare the proc with a string, instead of invoking the proc.

Two real failing examples:

* `}.from(old_value).to(lambda { |v| v == new_value.format })`
* `.from(old_id).to(->(id){ id == MyModel.last.id.to_s })`

Any idea on how to get them to work?

Would appreciate if we reopen the issue.

Cheers - Victor

**Comment by myronmarston** [comment]
Can you provide a reproducible example of a case that isn't working as you expect?

**Comment by pirj** [comment]
I couldn't get it to fail:
```ruby
RSpec.describe 'change to lambda' do
  it do
    @a = 0
    expect { @a = 1 }
      .to change { @a }.to(->(_a) { @a })
      .and change { @a }.to(lambda { |_a| @a })
  end
end
```

Let's close for now, since there's no clear reproduction example.

**Comment by sebastian-palma** [comment]
Seems to fail when the value is defined in `let` or `let!`;

```ruby
let(:a) { 0 }
it do
  expect { a = 1 }.to change { a }.to(-> { a })
end

# Failure/Error: expect { a = 1 }.to change { a }.to(-> { a })
#        expected `a` to have changed to #<Proc:0x00007ffff4d5e0c0 /file.rb:3 (lambda)>, but did not change
```

**Comment by JonRowe** [comment]
You are likely running into variable shadowing / precedence rules there, `a = 1` assigns a local variable called `a` within the block which you've set to one, but the change block and to lambda are not in the same scope so they see the method `a`, you can't change let values.
