### ISSUE TITLE
yield matcher with a custom block/probe

### ISSUE THREAD

**Issue by linkyndy** [rspec/rspec-expectations#933]
I need to test that a method yields specific arguments, but I also want to do something custom in the block to which the method yields (i.e.: raise an error).

So, normally I would call my method like:

```ruby
subject.retry_with_fallbacks([:a_fallback, :another_fallback], max_attempts: 2) do |fallback, attempts|
  # ...
  raise TestError
end
```

How can I achieve this with the `yield` matchers? I only have the probe, but it seems I can't "publicly" modify its corresponding Proc. The only way I see dealing with this is tampering with [`@block`](https://github.com/rspec/rspec-expectations/blob/e8e90cce3dfddab3ecd5b3c98559d384530daf8d/lib/rspec/matchers/built_in/yield.rb#L23), but I hope there is a better approach to it.

**Comment by myronmarston** [comment]
Our `yield` matchers aren't really designed for this, but you could do:

``` ruby
expect do |probe|
  subject.retry_with_fallbacks([:a_fallback, :another_fallback], max_attempts: 2) do |fallback, attempts|
    probe.to_proc.call(fallback, attempts)
    raise TestError
  end
end.to some_yield_matcher
```

**Comment by linkyndy** [comment]
Although it's not as good looking as the rest of RSpec, it does its job. Thank you!

Maybe there are plans of adding this functionality as well.
