### ISSUE TITLE
expect { }.to call(thing, :method) matcher

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-expectations#934]
Didn't see any issues for this and haven't seen the functionality documented anywhere. We've been playing around with the new expectation syntax:

```ruby
allow(thing).to receive(:something).and_return('blah')
do_the_thing
expect(thing).to have_received(:something)
```

Which feels a little like too much work, so we often go with the old style:

```ruby
expect(thing).to receive(:something).and_return('blah')
do_the_thing
```

What would be really nice is to have a block-style expectation matcher:

```ruby
expect {
  do_the_thing
}.to call(thing, :something).and_return('blah')
```

We could probably build this out ourselves as a custom matcher, but thought it would be nice as part of RSpec.

**Comment by JonRowe** [comment]
Hi, with submissions like this is normal for us to ask you to build it as a custom matcher, (maybe even publish it as a gem / micro gem) for a while first, to see how this would work / popularity etc.

Some things to consider here:

- Naming, `call(thing, :something)` isn't overly clear or expressive, (and conflicting with proc syntax). `call(:something, on: thing)` is a bit better but still has the proc syntax conflict... 

- The need to wrap the block expectation in a mocks scope, for this syntax to make sense in the wider RSpec ecosystem it's side-effects should be contained the block inside it, This would make nested usage of this matcher ugly but it would be the correct course of action.

**Comment by mockdeep** [comment]
Yeah, I thought the naming piece might be a bit off. I could see changing it to something like `call_method(:something).on(thing)` or `send_message(:something).to(thing)`.

Not sure I understand your second point, though. Can you clarify?

I'll play around with creating it as a custom matcher in our own codebase.

**Comment by JonRowe** [comment]
Personally I'd avoid `call` altogether, `perform(:method).on(thing)`?
On the second point:

```
expect {
  do_the_thing
}.to call(thing, :something).and_return('blah')
```

**Comment by mockdeep** [comment]
Oh, yeah, I see what you're saying. Not sure which way makes sense, and I'm not too familiar with the scoping rules for mocking. I pretty much operate on the assumption that the method is useless at that point unless you tack on a `.and_call_original`, but maybe it makes sense to unwrap it after the block.

**Comment by mockdeep** [comment]
(probably easier to not worry about it though...)

**Comment by mockdeep** [comment]
`perform` sounds a bit funny, though... `perform(:first_name).on(user)`? Other alternatives: `invoke`, can we use `send`, or does that have similar problems to `call`? Another possibility might be to add it on the mock instead? I guess we want the expectation to come at the end, though:

```ruby
expect(thing).to receive(:something) do
  do_the_thing
end
```

**Comment by JonRowe** [comment]
This:
```Ruby
expect(thing).to receive(:something) do
  do_the_thing
end
```

Already exists, but would make `thing.something` return `do_the_thing`

**Comment by mockdeep** [comment]
Ah, oops. Yeah, forgot about that.

**Comment by myronmarston** [comment]
FWIW, when we first introduced spying features, we discussed a very similar syntax to what you've suggested (see #220), but decided to go with a simple `have_received` matcher.  The main reasons are:

* A block form doesn't provide an easy way to configure how the spy should respond to the messages -- whereas that's not a problem at all with the direction we went.
* A block form can get unwieldy when there are multiple messages in play, where as having multiple `expect(...).to have_received(...)` calls in a row is far less unwieldy.
* RSpec's spying features work best when dealing with _command_ methods (where there isn't a meaningful return value) and you can therefore use a simple `spy` with no need to configure how it responds:

``` ruby
ledger = spy("Ledger")
process_transaction_with(ledger)
expect(ledger).to have_received(:record).with(transaction)
```

(notice that we don't need to `allow` anything on the ledger).

Overall, I don't think a block form buys us anything significant over what we have now, and it seems to me to be less flexible.  In addition, if we added it, it would be yet another thing for our users to need to learn--which to me is a hard sell given there aren't notable benefits over what we already have.  So I'm inclined not to add support for this to RSpec.  I think it could make a great extension gem, though.

**Comment by mockdeep** [comment]
@myronmarston agreed on the first point. It would be probably be hard to do anything more complicated, but for simpler things it feels like it adds convenience and nicely parallels the `change` matchers.

> A block form can get unwieldy when there are multiple messages in play, where as having multiple expect(...).to have_received(...) calls in a row is far less unwieldy.

With this, I guess I don't see it being a whole lot more complicated than the `change` matchers:

```ruby
expect {
  do_something
}.to change(foo, :bar).from('blah').('bloo')
  .and change(foo, :baz).from('woo').('wah')

expect {
  do_the_thing
}.to invoke(:something).on(thing).and_return('blah')
  .and invoke(:something_else).on(other_thing)
```

> RSpec's spying features work best when dealing with command methods (where there isn't a meaningful return value) and you can therefore use a simple spy with no need to configure how it responds

Even with this example, I would see wanting to wrap it for clarity, in the same way we would with the change matchers:

```ruby
ledger = spy("Ledger")
expect {
  process_transaction_with(ledger)
}.to invoke(:record).on(ledger).with(transaction)
```

For better or worse, though, our code has a lot of places where simply passing in a spy isn't an option for us at the moment. I'll play around with it and post back if I manage to come up with something.

**Comment by JonRowe** [comment]
It's more complex than `change` due to the fact mocks are more complication than simple assertions, but I encourage you to create this as an extension! Please leat us know if you need any help!

**Comment by mockdeep** [comment]
@JonRowe @myronmarston Okay, I've got a basic working implementation. I wasn't able to come up with a way to do it cleanly without digging into a private API, though. Ended up using `RSpec::Mocks::Matchers::HaveReceived`. Would love feedback:

```ruby
module Chalk
  module Matchers
    class Invoke
      include RSpec::Mocks::ExampleMethods

      def initialize(expected_method)
        @expected_method = expected_method
      end

      def matches?(event_proc)
        raise "missing '.on'" unless defined?(@expected_recipient)
        allow(@expected_recipient).to receive(@expected_method)
        event_proc.call
        have_received_matcher.matches?(@expected_recipient)
      end

      def on(expected_recipient)
        @expected_recipient = expected_recipient
        self
      end

      def with(*expected_arguments)
        @expected_arguments = expected_arguments
        self
      end

      def failure_message
        received_matcher.failure_message
      end

      def failure_message_when_negated
        received_matcher.failure_message_when_negated
      end

      def supports_block_expectations?
        true
      end

    private

      def have_received_matcher
        @have_received_matcher ||= begin
          matcher = RSpec::Mocks::Matchers::HaveReceived.new(@expected_method)
          if defined?(@expected_arguments)
            matcher = matcher.with(*@expected_arguments)
          end
          matcher
        end
      end
    end
  end
end

def invoke(expected_method)
  Chalk::Matchers::Invoke.new(expected_method)
end
```

**Comment by JonRowe** [comment]
If you check out the internals of mocks you should see theres ways to setup allowance / expectation targets without mixing in ExampleMethods

**Comment by mockdeep** [comment]
@JonRowe sorry for the delay, just getting back to this. Are you referring to using `AllowanceTarget` and `Matchers::Receive` directly? I replaced the `include` with the following methods and that did the trick for me:

```ruby
def allow(target)
  RSpec::Mocks::AllowanceTarget.new(@expected_recipient)
end

def receive(method_name)
  RSpec::Mocks::Matchers::Receive.new(method_name, nil)
end
```

I was trying to avoid using internal APIs, but I guess in for a penny, in for a pound.

**Comment by seanlinsley** [comment]
I was looking for this, as a way to better communicate which part of large test is intended to cause a particular change. I ended up extending it a little more to support `and_call_original` and to provide a negated matcher.

The only problem I noticed is that the matcher doesn't respond to `and`, so when combining matchers it can't be the first matcher.

```ruby
# Adapted from: https://github.com/rspec/rspec-expectations/issues/934
#
# expect{ foo }.to invoke(:method).on(Class).and_call_original
#
# expect{ foo }.to change{ bar }.and not_invoke(:method).on(Class)
#
class InvokeMatcher
  def initialize(expected_method)
    @expected_method = expected_method
  end

  def matches?(event_proc)
    fail 'missing `on`' unless defined?(@expected_recipient)

    stub = allow(@expected_recipient).to receive(@expected_method)
    stub.and_call_original if @call_original

    event_proc.call

    have_received_matcher.matches?(@expected_recipient)
  end

  def on(expected_recipient)
    @expected_recipient = expected_recipient
    self
  end

  def with(*expected_arguments)
    @expected_arguments = expected_arguments
    self
  end

  def failure_message
    have_received_matcher.failure_message
  end

  def failure_message_when_negated
    have_received_matcher.failure_message_when_negated
  end

  def supports_block_expectations?
    true
  end

  def and_call_original
    @call_original = true
    self
  end

  def allow(_target)
    RSpec::Mocks::AllowanceTarget.new(@expected_recipient)
  end

  def receive(method_name)
    RSpec::Mocks::Matchers::Receive.new(method_name, nil)
  end

private

  def have_received_matcher
    @have_received_matcher ||= begin
      matcher = RSpec::Mocks::Matchers::HaveReceived.new(@expected_method)
      if defined?(@expected_arguments)
        matcher = matcher.with(*@expected_arguments)
      end
      matcher
    end
  end
end

def invoke(expected_method)
  InvokeMatcher.new(expected_method)
end

RSpec::Matchers.define_negated_matcher :not_invoke, :invoke

**Comment by gabteles** [comment]
Hi folks, as I was also searching for a matcher like this, I've improved @seanlinsley version to fallback to `HaveReceived` constraint methods, then you can end up with more complex expectations, like the one below, not limiting only to `.and_call_original`.

```ruby
expect{ foo }.to invoke(:method).on(Class).at_least(3).times`
```

Fell free to modify this code.

```ruby
# Adapted from: https://github.com/rspec/rspec-expectations/issues/934
#
# expect{ foo }.to invoke(:method).on(Class).and_call_original
#
# expect{ foo }.to change{ bar }.and not_invoke(:method).on(Class)
#
# expect{ foo }.to invoke(:method).on(Class).at_least(3).times
#
class InvokeMatcher
  def initialize(expected_method)
    @expected_method = expected_method
    @have_received_matcher = RSpec::Mocks::Matchers::HaveReceived.new(@expected_method)
  end

  def description
    raise 'missing `on`' unless defined?(@expected_recipient)
    "invoke #{@expected_method} on #{expected_recipient.inspect}"
  end

  def method_missing(name, *args, &block)
    raise 'missing `on`' unless defined?(@expected_recipient)
    super unless respond_to_missing?(name)
    @have_received_matcher = @have_received_matcher.public_send(name, *args, &block)
    self
  end

  def respond_to_missing?(name, *args)
    @have_received_matcher.respond_to?(name, *args)
  end

  def matches?(event_proc)
    raise 'missing `on`' unless defined?(@expected_recipient)

    unless @expected_recipient.is_a?(RSpec::Mocks::Double)
      allow(@expected_recipient).to receive(@expected_method).and_call_original
    end

    event_proc.call

    @have_received_matcher.matches?(@expected_recipient)
  end

  def on(expected_recipient)
    @expected_recipient = expected_recipient
    self
  end

  def failure_message
    @have_received_matcher.failure_message
  end

  def failure_message_when_negated
    @have_received_matcher.failure_message_when_negated
  end

  def supports_block_expectations?
    true
  end

  def allow(_target)
    RSpec::Mocks::AllowanceTarget.new(@expected_recipient)
  end

  def receive(method_name)
    RSpec::Mocks::Matchers::Receive.new(method_name, nil)
  end
end

def invoke(expected_method)
  InvokeMatcher.new(expected_method)
end

RSpec::Matchers.define_negated_matcher :not_invoke, :invoke
```

**Comment by albertoalmagro** [comment]
I see there was still conversation here after closing this issue, but I found neither PR nor reference in the code base for this. How is the status?

**Comment by mikegee** [comment]
@albertoalmagro the maintainers encouraged developing an extension to RSpec. So far, that work is just in these comments (copied into individual projects). Would you like to package it into a gem?

**Comment by mockdeep** [comment]
Came across this gem [Saharspec](https://github.com/zverok/saharspec#matchers) this morning that has a similar matcher. I'll also probably add it to [JunkDrawer](https://github.com/thread-pond/junk_drawer) eventually.

**Comment by khiav223577** [comment]
> Hi folks, as I was also searching for a matcher like this, I've improved @seanlinsley version to fallback to `HaveReceived` constraint methods, then you can end up with more complex expectations, like the one below, not limiting only to `.and_call_original`.
> 
> ```ruby
> expect { foo }.to invoke(:method).on(Class).at_least(3).times
> ```
@gabteles 

How can I modify it to support any_instance? Any hints?
e.g.
```rb
expect{ something }.to invoke(:method).on_any_instance_of(Class).at_least(3).times
```

**Comment by JonRowe** [comment]
@khiav223577 You need to swap out the allowance code:

```
  def allow(target)
    AnyInstanceAllowanceTarget.new(target)
  end
```
