### ISSUE TITLE
Remove support from dynamic predicate matchers for present-tense predicate

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-expectations#935]
https://github.com/rspec/rspec-expectations/blob/a271631e9b8e1749be876dbcc65dbd7a6a40d2db/lib/rspec/matchers/built_in/be.rb#L248-L250

It's confusing and can lead to bugs like rspec/rspec-rails#1681.  It should be removed from RSpec 4 and deprecated in RSpec 3.99.

**Comment by pirj** [comment]
Fixed in #1286 (to be released as part of 4.0).
