### ISSUE TITLE
Consider improving failure message of #change matcher by extracting block snippets

### ISSUE THREAD

**Issue by yujinakayama** [rspec/rspec-expectations#937]
Currently failure message of the `change` matcher _with a block_ is sometimes unclear:

``` ruby
RSpec.describe '#do_something' do
  def do_something
    @foo = true
    @bar = false
  end

  before do
    @foo = false
    @bar = false
  end

  it 'changes @foo and @bar' do
    expect { do_something }.to change { @foo }
                          .and change { @bar }
  end
end
```

```
Failures:

  1) #do_something changes @foo and @bar
     Failure/Error:
       expect { do_something }.to change { @foo }
                             .and change { @bar }

       expected result to have changed, but is still false
```

It's not clear which the cause is `@foo` or `@bar` from the failure message. This is because RSpec does not know the snippets of the blocks and can only express them as `result`.

However, as we have introduced snippet extraction in https://github.com/rspec/rspec-core/pull/2083, extracting the block snippet may be possible in some cases.

I [tried implementing a prototype](https://github.com/rspec/rspec-expectations/commit/extract-block-snippet) and it seems to be working well. With the prototype, the above spec is reported as:

```
Failures:

  1) #do_something changes @foo and @bar
     Failure/Error:
       expect { do_something }.to change { @foo }
                             .and change { @bar }

       expected `@bar` to have changed, but is still false
```

@rspec/rspec What do you think?

**Comment by JonRowe** [comment]
I like this idea @yujinakayama

**Comment by myronmarston** [comment]
I like the improved output _a lot_, but I worry slightly about the difficulty of maintaining the code for this.  I'm not sure I'd be very effective at troubleshooting and fixing bugs in the code that supports this...

**Comment by yujinakayama** [comment]
> but I worry slightly about the difficulty of maintaining the code for this.

Though in some cases extracting the block snippets may be difficult (mainly because of lack of column information in `Proc#source_location`), we can fallback to the `result` in that cases since the snippets are provided through failure message, not as a public API.

**Comment by myronmarston** [comment]
Good point.  The other thing that worries me is that your prototype relies upon `RSpec.world.source_cache` from rspec-core.  If we move forward with this we'll have to decide if it makes sense to move the source cache stuff to rspec-support or if the code in rspec-expectations should be written to conditionally do this only if rspec-core is loaded (similar to the [color?](https://github.com/rspec/rspec-expectations/blob/a271631e9b8e1749be876dbcc65dbd7a6a40d2db/lib/rspec/expectations/configuration.rb#L72-L88) definition).
