### ISSUE TITLE
Allow `to_output` to accept multiple arguments

### ISSUE THREAD

**Issue by malclocke** [rspec/rspec-expectations#943]
Hi folks,

Would you be willing to accept a PR that allows the following?

    expect { some_method }.to_output(/This stuff/, /and this stuff/).to_stdout

As `to_output` currently only accepts one argument, the only solution I can see is to do the following:

    expect { some_method }.to_output(/This stuff/).to_stdout
    expect { some_method }.to_output(/and this stuff/).to_stdout

and this is less than ideal when `some_method` is expensive.

**Comment by myronmarston** [comment]
This is already supported by passing a compound matcher:

``` ruby
expect { some_method }.to_output(
  a_string_matching(/This stuff/).and matching(/and this stuff/
).to_stdout
```
