### ISSUE TITLE
is_expected.to have_sent_email.from('test@localhost') instantiates subject

### ISSUE THREAD

**Issue by ioquatix** [rspec/rspec-expectations#946]
I'm testing a subject which can't be instantiated normally, but it's still the central object being tested (it's instantiated as part of a mock-up rack app).

I want to test if the middleware has sent an email or not.

is_expected instantiates the subject whether or not it's actually used.

It's not possible to write `expect.to` but it does work correctly if I write `expect(true).to ...`.

Perhaps it should be possible to write simply `expect.to` which is similar to is_expected but doesn't instantiate subject, or perhaps subject should be lazily initialised when calling `is_expected`. Right now, `is_expected` is equivalent to `expect(subject)`. What about if it was `expect{subject}`?

**Comment by JonRowe** [comment]
`is_expected` is only intended for use as an `expect(subject).to` short cut, it's a left over from RSpec 2 supporting old school one liner snippets; Changing it would break existing test suites, in any case this isn't considered good practise any more and is not recommended. 

Try:

```Ruby
expect { action_that_sends_email }.to whatever_matcher_your_using
````

I'm a little curious what your matcher is here, as mostly they expect a value from expect.

**Comment by ioquatix** [comment]
Here is what the final spec looks like:

```
	it "should send an email to report the failure" do
		expect{get "/blow"}.to raise_error('Arrrh!')
		
		last_mail = Mail::TestMailer.deliveries.last
		
		expect(last_mail.to_s).to include("GET", "blow", "request.ip", "HTTP_", "TharSheBlows")
	end
```

However, there are helpers listed here: https://github.com/mikel/mail#using-mail-with-testing-or-specing-libraries

The idea is that you are just asking general questions about the email that was sent.

Ideally you could match the existing syntax but it's not possible without the implicit instantiation of `subject`.

**Comment by JonRowe** [comment]
The documentation you linked to is using the old syntax, but you can achieve that style by adding `subject { nil }` of by using a string description e.g.

```Ruby
RSpec.describe 'MyClass'
```

**Comment by ioquatix** [comment]
@JonRowe I guess my point was the two solutions you list are not really that good. Ideally, is_expected should not implicitly instantiate subject unless it's actually required to do so.

**Comment by myronmarston** [comment]
The _entire_ point of `is_expected` is that it's a short-cut for setting expectations on the subject.  The idea of using it to set an expectation on something else goes entirely against its purpose and, IMO, makes no sense.  We've documented it as being equivalent to `expect(subject)` so it would be very confusing for it to do anything more clever.

If you want it to do something different, you can override it in your project or publish a gem that does so:

``` ruby
module IsExpectedOverride
  def is_expected
    # do whatever you want
  end
end

RSpec.configure do |c|
  c.include IsExpectedOverride
end
```

**Comment by ioquatix** [comment]
Right, that makes sense. So, perhaps we should improve the documentation of the mail gem. What would be the best way for the mail gem to document support for rspec given that it's working with global state?

**Comment by myronmarston** [comment]
> Right, that makes sense. So, perhaps we should improve the documentation of the mail gem. What would be the best way for the mail gem to document support for rspec given that it's working with global state?

Expectations are intended to be made about something specific.  Instead of having the matchers ignore the argument passed to `expect`, I think the mail gem should provide an API to access the state the matchers are intended to match against.  For example, maybe something like a `delivered_email` method.  Then you could write expectations like:

``` ruby
expect(delivered_email).to matcher
```

Or wrap that in `subject` if you want to use the one-liners:

``` ruby
subject { delivered_email }
it { is_expected.to matcher }
```

**Comment by ioquatix** [comment]
@myronmarston That makes sense. Perhaps it would make sense for there to be a local mailbox for testing, e.g.

```
let(:test_mailbox) {Mail::TestMailbox.new}

...
mail = Mail.new (..., delivery_method: test_mailbox)

expect(test_mailbox).to_not be_empty
```

**Comment by myronmarston** [comment]
Yep.
