### ISSUE TITLE
Unexpected tIDENTIFIER for standard expect()

### ISSUE THREAD

**Issue by Portalboy** [rspec/rspec-expectations#950]
_I'm ticket #950? I feel special!_
I am getting the following error when attempting to run my test suite:

```
*path*/button_test_spec.rb:57: syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)
			expect(postSearchValue)not_to eq(preSearchValue)
										 ^
```

![unexpectedtidentifier](https://cloud.githubusercontent.com/assets/6773480/19325613/9336eef6-908c-11e6-9871-3f3de399350c.png)

Here is the context with the offending test, for good measure:

```
context "Reset button" do
	  
	  before :all do
		clientLastField = input("ctl00_PageContent_ASPxGridView1_DXFREditorcol7_I")
		clientLastXpath = ".//*[@id='ctl00_PageContent_ASPxGridView1_DXDataRow0']/td[6]"
		@preSearchValue = xpathify(clientLastXpath)
		clientLastField.set "John"
		send_keys :return
		@postSearchValue = xpathify(clientLastXpath)
		
	  end
	  
	  before :each do
		@clientLastField = input("ctl00_PageContent_ASPxGridView1_DXFREditorcol7_I")
		@clientLastXpath = ".//*[@id='ctl00_PageContent_ASPxGridView1_DXDataRow0']/td[6]"
	  end
	  
	  it "searches a Last Name to populate a filter" do
		preSearchValue = xpathify(@clientLastXpath)
		clientLastField.set "John"
		send_keys :return
		postSearchValue = xpathify(@clientLastXpath)
		expect(postSearchValue)not_to eq(preSearchValue)
	  end
	  
	end

```

Firstly, if you'd like to critique my obviously beginner suite layout, I welcome it; I'm struggling to find the optimal way of structuring my ``describe``s, ``context``s and ``it``s.
Secondly, why is this error occurring? Isn't this perfectly normal syntax?

**Comment by Portalboy** [comment]
It may also be good to note that there are some Domain Specific elements to my code:
input() is actually a shortening of Watir::Browser.input()
send_keys :return is also for Watir::Browser
xpathify() uses xpath to parse a value found on a webpage and return a string.

**Comment by mrageh** [comment]
` expect(postSearchValue).not_to eq(preSearchValue)`, you're missing a period before `not_to`, that maybe causing the error above.

**Comment by myronmarston** [comment]
@mrageh is correct.   Any time you see an error like `syntax error, unexpected t<token>...` it is an error happening in the ruby parser, that a particular library like RSpec can do nothing about.  In this case, `token(args)token` (e.g. `expect(postSearchValue)not_to`) is invalid ruby syntax.  It should be `token(args).token` (e.g. `expect(postSearchValue).not_to`).

**Comment by Portalboy** [comment]
Wow, I can't believe I missed that.
Thanks guys! Hopefully this will help Googlers unfortunate enough to have made the same mistake.
