### ISSUE TITLE
Response with wrong body

### ISSUE THREAD

**Issue by FlorianGerhardt** [rspec/rspec-expectations#957]
Hey there!
I'm getting errors when I'm checking the update action of my controller, it seems to me that the response in the expectation differs from the actual response.

The spec: 
```

let (:project) { Project.create! valid_attributes }

let(:valid_attributes) {
    { title: 'title', description: 'description'}
  }

let(:new_attributes) {
    { title: 'title-updated', description: 'description-updated' }
  }

it "updates the requested project" do
     
      put :update, id: project.to_param, project: new_attributes

      expect(response.body['title']).to eq(new_attributes[:title])
      expect(response.body['description']).to eq(new_attributes[:description])
      expect(response).to have_http_status(201)
    end
```

The error:
```
Failure/Error: expect(response.body['title']).to eq(new_attributes[:title])

       expected: "title-updated"
            got: "title"
```

The weird thing is, when I print the response.body, it shows the updated values.

**Comment by JonRowe** [comment]
Closing as this isn't an rspec-expectations issue.

Without knowing whats driving your page, is it possible that response is changing between the time your spec is run and you printing it? `puts(response.body)` and `expect(response.body)` are doing exactly the same thing, so `response.body['title']` is `"title"` when it is run.

**Comment by FlorianGerhardt** [comment]
After some more tests with assigning the response to a variable, I still get the same error, here is the updated code:

`it "updates the requested project" do
     
     saved_response =  put :update, id: project.to_param, project: new_attributes

      expect(saved_response .body['title']).to eq(new_attributes[:title])
      expect(saved_response .body['description']).to eq(new_attributes[:description])
      expect(saved_response ).to have_http_status(201)
    end`

Any ideas where this could be coming from if its not rspec? Running Rails 4.2.7.1 mostly vanilla, just rack-cors for cross origin requests.

**Comment by JonRowe** [comment]
`response` comes from `rails` if you put:

```
it "updates the requested project" do
  saved_response =  put :update, id: project.to_param, project: new_attributes

  puts saved_response.body['title']
  expect(saved_response.body['title']).to eq(new_attributes[:title])
  expect(saved_response.body['description']).to eq(new_attributes[:description])
  expect(saved_response).to have_http_status(201)
end
```

You should see "title" in your console output if your failure is legitimate.
