### ISSUE TITLE
Request to add a configuration option to default to aggregate_failures

### ISSUE THREAD

**Issue by thegranddesign** [rspec/rspec-expectations#969]
I'm not sure how everyone else feels about this, but for me personally I have never had a situation arise where I wouldn't want to aggregate failures if I have multiple expectations in an example.

I'm not saying that's never the case, but what I _am_ saying is that it might be beneficial to most people to be able to enable it by default, and then disable it for a spec (similar to how you can enable mock verification by default and then disable it for a given spec).

What does the core team think about this?

**Comment by xaviershay** [comment]
The [documentation](https://www.relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures) already provides a method to do this.

> RSpec::Core provides metadata integration for this feature. Each example that is tagged with :aggregate_failures will be wrapped in an aggregate_failures block. You can also use config.define_derived_metadata to apply this to every example automatically.

Open to PRs for making that page clearer!

**Comment by thegranddesign** [comment]
@xaviershay I didn't notice that!  Thank you!
