### ISSUE TITLE
 undefined method `expect' for #<Object:0x00000007b1db48> (NoMethodError)

### ISSUE THREAD

**Issue by sandeepnagra** [rspec/rspec-expectations#976]
I keep getting this error though it use to work fine earlier. I tried latest version of rspec 3.5.0 as well and then reverted to previous version I was using i.e. 3.4.0

sample expect statement - expect(page_title).to eq title and expect(element_text).to eq expected_value

My ruby version is ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

**Comment by myronmarston** [comment]
Can you provide a fuller snippet showing the full context?

RSpec does not add `expect` to every object (no more monkey patching!) instead only adding it to a the context in which rspec-core examples run (typically, `it` blocks, `before` hooks, etc).  The fact that the error you reported is `undefined method 'expect' for #<Object:0x00000007b1db48>` makes it sound like you are running this inside some anonymous object, not in an rspec example.

If you need to use `expect` in another context, you can mix-in the methods yourself via a module inclusion in your class:

``` ruby
include RSpec::Matchers
```

**Comment by sandeepnagra** [comment]
Solved it, the culprit was another gem which had following code:

require ‘rspec’

RSpec.configure do |config|
config.expect_with :rspec do |c|
c.syntax = :should
end
end

I commented it out and it works now. Apparently that gem was using should instead of expect and probably to make it work the writer of that gem had added this snippet. That's an old gem, I will look for its alternative.

**Comment by hiteshranaut** [comment]
Just replace  
`expectations.syntax = :should`
with 
`expectations.syntax = [:should , :expect]`

in your spec_helper.rb
