### ISSUE TITLE
Add 'contain' matcher as an alias for 'include'

### ISSUE THREAD

**Issue by pabloh** [rspec/rspec-expectations#979]
Maybe this was proposed and rejected before, but just in case I will post it since I couldn't find any closed issue about it.

I usually find this pattern quite common and I think it reads better as well:
```ruby
RSpec.describe "Item list" do
  let(:items) { [2, 7, 9] }

  it "has all the items" do
    expect(items).to contain_exactly(7, 2, 9)
  end

  it "has some of the items" do
    expect(items).to contain(9, 2)
  end
end
```

WDTF?

**Comment by myronmarston** [comment]
I don't think `contain` adds enough for us to grow our official API with it, but it's one line to add it to your application's test suite:

``` ruby
# in spec_helper.rb
RSpec::Matchers.alias_matcher :contain, :include
```
