### ISSUE TITLE
Possible duplicate: RSpec `all` conflicting with Capybara

### ISSUE THREAD

**Issue by luke-hill** [rspec/rspec-expectations#980]
I'm aware of the plethora of other cases for this. However after reading through all of them, they were mainly focussed on the support code of a project.

I'm in a cucumber project. And in the step definition code we perform our expectations.

Currently `expect[1,1,1].to all eq(1)` is failing for a Webdriver issue which I can diagnose to be related to this conflict.

My question is simple. Do we have / know of a solution for a Cucumber Project where the testing is done in the step definition code (Tried injecting RSpec::Matchers into the World construct and a few other resorting things)

**Comment by JonRowe** [comment]
Adding `RSpec::Matchers.alias_matcher :all, :all_match` or similar should allow you to avoid the conflict.
