### ISSUE TITLE
output matcher fails with exceptions from block

### ISSUE THREAD

**Issue by DavidS** [rspec/rspec-expectations#985]
```
describe "example" do
  it do
    begin
      expect do
        puts "bar"
        raise Exception.new("bar")
      end.to output(/foo/).to_stdout
    rescue Exception => e
      expect(e.message).to match /bar/
    end
  end
end
```

will unexpectedly match, because the thrown exception confuses the code around https://github.com/rspec/rspec-expectations/blob/aab6c1ff529b69d88b75b0ee13f21a3e79064369/lib/rspec/matchers/built_in/output.rb#L143

I'd have expected the code to fail, because the output ("bar") doesn't match `/foo/`.

It might be acceptable to swallow the exception completely, or to always fail on exceptions, even if output up until there would have matched already.

I worked around the issue by handling the exception within the block:

```
describe "example" do
  it do
    expect do
      begin
        puts "bar"
        raise Exception.new("bar")
      rescue Exception => e
        expect(e.message).to match /bar/
      end
    end.to output(/foo/).to_stdout
  end
end
```

but that is not a very intuitive solution.

**Comment by JonRowe** [comment]
This behaviour is occurring because you are rescuing the exception within your test, even if `output(/foo/).to_stdout` was reached you would never see a failures, as the `rescue` would swallow the test failure from the lack of output.

If you re-write this to expect an exception, and then check the output, it works fine:

```Ruby
expect do
  puts "bar"
  raise Exception.new("bar")
end.to raise_error(/bar/).and output(/foo/).to_stdout
```

Even if we changed the matcher to rescue exceptions within it's block, you'd still not see a failure due to your own rescue

**Comment by DavidS** [comment]
My original usecase was rescueing `SystemExit`, which I didn't expect to interfere with rspec's messaging. I also tested it with ArgumentError, and the same results, namely the output matcher's result being ignored.

Even removing the second expect still causes a false positive:

```
describe "example" do
  it do
    begin
      expect do
        puts "bar"
        raise ArgumentError.new("bar")
      end.to output(/foo/).to_stdout
    rescue ArgumentError => e
      puts "ok"
    end
  end
end
```

```
$ bundle exec rspec spec/test_spec.rb 

example
ok
  should output /foo/ to stdout

Finished in 0.00484 seconds (files took 0.07804 seconds to load)
1 example, 0 failures

$ 
```

Without the `rescue`, the test case fails as expected.

I like the combined check, and will adapt my project accordingly, but I still think that the underlying problem is a easily triggered landmine, with insidious side-effects.

**Comment by JonRowe** [comment]
The problem is the structure of your rescue, the point of an exception is to stop flow, so our matchers are never reached, you could do this manually like this:

```Ruby
describe "example" do
  it do
    begin
      expect do
        begin
          puts "bar"
          raise ArgumentError.new("bar")
        rescue ArgumentError => e
          puts "ok"
        end
      end.to output(/foo/).to_stdout
    end
  end
end
```

**Comment by DavidS** [comment]
Yeah, that was my first workaround. With your hint, my final version now looks like this:

```
require 'spec_helper'

describe PDK::CLI::New do
  context 'when no arguments or options are provided' do
    it do
      expect do
        PDK::CLI.run(['new'])
      end.to raise_error(SystemExit) { |error|
        expect(error.status).to be 1
      }.and output(/^USAGE\s+pdk new/m).to_stdout
    end
  end
end
```

and fails in all the right ways, produces instructive docstrings, etc.

**Comment by JonRowe** [comment]
Ah yes, not really a work around, just how Ruby's exceptions work.
