### ISSUE TITLE
Include an option to turn off output truncation

### ISSUE THREAD

**Issue by fabioperrella** [rspec/rspec-expectations#991]
Hi!

When using the matcher `expect(xx).to be_a(yy)` rspec truncate the output if it exceeds a number of chars.

Example:
```
Failure/Error: expect(result).to be_a(Validation::Valid)
       expected #<Validation::Invalid value=#<Bundle id: nil, created_at: nil, updated_at: nil, action: nil, type: "B...on::Finder::NotFoundError: No feature_definition (site_linux) found for contract (hodor_contract)>]> to be a kind of Validation::Valid
```

There is a `...` in the middle of the string (the truncation).

It would nice if there was an option to turn off this feature, because sometimes it is good the see the entire string.

I think this behavior also happens with other matchers.

I didn't find a way to turn off the truncation. Is there a way to do it?

Cheers - Fabio Perrella

**Comment by JonRowe** [comment]
It can't be turned off but theres work in progress to allow configuring it more easily (#951) but for now as a work around set `RSpec::Support::ObjectFormatter.default_instance.max_formatted_output_length = n` where n is high enough for your needs

**Comment by fabioperrella** [comment]
When the project is not using the gem rspec-rails, the solution above raises the error below:

```
uninitialized constant RSpec::Support::ObjectFormatter
```

As an alternative, it is possible to set the following configuration:
```ruby
RSpec.configure do |config|
  config.expect_with :rspec do |c|
    c.max_formatted_output_length = 1000000
  end
end
```

This config was introduced in https://github.com/rspec/rspec-expectations/pull/951

**Comment by JonRowe** [comment]
@fabioperrella It was a work around always intended to be replaced by #951, however the issue you were seeing is by not having a recent version of rspec or by a load error occurring. It's not normal...
