### ISSUE TITLE
Is implicit should still the recommended way? Are we favoring `is_expected.to`?

### ISSUE THREAD

**Issue by lunks** [rspec/rspec-expectations#994]
According to [Should.md](https://github.com/rspec/rspec-expectations/blob/master/Should.md#one-liners) implicit should reads better. I personally disagree and looking on the documentation itself it seems we are favoring `is_expected.to`.

Is a PR welcomed to remove that section? Or is the statement still valid?

**Comment by myronmarston** [comment]
I think we should keep the section, but update it to mention there's also `is_expected`.  A PR is welcome!

**Comment by pirj** [comment]
This seems to have been addressed.
